// Generated by tools/ownership/generate_d3d9_forwarders.py from MinGW d3d9.h.
// Edit the generator or handwritten ownership rules, not this file.
HRESULT WINAPI Factory::QueryInterface(REFIID riid, void** ppvObject) {
    return query(this, riid, ppvObject);
}
ULONG WINAPI Factory::AddRef() {
    return add_ref(this);
}
ULONG WINAPI Factory::Release() {
    return release(this);
}
HRESULT WINAPI Factory::RegisterSoftwareDevice(void* pInitializeFunction) {
    return native_->RegisterSoftwareDevice(pInitializeFunction);
}
UINT WINAPI Factory::GetAdapterCount() {
    return native_->GetAdapterCount();
}
HRESULT WINAPI Factory::GetAdapterIdentifier(UINT Adapter, DWORD Flags, D3DADAPTER_IDENTIFIER9* pIdentifier) {
    return native_->GetAdapterIdentifier(Adapter, Flags, pIdentifier);
}
UINT WINAPI Factory::GetAdapterModeCount(UINT Adapter, D3DFORMAT Format) {
    return native_->GetAdapterModeCount(Adapter, Format);
}
HRESULT WINAPI Factory::EnumAdapterModes(UINT Adapter, D3DFORMAT Format, UINT Mode, D3DDISPLAYMODE* pMode) {
    return native_->EnumAdapterModes(Adapter, Format, Mode, pMode);
}
HRESULT WINAPI Factory::GetAdapterDisplayMode(UINT Adapter, D3DDISPLAYMODE* pMode) {
    return native_->GetAdapterDisplayMode(Adapter, pMode);
}
HRESULT WINAPI Factory::CheckDeviceType(UINT iAdapter, D3DDEVTYPE DevType, D3DFORMAT DisplayFormat, D3DFORMAT BackBufferFormat, WINBOOL bWindowed) {
    return native_->CheckDeviceType(iAdapter, DevType, DisplayFormat, BackBufferFormat, bWindowed);
}
HRESULT WINAPI Factory::CheckDeviceFormat(UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, DWORD Usage, D3DRESOURCETYPE RType, D3DFORMAT CheckFormat) {
    return native_->CheckDeviceFormat(Adapter, DeviceType, AdapterFormat, Usage, RType, CheckFormat);
}
HRESULT WINAPI Factory::CheckDeviceMultiSampleType(UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT SurfaceFormat, WINBOOL Windowed, D3DMULTISAMPLE_TYPE MultiSampleType, DWORD* pQualityLevels) {
    return native_->CheckDeviceMultiSampleType(Adapter, DeviceType, SurfaceFormat, Windowed, MultiSampleType, pQualityLevels);
}
HRESULT WINAPI Factory::CheckDepthStencilMatch(UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, D3DFORMAT RenderTargetFormat, D3DFORMAT DepthStencilFormat) {
    return native_->CheckDepthStencilMatch(Adapter, DeviceType, AdapterFormat, RenderTargetFormat, DepthStencilFormat);
}
HRESULT WINAPI Factory::CheckDeviceFormatConversion(UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT SourceFormat, D3DFORMAT TargetFormat) {
    return native_->CheckDeviceFormatConversion(Adapter, DeviceType, SourceFormat, TargetFormat);
}
HRESULT WINAPI Factory::GetDeviceCaps(UINT Adapter, D3DDEVTYPE DeviceType, D3DCAPS9* pCaps) {
    return native_->GetDeviceCaps(Adapter, DeviceType, pCaps);
}
HMONITOR WINAPI Factory::GetAdapterMonitor(UINT Adapter) {
    return native_->GetAdapterMonitor(Adapter);
}
HRESULT WINAPI Factory::CreateDevice(UINT Adapter, D3DDEVTYPE DeviceType, HWND hFocusWindow, DWORD BehaviorFlags, D3DPRESENT_PARAMETERS* pPresentationParameters, IDirect3DDevice9** ppReturnedDeviceInterface) {
    return create_device(this, Adapter, DeviceType, hFocusWindow, BehaviorFlags, pPresentationParameters, ppReturnedDeviceInterface);
}
HRESULT WINAPI Device::QueryInterface(REFIID riid, void** ppvObject) {
    return query(this, riid, ppvObject);
}
ULONG WINAPI Device::AddRef() {
    return add_ref(this);
}
ULONG WINAPI Device::Release() {
    return release(this);
}
HRESULT WINAPI Device::TestCooperativeLevel() {
    return observe_result(device_of(this), native_->TestCooperativeLevel());
}
UINT WINAPI Device::GetAvailableTextureMem() {
    return native_->GetAvailableTextureMem();
}
HRESULT WINAPI Device::EvictManagedResources() {
    return native_->EvictManagedResources();
}
HRESULT WINAPI Device::GetDirect3D(IDirect3D9** ppD3D9) {
    return get_factory(this, ppD3D9);
}
HRESULT WINAPI Device::GetDeviceCaps(D3DCAPS9* pCaps) {
    return native_->GetDeviceCaps(pCaps);
}
HRESULT WINAPI Device::GetDisplayMode(UINT iSwapChain, D3DDISPLAYMODE* pMode) {
    return native_->GetDisplayMode(iSwapChain, pMode);
}
HRESULT WINAPI Device::GetCreationParameters(D3DDEVICE_CREATION_PARAMETERS * pParameters) {
    return native_->GetCreationParameters(pParameters);
}
HRESULT WINAPI Device::SetCursorProperties(UINT XHotSpot, UINT YHotSpot, IDirect3DSurface9* pCursorBitmap) {
    return native_->SetCursorProperties(XHotSpot, YHotSpot, unwrap(device_of(this), pCursorBitmap));
}
void WINAPI Device::SetCursorPosition(int X, int Y, DWORD Flags) {
    return native_->SetCursorPosition(X, Y, Flags);
}
WINBOOL WINAPI Device::ShowCursor(WINBOOL bShow) {
    return native_->ShowCursor(bShow);
}
HRESULT WINAPI Device::CreateAdditionalSwapChain(D3DPRESENT_PARAMETERS* pPresentationParameters, IDirect3DSwapChain9** pSwapChain) {
    IDirect3DSwapChain9* owned = untouched_output<IDirect3DSwapChain9>();
    const HRESULT hr = native_->CreateAdditionalSwapChain(pPresentationParameters, pSwapChain ? &owned : nullptr);
    return output(device_of(this), hr, owned, pSwapChain);
}
HRESULT WINAPI Device::GetSwapChain(UINT iSwapChain, IDirect3DSwapChain9** pSwapChain) {
    IDirect3DSwapChain9* owned = untouched_output<IDirect3DSwapChain9>();
    const HRESULT hr = native_->GetSwapChain(iSwapChain, pSwapChain ? &owned : nullptr);
    return output(device_of(this), hr, owned, pSwapChain);
}
UINT WINAPI Device::GetNumberOfSwapChains() {
    return native_->GetNumberOfSwapChains();
}
HRESULT WINAPI Device::Reset(D3DPRESENT_PARAMETERS* pPresentationParameters) {
    return reset_device(this, pPresentationParameters);
}
HRESULT WINAPI Device::Present(const RECT * src_rect, const RECT * dst_rect, HWND dst_window_override, const RGNDATA * dirty_region) {
    return observe_result(device_of(this), native_->Present(src_rect, dst_rect, dst_window_override, dirty_region));
}
HRESULT WINAPI Device::GetBackBuffer(UINT iSwapChain, UINT iBackBuffer, D3DBACKBUFFER_TYPE Type, IDirect3DSurface9** ppBackBuffer) {
    IDirect3DSurface9* owned = untouched_output<IDirect3DSurface9>();
    const HRESULT hr = native_->GetBackBuffer(iSwapChain, iBackBuffer, Type, ppBackBuffer ? &owned : nullptr);
    return output(device_of(this), hr, owned, ppBackBuffer);
}
HRESULT WINAPI Device::GetRasterStatus(UINT iSwapChain, D3DRASTER_STATUS* pRasterStatus) {
    return native_->GetRasterStatus(iSwapChain, pRasterStatus);
}
HRESULT WINAPI Device::SetDialogBoxMode(WINBOOL bEnableDialogs) {
    return native_->SetDialogBoxMode(bEnableDialogs);
}
void WINAPI Device::SetGammaRamp(UINT swapchain_idx, DWORD flags, const D3DGAMMARAMP * ramp) {
    return native_->SetGammaRamp(swapchain_idx, flags, ramp);
}
void WINAPI Device::GetGammaRamp(UINT iSwapChain, D3DGAMMARAMP* pRamp) {
    return native_->GetGammaRamp(iSwapChain, pRamp);
}
HRESULT WINAPI Device::CreateTexture(UINT Width, UINT Height, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DTexture9** ppTexture, HANDLE* pSharedHandle) {
    IDirect3DTexture9* owned = untouched_output<IDirect3DTexture9>();
    const HRESULT hr = native_->CreateTexture(Width, Height, Levels, Usage, Format, Pool, ppTexture ? &owned : nullptr, pSharedHandle);
    return output(device_of(this), hr, owned, ppTexture);
}
HRESULT WINAPI Device::CreateVolumeTexture(UINT Width, UINT Height, UINT Depth, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DVolumeTexture9** ppVolumeTexture, HANDLE* pSharedHandle) {
    IDirect3DVolumeTexture9* owned = untouched_output<IDirect3DVolumeTexture9>();
    const HRESULT hr = native_->CreateVolumeTexture(Width, Height, Depth, Levels, Usage, Format, Pool, ppVolumeTexture ? &owned : nullptr, pSharedHandle);
    return output(device_of(this), hr, owned, ppVolumeTexture);
}
HRESULT WINAPI Device::CreateCubeTexture(UINT EdgeLength, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DCubeTexture9** ppCubeTexture, HANDLE* pSharedHandle) {
    IDirect3DCubeTexture9* owned = untouched_output<IDirect3DCubeTexture9>();
    const HRESULT hr = native_->CreateCubeTexture(EdgeLength, Levels, Usage, Format, Pool, ppCubeTexture ? &owned : nullptr, pSharedHandle);
    return output(device_of(this), hr, owned, ppCubeTexture);
}
HRESULT WINAPI Device::CreateVertexBuffer(UINT Length, DWORD Usage, DWORD FVF, D3DPOOL Pool, IDirect3DVertexBuffer9** ppVertexBuffer, HANDLE* pSharedHandle) {
    IDirect3DVertexBuffer9* owned = untouched_output<IDirect3DVertexBuffer9>();
    const HRESULT hr = native_->CreateVertexBuffer(Length, Usage, FVF, Pool, ppVertexBuffer ? &owned : nullptr, pSharedHandle);
    return output(device_of(this), hr, owned, ppVertexBuffer);
}
HRESULT WINAPI Device::CreateIndexBuffer(UINT Length, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DIndexBuffer9** ppIndexBuffer, HANDLE* pSharedHandle) {
    IDirect3DIndexBuffer9* owned = untouched_output<IDirect3DIndexBuffer9>();
    const HRESULT hr = native_->CreateIndexBuffer(Length, Usage, Format, Pool, ppIndexBuffer ? &owned : nullptr, pSharedHandle);
    return output(device_of(this), hr, owned, ppIndexBuffer);
}
HRESULT WINAPI Device::CreateRenderTarget(UINT Width, UINT Height, D3DFORMAT Format, D3DMULTISAMPLE_TYPE MultiSample, DWORD MultisampleQuality, WINBOOL Lockable, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle) {
    IDirect3DSurface9* owned = untouched_output<IDirect3DSurface9>();
    const HRESULT hr = native_->CreateRenderTarget(Width, Height, Format, MultiSample, MultisampleQuality, Lockable, ppSurface ? &owned : nullptr, pSharedHandle);
    return output(device_of(this), hr, owned, ppSurface);
}
HRESULT WINAPI Device::CreateDepthStencilSurface(UINT Width, UINT Height, D3DFORMAT Format, D3DMULTISAMPLE_TYPE MultiSample, DWORD MultisampleQuality, WINBOOL Discard, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle) {
    IDirect3DSurface9* owned = untouched_output<IDirect3DSurface9>();
    const HRESULT hr = native_->CreateDepthStencilSurface(Width, Height, Format, MultiSample, MultisampleQuality, Discard, ppSurface ? &owned : nullptr, pSharedHandle);
    return output(device_of(this), hr, owned, ppSurface);
}
HRESULT WINAPI Device::UpdateSurface(IDirect3DSurface9 * src_surface, const RECT * src_rect, IDirect3DSurface9 * dst_surface, const POINT * dst_point) {
    return native_->UpdateSurface(unwrap_physical_surface(device_of(this), src_surface), src_rect, unwrap_physical_surface(device_of(this), dst_surface), dst_point);
}
HRESULT WINAPI Device::UpdateTexture(IDirect3DBaseTexture9* pSourceTexture, IDirect3DBaseTexture9* pDestinationTexture) {
    return native_->UpdateTexture(unwrap(device_of(this), pSourceTexture), unwrap(device_of(this), pDestinationTexture));
}
HRESULT WINAPI Device::GetRenderTargetData(IDirect3DSurface9* pRenderTarget, IDirect3DSurface9* pDestSurface) {
    return native_->GetRenderTargetData(unwrap_physical_surface(device_of(this), pRenderTarget), unwrap_physical_surface(device_of(this), pDestSurface));
}
HRESULT WINAPI Device::GetFrontBufferData(UINT iSwapChain, IDirect3DSurface9* pDestSurface) {
    return native_->GetFrontBufferData(iSwapChain, unwrap_physical_surface(device_of(this), pDestSurface));
}
HRESULT WINAPI Device::StretchRect(IDirect3DSurface9 * src_surface, const RECT * src_rect, IDirect3DSurface9 * dst_surface, const RECT * dst_rect, D3DTEXTUREFILTERTYPE filter) {
    return native_->StretchRect(unwrap_physical_surface(device_of(this), src_surface), src_rect, unwrap_physical_surface(device_of(this), dst_surface), dst_rect, filter);
}
HRESULT WINAPI Device::ColorFill(IDirect3DSurface9 * surface, const RECT * rect, D3DCOLOR color) {
    return native_->ColorFill(unwrap_physical_surface(device_of(this), surface), rect, color);
}
HRESULT WINAPI Device::CreateOffscreenPlainSurface(UINT Width, UINT Height, D3DFORMAT Format, D3DPOOL Pool, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle) {
    IDirect3DSurface9* owned = untouched_output<IDirect3DSurface9>();
    const HRESULT hr = native_->CreateOffscreenPlainSurface(Width, Height, Format, Pool, ppSurface ? &owned : nullptr, pSharedHandle);
    return output(device_of(this), hr, owned, ppSurface);
}
HRESULT WINAPI Device::SetRenderTarget(DWORD RenderTargetIndex, IDirect3DSurface9* pRenderTarget) {
    return native_->SetRenderTarget(RenderTargetIndex, unwrap(device_of(this), pRenderTarget));
}
HRESULT WINAPI Device::GetRenderTarget(DWORD RenderTargetIndex, IDirect3DSurface9** ppRenderTarget) {
    IDirect3DSurface9* owned = untouched_output<IDirect3DSurface9>();
    const HRESULT hr = native_->GetRenderTarget(RenderTargetIndex, ppRenderTarget ? &owned : nullptr);
    return output(device_of(this), hr, owned, ppRenderTarget);
}
HRESULT WINAPI Device::SetDepthStencilSurface(IDirect3DSurface9* pNewZStencil) {
    return set_depth(this, pNewZStencil);
}
HRESULT WINAPI Device::GetDepthStencilSurface(IDirect3DSurface9** ppZStencilSurface) {
    return get_depth(this, ppZStencilSurface);
}
HRESULT WINAPI Device::BeginScene() {
    return native_->BeginScene();
}
HRESULT WINAPI Device::EndScene() {
    return native_->EndScene();
}
HRESULT WINAPI Device::Clear(DWORD rect_count, const D3DRECT * rects, DWORD flags, D3DCOLOR color, float z, DWORD stencil) {
    return clear_device(this, rect_count, rects, flags, color, z, stencil);
}
HRESULT WINAPI Device::SetTransform(D3DTRANSFORMSTATETYPE state, const D3DMATRIX * matrix) {
    return native_->SetTransform(state, matrix);
}
HRESULT WINAPI Device::GetTransform(D3DTRANSFORMSTATETYPE State, D3DMATRIX* pMatrix) {
    return native_->GetTransform(State, pMatrix);
}
HRESULT WINAPI Device::MultiplyTransform(D3DTRANSFORMSTATETYPE state, const D3DMATRIX * matrix) {
    return native_->MultiplyTransform(state, matrix);
}
HRESULT WINAPI Device::SetViewport(const D3DVIEWPORT9 * viewport) {
    return native_->SetViewport(viewport);
}
HRESULT WINAPI Device::GetViewport(D3DVIEWPORT9* pViewport) {
    return native_->GetViewport(pViewport);
}
HRESULT WINAPI Device::SetMaterial(const D3DMATERIAL9 * material) {
    return native_->SetMaterial(material);
}
HRESULT WINAPI Device::GetMaterial(D3DMATERIAL9* pMaterial) {
    return native_->GetMaterial(pMaterial);
}
HRESULT WINAPI Device::SetLight(DWORD index, const D3DLIGHT9 * light) {
    return native_->SetLight(index, light);
}
HRESULT WINAPI Device::GetLight(DWORD Index, D3DLIGHT9* arg1) {
    return native_->GetLight(Index, arg1);
}
HRESULT WINAPI Device::LightEnable(DWORD Index, WINBOOL Enable) {
    return native_->LightEnable(Index, Enable);
}
HRESULT WINAPI Device::GetLightEnable(DWORD Index, WINBOOL* pEnable) {
    return native_->GetLightEnable(Index, pEnable);
}
HRESULT WINAPI Device::SetClipPlane(DWORD index, const float * plane) {
    return native_->SetClipPlane(index, plane);
}
HRESULT WINAPI Device::GetClipPlane(DWORD Index, float* pPlane) {
    return native_->GetClipPlane(Index, pPlane);
}
HRESULT WINAPI Device::SetRenderState(D3DRENDERSTATETYPE State, DWORD Value) {
    return native_->SetRenderState(State, Value);
}
HRESULT WINAPI Device::GetRenderState(D3DRENDERSTATETYPE State, DWORD* pValue) {
    return native_->GetRenderState(State, pValue);
}
HRESULT WINAPI Device::CreateStateBlock(D3DSTATEBLOCKTYPE Type, IDirect3DStateBlock9** ppSB) {
    IDirect3DStateBlock9* owned = untouched_output<IDirect3DStateBlock9>();
    const HRESULT hr = native_->CreateStateBlock(Type, ppSB ? &owned : nullptr);
    return output(device_of(this), hr, owned, ppSB);
}
HRESULT WINAPI Device::BeginStateBlock() {
    return native_->BeginStateBlock();
}
HRESULT WINAPI Device::EndStateBlock(IDirect3DStateBlock9** ppSB) {
    IDirect3DStateBlock9* owned = untouched_output<IDirect3DStateBlock9>();
    const HRESULT hr = native_->EndStateBlock(ppSB ? &owned : nullptr);
    return output(device_of(this), hr, owned, ppSB);
}
HRESULT WINAPI Device::SetClipStatus(const D3DCLIPSTATUS9 * clip_status) {
    return native_->SetClipStatus(clip_status);
}
HRESULT WINAPI Device::GetClipStatus(D3DCLIPSTATUS9* pClipStatus) {
    return native_->GetClipStatus(pClipStatus);
}
HRESULT WINAPI Device::GetTexture(DWORD Stage, IDirect3DBaseTexture9** ppTexture) {
    IDirect3DBaseTexture9* owned = untouched_output<IDirect3DBaseTexture9>();
    const HRESULT hr = native_->GetTexture(Stage, ppTexture ? &owned : nullptr);
    return output(device_of(this), hr, owned, ppTexture);
}
HRESULT WINAPI Device::SetTexture(DWORD Stage, IDirect3DBaseTexture9* pTexture) {
    return native_->SetTexture(Stage, unwrap(device_of(this), pTexture));
}
HRESULT WINAPI Device::GetTextureStageState(DWORD Stage, D3DTEXTURESTAGESTATETYPE Type, DWORD* pValue) {
    return native_->GetTextureStageState(Stage, Type, pValue);
}
HRESULT WINAPI Device::SetTextureStageState(DWORD Stage, D3DTEXTURESTAGESTATETYPE Type, DWORD Value) {
    return native_->SetTextureStageState(Stage, Type, Value);
}
HRESULT WINAPI Device::GetSamplerState(DWORD Sampler, D3DSAMPLERSTATETYPE Type, DWORD* pValue) {
    return native_->GetSamplerState(Sampler, Type, pValue);
}
HRESULT WINAPI Device::SetSamplerState(DWORD Sampler, D3DSAMPLERSTATETYPE Type, DWORD Value) {
    return native_->SetSamplerState(Sampler, Type, Value);
}
HRESULT WINAPI Device::ValidateDevice(DWORD* pNumPasses) {
    return native_->ValidateDevice(pNumPasses);
}
HRESULT WINAPI Device::SetPaletteEntries(UINT palette_idx, const PALETTEENTRY * entries) {
    return native_->SetPaletteEntries(palette_idx, entries);
}
HRESULT WINAPI Device::GetPaletteEntries(UINT PaletteNumber, PALETTEENTRY* pEntries) {
    return native_->GetPaletteEntries(PaletteNumber, pEntries);
}
HRESULT WINAPI Device::SetCurrentTexturePalette(UINT PaletteNumber) {
    return native_->SetCurrentTexturePalette(PaletteNumber);
}
HRESULT WINAPI Device::GetCurrentTexturePalette(UINT * PaletteNumber) {
    return native_->GetCurrentTexturePalette(PaletteNumber);
}
HRESULT WINAPI Device::SetScissorRect(const RECT * rect) {
    return native_->SetScissorRect(rect);
}
HRESULT WINAPI Device::GetScissorRect(RECT* pRect) {
    return native_->GetScissorRect(pRect);
}
HRESULT WINAPI Device::SetSoftwareVertexProcessing(WINBOOL bSoftware) {
    return native_->SetSoftwareVertexProcessing(bSoftware);
}
WINBOOL WINAPI Device::GetSoftwareVertexProcessing() {
    return native_->GetSoftwareVertexProcessing();
}
HRESULT WINAPI Device::SetNPatchMode(float nSegments) {
    return native_->SetNPatchMode(nSegments);
}
float WINAPI Device::GetNPatchMode() {
    return native_->GetNPatchMode();
}
HRESULT WINAPI Device::DrawPrimitive(D3DPRIMITIVETYPE PrimitiveType, UINT StartVertex, UINT PrimitiveCount) {
    return draw_device(this, [&]() { return native_->DrawPrimitive(PrimitiveType, StartVertex, PrimitiveCount); });
}
HRESULT WINAPI Device::DrawIndexedPrimitive(D3DPRIMITIVETYPE arg0, INT BaseVertexIndex, UINT MinVertexIndex, UINT NumVertices, UINT startIndex, UINT primCount) {
    return draw_device(this, [&]() { return native_->DrawIndexedPrimitive(arg0, BaseVertexIndex, MinVertexIndex, NumVertices, startIndex, primCount); });
}
HRESULT WINAPI Device::DrawPrimitiveUP(D3DPRIMITIVETYPE primitive_type, UINT primitive_count, const void * data, UINT stride) {
    return draw_device(this, [&]() { return native_->DrawPrimitiveUP(primitive_type, primitive_count, data, stride); });
}
HRESULT WINAPI Device::DrawIndexedPrimitiveUP(D3DPRIMITIVETYPE primitive_type, UINT min_vertex_idx, UINT vertex_count, UINT primitive_count, const void * index_data, D3DFORMAT index_format, const void * data, UINT stride) {
    return draw_device(this, [&]() { return native_->DrawIndexedPrimitiveUP(primitive_type, min_vertex_idx, vertex_count, primitive_count, index_data, index_format, data, stride); });
}
HRESULT WINAPI Device::ProcessVertices(UINT SrcStartIndex, UINT DestIndex, UINT VertexCount, IDirect3DVertexBuffer9* pDestBuffer, IDirect3DVertexDeclaration9* pVertexDecl, DWORD Flags) {
    return native_->ProcessVertices(SrcStartIndex, DestIndex, VertexCount, unwrap(device_of(this), pDestBuffer), unwrap(device_of(this), pVertexDecl), Flags);
}
HRESULT WINAPI Device::CreateVertexDeclaration(const D3DVERTEXELEMENT9 * elements, IDirect3DVertexDeclaration9 ** declaration) {
    IDirect3DVertexDeclaration9* owned = untouched_output<IDirect3DVertexDeclaration9>();
    const HRESULT hr = native_->CreateVertexDeclaration(elements, declaration ? &owned : nullptr);
    return output(device_of(this), hr, owned, declaration);
}
HRESULT WINAPI Device::SetVertexDeclaration(IDirect3DVertexDeclaration9* pDecl) {
    return native_->SetVertexDeclaration(unwrap(device_of(this), pDecl));
}
HRESULT WINAPI Device::GetVertexDeclaration(IDirect3DVertexDeclaration9** ppDecl) {
    IDirect3DVertexDeclaration9* owned = untouched_output<IDirect3DVertexDeclaration9>();
    const HRESULT hr = native_->GetVertexDeclaration(ppDecl ? &owned : nullptr);
    return output(device_of(this), hr, owned, ppDecl);
}
HRESULT WINAPI Device::SetFVF(DWORD FVF) {
    return native_->SetFVF(FVF);
}
HRESULT WINAPI Device::GetFVF(DWORD* pFVF) {
    return native_->GetFVF(pFVF);
}
HRESULT WINAPI Device::CreateVertexShader(const DWORD * byte_code, IDirect3DVertexShader9 ** shader) {
    IDirect3DVertexShader9* owned = untouched_output<IDirect3DVertexShader9>();
    const HRESULT hr = native_->CreateVertexShader(byte_code, shader ? &owned : nullptr);
    return output(device_of(this), hr, owned, shader);
}
HRESULT WINAPI Device::SetVertexShader(IDirect3DVertexShader9* pShader) {
    return native_->SetVertexShader(unwrap(device_of(this), pShader));
}
HRESULT WINAPI Device::GetVertexShader(IDirect3DVertexShader9** ppShader) {
    IDirect3DVertexShader9* owned = untouched_output<IDirect3DVertexShader9>();
    const HRESULT hr = native_->GetVertexShader(ppShader ? &owned : nullptr);
    return output(device_of(this), hr, owned, ppShader);
}
HRESULT WINAPI Device::SetVertexShaderConstantF(UINT reg_idx, const float * data, UINT count) {
    return native_->SetVertexShaderConstantF(reg_idx, data, count);
}
HRESULT WINAPI Device::GetVertexShaderConstantF(UINT StartRegister, float* pConstantData, UINT Vector4fCount) {
    return native_->GetVertexShaderConstantF(StartRegister, pConstantData, Vector4fCount);
}
HRESULT WINAPI Device::SetVertexShaderConstantI(UINT reg_idx, const int * data, UINT count) {
    return native_->SetVertexShaderConstantI(reg_idx, data, count);
}
HRESULT WINAPI Device::GetVertexShaderConstantI(UINT StartRegister, int* pConstantData, UINT Vector4iCount) {
    return native_->GetVertexShaderConstantI(StartRegister, pConstantData, Vector4iCount);
}
HRESULT WINAPI Device::SetVertexShaderConstantB(UINT reg_idx, const WINBOOL * data, UINT count) {
    return native_->SetVertexShaderConstantB(reg_idx, data, count);
}
HRESULT WINAPI Device::GetVertexShaderConstantB(UINT StartRegister, WINBOOL* pConstantData, UINT BoolCount) {
    return native_->GetVertexShaderConstantB(StartRegister, pConstantData, BoolCount);
}
HRESULT WINAPI Device::SetStreamSource(UINT StreamNumber, IDirect3DVertexBuffer9* pStreamData, UINT OffsetInBytes, UINT Stride) {
    return native_->SetStreamSource(StreamNumber, unwrap(device_of(this), pStreamData), OffsetInBytes, Stride);
}
HRESULT WINAPI Device::GetStreamSource(UINT StreamNumber, IDirect3DVertexBuffer9** ppStreamData, UINT* OffsetInBytes, UINT* pStride) {
    IDirect3DVertexBuffer9* owned = untouched_output<IDirect3DVertexBuffer9>();
    const HRESULT hr = native_->GetStreamSource(StreamNumber, ppStreamData ? &owned : nullptr, OffsetInBytes, pStride);
    return output(device_of(this), hr, owned, ppStreamData);
}
HRESULT WINAPI Device::SetStreamSourceFreq(UINT StreamNumber, UINT Divider) {
    return native_->SetStreamSourceFreq(StreamNumber, Divider);
}
HRESULT WINAPI Device::GetStreamSourceFreq(UINT StreamNumber, UINT* Divider) {
    return native_->GetStreamSourceFreq(StreamNumber, Divider);
}
HRESULT WINAPI Device::SetIndices(IDirect3DIndexBuffer9* pIndexData) {
    return native_->SetIndices(unwrap(device_of(this), pIndexData));
}
HRESULT WINAPI Device::GetIndices(IDirect3DIndexBuffer9** ppIndexData) {
    IDirect3DIndexBuffer9* owned = untouched_output<IDirect3DIndexBuffer9>();
    const HRESULT hr = native_->GetIndices(ppIndexData ? &owned : nullptr);
    return output(device_of(this), hr, owned, ppIndexData);
}
HRESULT WINAPI Device::CreatePixelShader(const DWORD * byte_code, IDirect3DPixelShader9 ** shader) {
    IDirect3DPixelShader9* owned = untouched_output<IDirect3DPixelShader9>();
    const HRESULT hr = native_->CreatePixelShader(byte_code, shader ? &owned : nullptr);
    return output(device_of(this), hr, owned, shader);
}
HRESULT WINAPI Device::SetPixelShader(IDirect3DPixelShader9* pShader) {
    return native_->SetPixelShader(unwrap(device_of(this), pShader));
}
HRESULT WINAPI Device::GetPixelShader(IDirect3DPixelShader9** ppShader) {
    IDirect3DPixelShader9* owned = untouched_output<IDirect3DPixelShader9>();
    const HRESULT hr = native_->GetPixelShader(ppShader ? &owned : nullptr);
    return output(device_of(this), hr, owned, ppShader);
}
HRESULT WINAPI Device::SetPixelShaderConstantF(UINT reg_idx, const float * data, UINT count) {
    return native_->SetPixelShaderConstantF(reg_idx, data, count);
}
HRESULT WINAPI Device::GetPixelShaderConstantF(UINT StartRegister, float* pConstantData, UINT Vector4fCount) {
    return native_->GetPixelShaderConstantF(StartRegister, pConstantData, Vector4fCount);
}
HRESULT WINAPI Device::SetPixelShaderConstantI(UINT reg_idx, const int * data, UINT count) {
    return native_->SetPixelShaderConstantI(reg_idx, data, count);
}
HRESULT WINAPI Device::GetPixelShaderConstantI(UINT StartRegister, int* pConstantData, UINT Vector4iCount) {
    return native_->GetPixelShaderConstantI(StartRegister, pConstantData, Vector4iCount);
}
HRESULT WINAPI Device::SetPixelShaderConstantB(UINT reg_idx, const WINBOOL * data, UINT count) {
    return native_->SetPixelShaderConstantB(reg_idx, data, count);
}
HRESULT WINAPI Device::GetPixelShaderConstantB(UINT StartRegister, WINBOOL* pConstantData, UINT BoolCount) {
    return native_->GetPixelShaderConstantB(StartRegister, pConstantData, BoolCount);
}
HRESULT WINAPI Device::DrawRectPatch(UINT handle, const float * segment_count, const D3DRECTPATCH_INFO * patch_info) {
    return draw_device(this, [&]() { return native_->DrawRectPatch(handle, segment_count, patch_info); });
}
HRESULT WINAPI Device::DrawTriPatch(UINT handle, const float * segment_count, const D3DTRIPATCH_INFO * patch_info) {
    return draw_device(this, [&]() { return native_->DrawTriPatch(handle, segment_count, patch_info); });
}
HRESULT WINAPI Device::DeletePatch(UINT Handle) {
    return native_->DeletePatch(Handle);
}
HRESULT WINAPI Device::CreateQuery(D3DQUERYTYPE Type, IDirect3DQuery9** ppQuery) {
    IDirect3DQuery9* owned = untouched_output<IDirect3DQuery9>();
    const HRESULT hr = native_->CreateQuery(Type, ppQuery ? &owned : nullptr);
    return output(device_of(this), hr, owned, ppQuery);
}
HRESULT WINAPI Texture::QueryInterface(REFIID riid, void** ppvObject) {
    return query(this, riid, ppvObject);
}
ULONG WINAPI Texture::AddRef() {
    return add_ref(this);
}
ULONG WINAPI Texture::Release() {
    return release(this);
}
HRESULT WINAPI Texture::GetDevice(IDirect3DDevice9** ppDevice) {
    return get_device(this, ppDevice);
}
HRESULT WINAPI Texture::SetPrivateData(REFGUID guid, const void * data, DWORD data_size, DWORD flags) {
    return native_->SetPrivateData(guid, data, data_size, flags);
}
HRESULT WINAPI Texture::GetPrivateData(REFGUID refguid, void* pData, DWORD* pSizeOfData) {
    return native_->GetPrivateData(refguid, pData, pSizeOfData);
}
HRESULT WINAPI Texture::FreePrivateData(REFGUID refguid) {
    return native_->FreePrivateData(refguid);
}
DWORD WINAPI Texture::SetPriority(DWORD PriorityNew) {
    return native_->SetPriority(PriorityNew);
}
DWORD WINAPI Texture::GetPriority() {
    return native_->GetPriority();
}
void WINAPI Texture::PreLoad() {
    return native_->PreLoad();
}
D3DRESOURCETYPE WINAPI Texture::GetType() {
    return native_->GetType();
}
DWORD WINAPI Texture::SetLOD(DWORD LODNew) {
    return native_->SetLOD(LODNew);
}
DWORD WINAPI Texture::GetLOD() {
    return native_->GetLOD();
}
DWORD WINAPI Texture::GetLevelCount() {
    return native_->GetLevelCount();
}
HRESULT WINAPI Texture::SetAutoGenFilterType(D3DTEXTUREFILTERTYPE FilterType) {
    return native_->SetAutoGenFilterType(FilterType);
}
D3DTEXTUREFILTERTYPE WINAPI Texture::GetAutoGenFilterType() {
    return native_->GetAutoGenFilterType();
}
void WINAPI Texture::GenerateMipSubLevels() {
    return native_->GenerateMipSubLevels();
}
HRESULT WINAPI Texture::GetLevelDesc(UINT Level, D3DSURFACE_DESC* pDesc) {
    return native_->GetLevelDesc(Level, pDesc);
}
HRESULT WINAPI Texture::GetSurfaceLevel(UINT Level, IDirect3DSurface9** ppSurfaceLevel) {
    IDirect3DSurface9* owned = untouched_output<IDirect3DSurface9>();
    const HRESULT hr = native_->GetSurfaceLevel(Level, ppSurfaceLevel ? &owned : nullptr);
    return output(device_of(this), hr, owned, ppSurfaceLevel);
}
HRESULT WINAPI Texture::LockRect(UINT level, D3DLOCKED_RECT * locked_rect, const RECT * rect, DWORD flags) {
    return native_->LockRect(level, locked_rect, rect, flags);
}
HRESULT WINAPI Texture::UnlockRect(UINT Level) {
    return native_->UnlockRect(Level);
}
HRESULT WINAPI Texture::AddDirtyRect(const RECT * dirty_rect) {
    return native_->AddDirtyRect(dirty_rect);
}
HRESULT WINAPI CubeTexture::QueryInterface(REFIID riid, void** ppvObject) {
    return query(this, riid, ppvObject);
}
ULONG WINAPI CubeTexture::AddRef() {
    return add_ref(this);
}
ULONG WINAPI CubeTexture::Release() {
    return release(this);
}
HRESULT WINAPI CubeTexture::GetDevice(IDirect3DDevice9** ppDevice) {
    return get_device(this, ppDevice);
}
HRESULT WINAPI CubeTexture::SetPrivateData(REFGUID guid, const void * data, DWORD data_size, DWORD flags) {
    return native_->SetPrivateData(guid, data, data_size, flags);
}
HRESULT WINAPI CubeTexture::GetPrivateData(REFGUID refguid, void* pData, DWORD* pSizeOfData) {
    return native_->GetPrivateData(refguid, pData, pSizeOfData);
}
HRESULT WINAPI CubeTexture::FreePrivateData(REFGUID refguid) {
    return native_->FreePrivateData(refguid);
}
DWORD WINAPI CubeTexture::SetPriority(DWORD PriorityNew) {
    return native_->SetPriority(PriorityNew);
}
DWORD WINAPI CubeTexture::GetPriority() {
    return native_->GetPriority();
}
void WINAPI CubeTexture::PreLoad() {
    return native_->PreLoad();
}
D3DRESOURCETYPE WINAPI CubeTexture::GetType() {
    return native_->GetType();
}
DWORD WINAPI CubeTexture::SetLOD(DWORD LODNew) {
    return native_->SetLOD(LODNew);
}
DWORD WINAPI CubeTexture::GetLOD() {
    return native_->GetLOD();
}
DWORD WINAPI CubeTexture::GetLevelCount() {
    return native_->GetLevelCount();
}
HRESULT WINAPI CubeTexture::SetAutoGenFilterType(D3DTEXTUREFILTERTYPE FilterType) {
    return native_->SetAutoGenFilterType(FilterType);
}
D3DTEXTUREFILTERTYPE WINAPI CubeTexture::GetAutoGenFilterType() {
    return native_->GetAutoGenFilterType();
}
void WINAPI CubeTexture::GenerateMipSubLevels() {
    return native_->GenerateMipSubLevels();
}
HRESULT WINAPI CubeTexture::GetLevelDesc(UINT Level, D3DSURFACE_DESC* pDesc) {
    return native_->GetLevelDesc(Level, pDesc);
}
HRESULT WINAPI CubeTexture::GetCubeMapSurface(D3DCUBEMAP_FACES FaceType, UINT Level, IDirect3DSurface9** ppCubeMapSurface) {
    IDirect3DSurface9* owned = untouched_output<IDirect3DSurface9>();
    const HRESULT hr = native_->GetCubeMapSurface(FaceType, Level, ppCubeMapSurface ? &owned : nullptr);
    return output(device_of(this), hr, owned, ppCubeMapSurface);
}
HRESULT WINAPI CubeTexture::LockRect(D3DCUBEMAP_FACES face, UINT level, D3DLOCKED_RECT * locked_rect, const RECT * rect, DWORD flags) {
    return native_->LockRect(face, level, locked_rect, rect, flags);
}
HRESULT WINAPI CubeTexture::UnlockRect(D3DCUBEMAP_FACES FaceType, UINT Level) {
    return native_->UnlockRect(FaceType, Level);
}
HRESULT WINAPI CubeTexture::AddDirtyRect(D3DCUBEMAP_FACES face, const RECT * dirty_rect) {
    return native_->AddDirtyRect(face, dirty_rect);
}
HRESULT WINAPI VolumeTexture::QueryInterface(REFIID riid, void** ppvObject) {
    return query(this, riid, ppvObject);
}
ULONG WINAPI VolumeTexture::AddRef() {
    return add_ref(this);
}
ULONG WINAPI VolumeTexture::Release() {
    return release(this);
}
HRESULT WINAPI VolumeTexture::GetDevice(IDirect3DDevice9** ppDevice) {
    return get_device(this, ppDevice);
}
HRESULT WINAPI VolumeTexture::SetPrivateData(REFGUID guid, const void * data, DWORD data_size, DWORD flags) {
    return native_->SetPrivateData(guid, data, data_size, flags);
}
HRESULT WINAPI VolumeTexture::GetPrivateData(REFGUID refguid, void* pData, DWORD* pSizeOfData) {
    return native_->GetPrivateData(refguid, pData, pSizeOfData);
}
HRESULT WINAPI VolumeTexture::FreePrivateData(REFGUID refguid) {
    return native_->FreePrivateData(refguid);
}
DWORD WINAPI VolumeTexture::SetPriority(DWORD PriorityNew) {
    return native_->SetPriority(PriorityNew);
}
DWORD WINAPI VolumeTexture::GetPriority() {
    return native_->GetPriority();
}
void WINAPI VolumeTexture::PreLoad() {
    return native_->PreLoad();
}
D3DRESOURCETYPE WINAPI VolumeTexture::GetType() {
    return native_->GetType();
}
DWORD WINAPI VolumeTexture::SetLOD(DWORD LODNew) {
    return native_->SetLOD(LODNew);
}
DWORD WINAPI VolumeTexture::GetLOD() {
    return native_->GetLOD();
}
DWORD WINAPI VolumeTexture::GetLevelCount() {
    return native_->GetLevelCount();
}
HRESULT WINAPI VolumeTexture::SetAutoGenFilterType(D3DTEXTUREFILTERTYPE FilterType) {
    return native_->SetAutoGenFilterType(FilterType);
}
D3DTEXTUREFILTERTYPE WINAPI VolumeTexture::GetAutoGenFilterType() {
    return native_->GetAutoGenFilterType();
}
void WINAPI VolumeTexture::GenerateMipSubLevels() {
    return native_->GenerateMipSubLevels();
}
HRESULT WINAPI VolumeTexture::GetLevelDesc(UINT Level, D3DVOLUME_DESC * pDesc) {
    return native_->GetLevelDesc(Level, pDesc);
}
HRESULT WINAPI VolumeTexture::GetVolumeLevel(UINT Level, IDirect3DVolume9** ppVolumeLevel) {
    IDirect3DVolume9* owned = untouched_output<IDirect3DVolume9>();
    const HRESULT hr = native_->GetVolumeLevel(Level, ppVolumeLevel ? &owned : nullptr);
    return output(device_of(this), hr, owned, ppVolumeLevel);
}
HRESULT WINAPI VolumeTexture::LockBox(UINT level, D3DLOCKED_BOX * locked_box, const D3DBOX * box, DWORD flags) {
    return native_->LockBox(level, locked_box, box, flags);
}
HRESULT WINAPI VolumeTexture::UnlockBox(UINT Level) {
    return native_->UnlockBox(Level);
}
HRESULT WINAPI VolumeTexture::AddDirtyBox(const D3DBOX * dirty_box) {
    return native_->AddDirtyBox(dirty_box);
}
HRESULT WINAPI Surface::QueryInterface(REFIID riid, void** ppvObject) {
    return query(this, riid, ppvObject);
}
ULONG WINAPI Surface::AddRef() {
    return add_ref(this);
}
ULONG WINAPI Surface::Release() {
    return release(this);
}
HRESULT WINAPI Surface::GetDevice(IDirect3DDevice9** ppDevice) {
    return get_device(this, ppDevice);
}
HRESULT WINAPI Surface::SetPrivateData(REFGUID guid, const void * data, DWORD data_size, DWORD flags) {
    return native_->SetPrivateData(guid, data, data_size, flags);
}
HRESULT WINAPI Surface::GetPrivateData(REFGUID refguid, void* pData, DWORD* pSizeOfData) {
    return native_->GetPrivateData(refguid, pData, pSizeOfData);
}
HRESULT WINAPI Surface::FreePrivateData(REFGUID refguid) {
    return native_->FreePrivateData(refguid);
}
DWORD WINAPI Surface::SetPriority(DWORD PriorityNew) {
    return native_->SetPriority(PriorityNew);
}
DWORD WINAPI Surface::GetPriority() {
    return native_->GetPriority();
}
void WINAPI Surface::PreLoad() {
    return native_->PreLoad();
}
D3DRESOURCETYPE WINAPI Surface::GetType() {
    return native_->GetType();
}
HRESULT WINAPI Surface::GetContainer(REFIID riid, void** ppContainer) {
    return get_container(this, riid, ppContainer);
}
HRESULT WINAPI Surface::GetDesc(D3DSURFACE_DESC* pDesc) {
    return native_->GetDesc(pDesc);
}
HRESULT WINAPI Surface::LockRect(D3DLOCKED_RECT * locked_rect, const RECT * rect, DWORD flags) {
    return native_->LockRect(locked_rect, rect, flags);
}
HRESULT WINAPI Surface::UnlockRect() {
    return native_->UnlockRect();
}
HRESULT WINAPI Surface::GetDC(HDC* phdc) {
    return native_->GetDC(phdc);
}
HRESULT WINAPI Surface::ReleaseDC(HDC hdc) {
    return native_->ReleaseDC(hdc);
}
HRESULT WINAPI Volume::QueryInterface(REFIID riid, void** ppvObject) {
    return query(this, riid, ppvObject);
}
ULONG WINAPI Volume::AddRef() {
    return add_ref(this);
}
ULONG WINAPI Volume::Release() {
    return release(this);
}
HRESULT WINAPI Volume::GetDevice(IDirect3DDevice9** ppDevice) {
    return get_device(this, ppDevice);
}
HRESULT WINAPI Volume::SetPrivateData(REFGUID guid, const void * data, DWORD data_size, DWORD flags) {
    return native_->SetPrivateData(guid, data, data_size, flags);
}
HRESULT WINAPI Volume::GetPrivateData(REFGUID refguid, void* pData, DWORD* pSizeOfData) {
    return native_->GetPrivateData(refguid, pData, pSizeOfData);
}
HRESULT WINAPI Volume::FreePrivateData(REFGUID refguid) {
    return native_->FreePrivateData(refguid);
}
HRESULT WINAPI Volume::GetContainer(REFIID riid, void** ppContainer) {
    return get_container(this, riid, ppContainer);
}
HRESULT WINAPI Volume::GetDesc(D3DVOLUME_DESC* pDesc) {
    return native_->GetDesc(pDesc);
}
HRESULT WINAPI Volume::LockBox(D3DLOCKED_BOX * locked_box, const D3DBOX * box, DWORD flags) {
    return native_->LockBox(locked_box, box, flags);
}
HRESULT WINAPI Volume::UnlockBox() {
    return native_->UnlockBox();
}
HRESULT WINAPI VertexBuffer::QueryInterface(REFIID riid, void** ppvObject) {
    return query(this, riid, ppvObject);
}
ULONG WINAPI VertexBuffer::AddRef() {
    return add_ref(this);
}
ULONG WINAPI VertexBuffer::Release() {
    return release(this);
}
HRESULT WINAPI VertexBuffer::GetDevice(IDirect3DDevice9** ppDevice) {
    return get_device(this, ppDevice);
}
HRESULT WINAPI VertexBuffer::SetPrivateData(REFGUID guid, const void * data, DWORD data_size, DWORD flags) {
    return native_->SetPrivateData(guid, data, data_size, flags);
}
HRESULT WINAPI VertexBuffer::GetPrivateData(REFGUID refguid, void* pData, DWORD* pSizeOfData) {
    return native_->GetPrivateData(refguid, pData, pSizeOfData);
}
HRESULT WINAPI VertexBuffer::FreePrivateData(REFGUID refguid) {
    return native_->FreePrivateData(refguid);
}
DWORD WINAPI VertexBuffer::SetPriority(DWORD PriorityNew) {
    return native_->SetPriority(PriorityNew);
}
DWORD WINAPI VertexBuffer::GetPriority() {
    return native_->GetPriority();
}
void WINAPI VertexBuffer::PreLoad() {
    return native_->PreLoad();
}
D3DRESOURCETYPE WINAPI VertexBuffer::GetType() {
    return native_->GetType();
}
HRESULT WINAPI VertexBuffer::Lock(UINT OffsetToLock, UINT SizeToLock, void** ppbData, DWORD Flags) {
    return native_->Lock(OffsetToLock, SizeToLock, ppbData, Flags);
}
HRESULT WINAPI VertexBuffer::Unlock() {
    return native_->Unlock();
}
HRESULT WINAPI VertexBuffer::GetDesc(D3DVERTEXBUFFER_DESC* pDesc) {
    return native_->GetDesc(pDesc);
}
HRESULT WINAPI IndexBuffer::QueryInterface(REFIID riid, void** ppvObject) {
    return query(this, riid, ppvObject);
}
ULONG WINAPI IndexBuffer::AddRef() {
    return add_ref(this);
}
ULONG WINAPI IndexBuffer::Release() {
    return release(this);
}
HRESULT WINAPI IndexBuffer::GetDevice(IDirect3DDevice9** ppDevice) {
    return get_device(this, ppDevice);
}
HRESULT WINAPI IndexBuffer::SetPrivateData(REFGUID guid, const void * data, DWORD data_size, DWORD flags) {
    return native_->SetPrivateData(guid, data, data_size, flags);
}
HRESULT WINAPI IndexBuffer::GetPrivateData(REFGUID refguid, void* pData, DWORD* pSizeOfData) {
    return native_->GetPrivateData(refguid, pData, pSizeOfData);
}
HRESULT WINAPI IndexBuffer::FreePrivateData(REFGUID refguid) {
    return native_->FreePrivateData(refguid);
}
DWORD WINAPI IndexBuffer::SetPriority(DWORD PriorityNew) {
    return native_->SetPriority(PriorityNew);
}
DWORD WINAPI IndexBuffer::GetPriority() {
    return native_->GetPriority();
}
void WINAPI IndexBuffer::PreLoad() {
    return native_->PreLoad();
}
D3DRESOURCETYPE WINAPI IndexBuffer::GetType() {
    return native_->GetType();
}
HRESULT WINAPI IndexBuffer::Lock(UINT OffsetToLock, UINT SizeToLock, void** ppbData, DWORD Flags) {
    return native_->Lock(OffsetToLock, SizeToLock, ppbData, Flags);
}
HRESULT WINAPI IndexBuffer::Unlock() {
    return native_->Unlock();
}
HRESULT WINAPI IndexBuffer::GetDesc(D3DINDEXBUFFER_DESC* pDesc) {
    return native_->GetDesc(pDesc);
}
HRESULT WINAPI VertexDeclaration::QueryInterface(REFIID riid, void** ppvObject) {
    return query(this, riid, ppvObject);
}
ULONG WINAPI VertexDeclaration::AddRef() {
    return add_ref(this);
}
ULONG WINAPI VertexDeclaration::Release() {
    return release(this);
}
HRESULT WINAPI VertexDeclaration::GetDevice(IDirect3DDevice9** ppDevice) {
    return get_device(this, ppDevice);
}
HRESULT WINAPI VertexDeclaration::GetDeclaration(D3DVERTEXELEMENT9* arg0, UINT* pNumElements) {
    return native_->GetDeclaration(arg0, pNumElements);
}
HRESULT WINAPI VertexShader::QueryInterface(REFIID riid, void** ppvObject) {
    return query(this, riid, ppvObject);
}
ULONG WINAPI VertexShader::AddRef() {
    return add_ref(this);
}
ULONG WINAPI VertexShader::Release() {
    return release(this);
}
HRESULT WINAPI VertexShader::GetDevice(IDirect3DDevice9** ppDevice) {
    return get_device(this, ppDevice);
}
HRESULT WINAPI VertexShader::GetFunction(void* arg0, UINT* pSizeOfData) {
    return native_->GetFunction(arg0, pSizeOfData);
}
HRESULT WINAPI PixelShader::QueryInterface(REFIID riid, void** ppvObject) {
    return query(this, riid, ppvObject);
}
ULONG WINAPI PixelShader::AddRef() {
    return add_ref(this);
}
ULONG WINAPI PixelShader::Release() {
    return release(this);
}
HRESULT WINAPI PixelShader::GetDevice(IDirect3DDevice9** ppDevice) {
    return get_device(this, ppDevice);
}
HRESULT WINAPI PixelShader::GetFunction(void* arg0, UINT* pSizeOfData) {
    return native_->GetFunction(arg0, pSizeOfData);
}
HRESULT WINAPI StateBlock::QueryInterface(REFIID riid, void** ppvObject) {
    return query(this, riid, ppvObject);
}
ULONG WINAPI StateBlock::AddRef() {
    return add_ref(this);
}
ULONG WINAPI StateBlock::Release() {
    return release(this);
}
HRESULT WINAPI StateBlock::GetDevice(IDirect3DDevice9** ppDevice) {
    return get_device(this, ppDevice);
}
HRESULT WINAPI StateBlock::Capture() {
    return native_->Capture();
}
HRESULT WINAPI StateBlock::Apply() {
    return native_->Apply();
}
HRESULT WINAPI Query::QueryInterface(REFIID riid, void** ppvObject) {
    return query(this, riid, ppvObject);
}
ULONG WINAPI Query::AddRef() {
    return add_ref(this);
}
ULONG WINAPI Query::Release() {
    return release(this);
}
HRESULT WINAPI Query::GetDevice(IDirect3DDevice9** ppDevice) {
    return get_device(this, ppDevice);
}
D3DQUERYTYPE WINAPI Query::GetType() {
    return native_->GetType();
}
DWORD WINAPI Query::GetDataSize() {
    return native_->GetDataSize();
}
HRESULT WINAPI Query::Issue(DWORD dwIssueFlags) {
    return native_->Issue(dwIssueFlags);
}
HRESULT WINAPI Query::GetData(void* pData, DWORD dwSize, DWORD dwGetDataFlags) {
    return native_->GetData(pData, dwSize, dwGetDataFlags);
}
HRESULT WINAPI SwapChain::QueryInterface(REFIID riid, void ** ppvObject) {
    return query(this, riid, ppvObject);
}
ULONG WINAPI SwapChain::AddRef() {
    return add_ref(this);
}
ULONG WINAPI SwapChain::Release() {
    return release(this);
}
HRESULT WINAPI SwapChain::Present(const RECT * src_rect, const RECT * dst_rect, HWND dst_window_override, const RGNDATA * dirty_region, DWORD flags) {
    return observe_result(device_of(this), native_->Present(src_rect, dst_rect, dst_window_override, dirty_region, flags));
}
HRESULT WINAPI SwapChain::GetFrontBufferData(IDirect3DSurface9 * pDestSurface) {
    return native_->GetFrontBufferData(unwrap_physical_surface(device_of(this), pDestSurface));
}
HRESULT WINAPI SwapChain::GetBackBuffer(UINT iBackBuffer, D3DBACKBUFFER_TYPE Type, IDirect3DSurface9 ** ppBackBuffer) {
    IDirect3DSurface9* owned = untouched_output<IDirect3DSurface9>();
    const HRESULT hr = native_->GetBackBuffer(iBackBuffer, Type, ppBackBuffer ? &owned : nullptr);
    return output(device_of(this), hr, owned, ppBackBuffer);
}
HRESULT WINAPI SwapChain::GetRasterStatus(D3DRASTER_STATUS * pRasterStatus) {
    return native_->GetRasterStatus(pRasterStatus);
}
HRESULT WINAPI SwapChain::GetDisplayMode(D3DDISPLAYMODE * pMode) {
    return native_->GetDisplayMode(pMode);
}
HRESULT WINAPI SwapChain::GetDevice(IDirect3DDevice9 ** ppDevice) {
    return get_device(this, ppDevice);
}
HRESULT WINAPI SwapChain::GetPresentParameters(D3DPRESENT_PARAMETERS * pPresentationParameters) {
    return native_->GetPresentParameters(pPresentationParameters);
}
