// Generated by tools/ownership/generate_d3d9_forwarders.py from MinGW d3d9.h.
// Edit the generator or handwritten ownership rules, not this file.
struct Factory final : IDirect3D9, Node {
    IDirect3D9* native_;
    Options options;
    Factory(IDirect3D9* native, Node* owner)
        : Node(Kind::Factory, native, owner), native_(native) { application = static_cast<IDirect3D9*>(this); }
    HRESULT WINAPI QueryInterface(REFIID riid, void** ppvObject) override;
    ULONG WINAPI AddRef() override;
    ULONG WINAPI Release() override;
    HRESULT WINAPI RegisterSoftwareDevice(void* pInitializeFunction) override;
    UINT WINAPI GetAdapterCount() override;
    HRESULT WINAPI GetAdapterIdentifier(UINT Adapter, DWORD Flags, D3DADAPTER_IDENTIFIER9* pIdentifier) override;
    UINT WINAPI GetAdapterModeCount(UINT Adapter, D3DFORMAT Format) override;
    HRESULT WINAPI EnumAdapterModes(UINT Adapter, D3DFORMAT Format, UINT Mode, D3DDISPLAYMODE* pMode) override;
    HRESULT WINAPI GetAdapterDisplayMode(UINT Adapter, D3DDISPLAYMODE* pMode) override;
    HRESULT WINAPI CheckDeviceType(UINT iAdapter, D3DDEVTYPE DevType, D3DFORMAT DisplayFormat, D3DFORMAT BackBufferFormat, WINBOOL bWindowed) override;
    HRESULT WINAPI CheckDeviceFormat(UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, DWORD Usage, D3DRESOURCETYPE RType, D3DFORMAT CheckFormat) override;
    HRESULT WINAPI CheckDeviceMultiSampleType(UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT SurfaceFormat, WINBOOL Windowed, D3DMULTISAMPLE_TYPE MultiSampleType, DWORD* pQualityLevels) override;
    HRESULT WINAPI CheckDepthStencilMatch(UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, D3DFORMAT RenderTargetFormat, D3DFORMAT DepthStencilFormat) override;
    HRESULT WINAPI CheckDeviceFormatConversion(UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT SourceFormat, D3DFORMAT TargetFormat) override;
    HRESULT WINAPI GetDeviceCaps(UINT Adapter, D3DDEVTYPE DeviceType, D3DCAPS9* pCaps) override;
    HMONITOR WINAPI GetAdapterMonitor(UINT Adapter) override;
    HRESULT WINAPI CreateDevice(UINT Adapter, D3DDEVTYPE DeviceType, HWND hFocusWindow, DWORD BehaviorFlags, D3DPRESENT_PARAMETERS* pPresentationParameters, IDirect3DDevice9** ppReturnedDeviceInterface) override;
};
struct Device final : IDirect3DDevice9, Node {
    IDirect3DDevice9* native_;
    Options options;
    std::vector<IUnknown*> renderer_resources;
    bool retiring = false, resetting = false, lost = false;
    CopyDepth copy_depth;
    ObservedExecutionState execution;
    std::atomic<bool> recording_state_block{false};
    HRESULT buffer_tracking_status = S_OK;
    std::shared_ptr<FiniteOwner> finite_owner;
    HRESULT finite_status = S_FALSE;
    Device(IDirect3DDevice9* native, Node* owner)
        : Node(Kind::Device, native, owner), native_(native) { application = static_cast<IDirect3DDevice9*>(this); }
    HRESULT WINAPI QueryInterface(REFIID riid, void** ppvObject) override;
    ULONG WINAPI AddRef() override;
    ULONG WINAPI Release() override;
    HRESULT WINAPI TestCooperativeLevel() override;
    UINT WINAPI GetAvailableTextureMem() override;
    HRESULT WINAPI EvictManagedResources() override;
    HRESULT WINAPI GetDirect3D(IDirect3D9** ppD3D9) override;
    HRESULT WINAPI GetDeviceCaps(D3DCAPS9* pCaps) override;
    HRESULT WINAPI GetDisplayMode(UINT iSwapChain, D3DDISPLAYMODE* pMode) override;
    HRESULT WINAPI GetCreationParameters(D3DDEVICE_CREATION_PARAMETERS * pParameters) override;
    HRESULT WINAPI SetCursorProperties(UINT XHotSpot, UINT YHotSpot, IDirect3DSurface9* pCursorBitmap) override;
    void WINAPI SetCursorPosition(int X, int Y, DWORD Flags) override;
    WINBOOL WINAPI ShowCursor(WINBOOL bShow) override;
    HRESULT WINAPI CreateAdditionalSwapChain(D3DPRESENT_PARAMETERS* pPresentationParameters, IDirect3DSwapChain9** pSwapChain) override;
    HRESULT WINAPI GetSwapChain(UINT iSwapChain, IDirect3DSwapChain9** pSwapChain) override;
    UINT WINAPI GetNumberOfSwapChains() override;
    HRESULT WINAPI Reset(D3DPRESENT_PARAMETERS* pPresentationParameters) override;
    HRESULT WINAPI Present(const RECT * src_rect, const RECT * dst_rect, HWND dst_window_override, const RGNDATA * dirty_region) override;
    HRESULT WINAPI GetBackBuffer(UINT iSwapChain, UINT iBackBuffer, D3DBACKBUFFER_TYPE Type, IDirect3DSurface9** ppBackBuffer) override;
    HRESULT WINAPI GetRasterStatus(UINT iSwapChain, D3DRASTER_STATUS* pRasterStatus) override;
    HRESULT WINAPI SetDialogBoxMode(WINBOOL bEnableDialogs) override;
    void WINAPI SetGammaRamp(UINT swapchain_idx, DWORD flags, const D3DGAMMARAMP * ramp) override;
    void WINAPI GetGammaRamp(UINT iSwapChain, D3DGAMMARAMP* pRamp) override;
    HRESULT WINAPI CreateTexture(UINT Width, UINT Height, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DTexture9** ppTexture, HANDLE* pSharedHandle) override;
    HRESULT WINAPI CreateVolumeTexture(UINT Width, UINT Height, UINT Depth, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DVolumeTexture9** ppVolumeTexture, HANDLE* pSharedHandle) override;
    HRESULT WINAPI CreateCubeTexture(UINT EdgeLength, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DCubeTexture9** ppCubeTexture, HANDLE* pSharedHandle) override;
    HRESULT WINAPI CreateVertexBuffer(UINT Length, DWORD Usage, DWORD FVF, D3DPOOL Pool, IDirect3DVertexBuffer9** ppVertexBuffer, HANDLE* pSharedHandle) override;
    HRESULT WINAPI CreateIndexBuffer(UINT Length, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DIndexBuffer9** ppIndexBuffer, HANDLE* pSharedHandle) override;
    HRESULT WINAPI CreateRenderTarget(UINT Width, UINT Height, D3DFORMAT Format, D3DMULTISAMPLE_TYPE MultiSample, DWORD MultisampleQuality, WINBOOL Lockable, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle) override;
    HRESULT WINAPI CreateDepthStencilSurface(UINT Width, UINT Height, D3DFORMAT Format, D3DMULTISAMPLE_TYPE MultiSample, DWORD MultisampleQuality, WINBOOL Discard, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle) override;
    HRESULT WINAPI UpdateSurface(IDirect3DSurface9 * src_surface, const RECT * src_rect, IDirect3DSurface9 * dst_surface, const POINT * dst_point) override;
    HRESULT WINAPI UpdateTexture(IDirect3DBaseTexture9* pSourceTexture, IDirect3DBaseTexture9* pDestinationTexture) override;
    HRESULT WINAPI GetRenderTargetData(IDirect3DSurface9* pRenderTarget, IDirect3DSurface9* pDestSurface) override;
    HRESULT WINAPI GetFrontBufferData(UINT iSwapChain, IDirect3DSurface9* pDestSurface) override;
    HRESULT WINAPI StretchRect(IDirect3DSurface9 * src_surface, const RECT * src_rect, IDirect3DSurface9 * dst_surface, const RECT * dst_rect, D3DTEXTUREFILTERTYPE filter) override;
    HRESULT WINAPI ColorFill(IDirect3DSurface9 * surface, const RECT * rect, D3DCOLOR color) override;
    HRESULT WINAPI CreateOffscreenPlainSurface(UINT Width, UINT Height, D3DFORMAT Format, D3DPOOL Pool, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle) override;
    HRESULT WINAPI SetRenderTarget(DWORD RenderTargetIndex, IDirect3DSurface9* pRenderTarget) override;
    HRESULT WINAPI GetRenderTarget(DWORD RenderTargetIndex, IDirect3DSurface9** ppRenderTarget) override;
    HRESULT WINAPI SetDepthStencilSurface(IDirect3DSurface9* pNewZStencil) override;
    HRESULT WINAPI GetDepthStencilSurface(IDirect3DSurface9** ppZStencilSurface) override;
    HRESULT WINAPI BeginScene() override;
    HRESULT WINAPI EndScene() override;
    HRESULT WINAPI Clear(DWORD rect_count, const D3DRECT * rects, DWORD flags, D3DCOLOR color, float z, DWORD stencil) override;
    HRESULT WINAPI SetTransform(D3DTRANSFORMSTATETYPE state, const D3DMATRIX * matrix) override;
    HRESULT WINAPI GetTransform(D3DTRANSFORMSTATETYPE State, D3DMATRIX* pMatrix) override;
    HRESULT WINAPI MultiplyTransform(D3DTRANSFORMSTATETYPE state, const D3DMATRIX * matrix) override;
    HRESULT WINAPI SetViewport(const D3DVIEWPORT9 * viewport) override;
    HRESULT WINAPI GetViewport(D3DVIEWPORT9* pViewport) override;
    HRESULT WINAPI SetMaterial(const D3DMATERIAL9 * material) override;
    HRESULT WINAPI GetMaterial(D3DMATERIAL9* pMaterial) override;
    HRESULT WINAPI SetLight(DWORD index, const D3DLIGHT9 * light) override;
    HRESULT WINAPI GetLight(DWORD Index, D3DLIGHT9* arg1) override;
    HRESULT WINAPI LightEnable(DWORD Index, WINBOOL Enable) override;
    HRESULT WINAPI GetLightEnable(DWORD Index, WINBOOL* pEnable) override;
    HRESULT WINAPI SetClipPlane(DWORD index, const float * plane) override;
    HRESULT WINAPI GetClipPlane(DWORD Index, float* pPlane) override;
    HRESULT WINAPI SetRenderState(D3DRENDERSTATETYPE State, DWORD Value) override;
    HRESULT WINAPI GetRenderState(D3DRENDERSTATETYPE State, DWORD* pValue) override;
    HRESULT WINAPI CreateStateBlock(D3DSTATEBLOCKTYPE Type, IDirect3DStateBlock9** ppSB) override;
    HRESULT WINAPI BeginStateBlock() override;
    HRESULT WINAPI EndStateBlock(IDirect3DStateBlock9** ppSB) override;
    HRESULT WINAPI SetClipStatus(const D3DCLIPSTATUS9 * clip_status) override;
    HRESULT WINAPI GetClipStatus(D3DCLIPSTATUS9* pClipStatus) override;
    HRESULT WINAPI GetTexture(DWORD Stage, IDirect3DBaseTexture9** ppTexture) override;
    HRESULT WINAPI SetTexture(DWORD Stage, IDirect3DBaseTexture9* pTexture) override;
    HRESULT WINAPI GetTextureStageState(DWORD Stage, D3DTEXTURESTAGESTATETYPE Type, DWORD* pValue) override;
    HRESULT WINAPI SetTextureStageState(DWORD Stage, D3DTEXTURESTAGESTATETYPE Type, DWORD Value) override;
    HRESULT WINAPI GetSamplerState(DWORD Sampler, D3DSAMPLERSTATETYPE Type, DWORD* pValue) override;
    HRESULT WINAPI SetSamplerState(DWORD Sampler, D3DSAMPLERSTATETYPE Type, DWORD Value) override;
    HRESULT WINAPI ValidateDevice(DWORD* pNumPasses) override;
    HRESULT WINAPI SetPaletteEntries(UINT palette_idx, const PALETTEENTRY * entries) override;
    HRESULT WINAPI GetPaletteEntries(UINT PaletteNumber, PALETTEENTRY* pEntries) override;
    HRESULT WINAPI SetCurrentTexturePalette(UINT PaletteNumber) override;
    HRESULT WINAPI GetCurrentTexturePalette(UINT * PaletteNumber) override;
    HRESULT WINAPI SetScissorRect(const RECT * rect) override;
    HRESULT WINAPI GetScissorRect(RECT* pRect) override;
    HRESULT WINAPI SetSoftwareVertexProcessing(WINBOOL bSoftware) override;
    WINBOOL WINAPI GetSoftwareVertexProcessing() override;
    HRESULT WINAPI SetNPatchMode(float nSegments) override;
    float WINAPI GetNPatchMode() override;
    HRESULT WINAPI DrawPrimitive(D3DPRIMITIVETYPE PrimitiveType, UINT StartVertex, UINT PrimitiveCount) override;
    HRESULT WINAPI DrawIndexedPrimitive(D3DPRIMITIVETYPE arg0, INT BaseVertexIndex, UINT MinVertexIndex, UINT NumVertices, UINT startIndex, UINT primCount) override;
    HRESULT WINAPI DrawPrimitiveUP(D3DPRIMITIVETYPE primitive_type, UINT primitive_count, const void * data, UINT stride) override;
    HRESULT WINAPI DrawIndexedPrimitiveUP(D3DPRIMITIVETYPE primitive_type, UINT min_vertex_idx, UINT vertex_count, UINT primitive_count, const void * index_data, D3DFORMAT index_format, const void * data, UINT stride) override;
    HRESULT WINAPI ProcessVertices(UINT SrcStartIndex, UINT DestIndex, UINT VertexCount, IDirect3DVertexBuffer9* pDestBuffer, IDirect3DVertexDeclaration9* pVertexDecl, DWORD Flags) override;
    HRESULT WINAPI CreateVertexDeclaration(const D3DVERTEXELEMENT9 * elements, IDirect3DVertexDeclaration9 ** declaration) override;
    HRESULT WINAPI SetVertexDeclaration(IDirect3DVertexDeclaration9* pDecl) override;
    HRESULT WINAPI GetVertexDeclaration(IDirect3DVertexDeclaration9** ppDecl) override;
    HRESULT WINAPI SetFVF(DWORD FVF) override;
    HRESULT WINAPI GetFVF(DWORD* pFVF) override;
    HRESULT WINAPI CreateVertexShader(const DWORD * byte_code, IDirect3DVertexShader9 ** shader) override;
    HRESULT WINAPI SetVertexShader(IDirect3DVertexShader9* pShader) override;
    HRESULT WINAPI GetVertexShader(IDirect3DVertexShader9** ppShader) override;
    HRESULT WINAPI SetVertexShaderConstantF(UINT reg_idx, const float * data, UINT count) override;
    HRESULT WINAPI GetVertexShaderConstantF(UINT StartRegister, float* pConstantData, UINT Vector4fCount) override;
    HRESULT WINAPI SetVertexShaderConstantI(UINT reg_idx, const int * data, UINT count) override;
    HRESULT WINAPI GetVertexShaderConstantI(UINT StartRegister, int* pConstantData, UINT Vector4iCount) override;
    HRESULT WINAPI SetVertexShaderConstantB(UINT reg_idx, const WINBOOL * data, UINT count) override;
    HRESULT WINAPI GetVertexShaderConstantB(UINT StartRegister, WINBOOL* pConstantData, UINT BoolCount) override;
    HRESULT WINAPI SetStreamSource(UINT StreamNumber, IDirect3DVertexBuffer9* pStreamData, UINT OffsetInBytes, UINT Stride) override;
    HRESULT WINAPI GetStreamSource(UINT StreamNumber, IDirect3DVertexBuffer9** ppStreamData, UINT* OffsetInBytes, UINT* pStride) override;
    HRESULT WINAPI SetStreamSourceFreq(UINT StreamNumber, UINT Divider) override;
    HRESULT WINAPI GetStreamSourceFreq(UINT StreamNumber, UINT* Divider) override;
    HRESULT WINAPI SetIndices(IDirect3DIndexBuffer9* pIndexData) override;
    HRESULT WINAPI GetIndices(IDirect3DIndexBuffer9** ppIndexData) override;
    HRESULT WINAPI CreatePixelShader(const DWORD * byte_code, IDirect3DPixelShader9 ** shader) override;
    HRESULT WINAPI SetPixelShader(IDirect3DPixelShader9* pShader) override;
    HRESULT WINAPI GetPixelShader(IDirect3DPixelShader9** ppShader) override;
    HRESULT WINAPI SetPixelShaderConstantF(UINT reg_idx, const float * data, UINT count) override;
    HRESULT WINAPI GetPixelShaderConstantF(UINT StartRegister, float* pConstantData, UINT Vector4fCount) override;
    HRESULT WINAPI SetPixelShaderConstantI(UINT reg_idx, const int * data, UINT count) override;
    HRESULT WINAPI GetPixelShaderConstantI(UINT StartRegister, int* pConstantData, UINT Vector4iCount) override;
    HRESULT WINAPI SetPixelShaderConstantB(UINT reg_idx, const WINBOOL * data, UINT count) override;
    HRESULT WINAPI GetPixelShaderConstantB(UINT StartRegister, WINBOOL* pConstantData, UINT BoolCount) override;
    HRESULT WINAPI DrawRectPatch(UINT handle, const float * segment_count, const D3DRECTPATCH_INFO * patch_info) override;
    HRESULT WINAPI DrawTriPatch(UINT handle, const float * segment_count, const D3DTRIPATCH_INFO * patch_info) override;
    HRESULT WINAPI DeletePatch(UINT Handle) override;
    HRESULT WINAPI CreateQuery(D3DQUERYTYPE Type, IDirect3DQuery9** ppQuery) override;
};
struct Texture final : IDirect3DTexture9, Node {
    IDirect3DTexture9* native_;
    Texture(IDirect3DTexture9* native, Node* owner)
        : Node(Kind::Texture, native, owner), native_(native) { application = static_cast<IDirect3DTexture9*>(this); }
    HRESULT WINAPI QueryInterface(REFIID riid, void** ppvObject) override;
    ULONG WINAPI AddRef() override;
    ULONG WINAPI Release() override;
    HRESULT WINAPI GetDevice(IDirect3DDevice9** ppDevice) override;
    HRESULT WINAPI SetPrivateData(REFGUID guid, const void * data, DWORD data_size, DWORD flags) override;
    HRESULT WINAPI GetPrivateData(REFGUID refguid, void* pData, DWORD* pSizeOfData) override;
    HRESULT WINAPI FreePrivateData(REFGUID refguid) override;
    DWORD WINAPI SetPriority(DWORD PriorityNew) override;
    DWORD WINAPI GetPriority() override;
    void WINAPI PreLoad() override;
    D3DRESOURCETYPE WINAPI GetType() override;
    DWORD WINAPI SetLOD(DWORD LODNew) override;
    DWORD WINAPI GetLOD() override;
    DWORD WINAPI GetLevelCount() override;
    HRESULT WINAPI SetAutoGenFilterType(D3DTEXTUREFILTERTYPE FilterType) override;
    D3DTEXTUREFILTERTYPE WINAPI GetAutoGenFilterType() override;
    void WINAPI GenerateMipSubLevels() override;
    HRESULT WINAPI GetLevelDesc(UINT Level, D3DSURFACE_DESC* pDesc) override;
    HRESULT WINAPI GetSurfaceLevel(UINT Level, IDirect3DSurface9** ppSurfaceLevel) override;
    HRESULT WINAPI LockRect(UINT level, D3DLOCKED_RECT * locked_rect, const RECT * rect, DWORD flags) override;
    HRESULT WINAPI UnlockRect(UINT Level) override;
    HRESULT WINAPI AddDirtyRect(const RECT * dirty_rect) override;
};
struct CubeTexture final : IDirect3DCubeTexture9, Node {
    IDirect3DCubeTexture9* native_;
    CubeTexture(IDirect3DCubeTexture9* native, Node* owner)
        : Node(Kind::CubeTexture, native, owner), native_(native) { application = static_cast<IDirect3DCubeTexture9*>(this); }
    HRESULT WINAPI QueryInterface(REFIID riid, void** ppvObject) override;
    ULONG WINAPI AddRef() override;
    ULONG WINAPI Release() override;
    HRESULT WINAPI GetDevice(IDirect3DDevice9** ppDevice) override;
    HRESULT WINAPI SetPrivateData(REFGUID guid, const void * data, DWORD data_size, DWORD flags) override;
    HRESULT WINAPI GetPrivateData(REFGUID refguid, void* pData, DWORD* pSizeOfData) override;
    HRESULT WINAPI FreePrivateData(REFGUID refguid) override;
    DWORD WINAPI SetPriority(DWORD PriorityNew) override;
    DWORD WINAPI GetPriority() override;
    void WINAPI PreLoad() override;
    D3DRESOURCETYPE WINAPI GetType() override;
    DWORD WINAPI SetLOD(DWORD LODNew) override;
    DWORD WINAPI GetLOD() override;
    DWORD WINAPI GetLevelCount() override;
    HRESULT WINAPI SetAutoGenFilterType(D3DTEXTUREFILTERTYPE FilterType) override;
    D3DTEXTUREFILTERTYPE WINAPI GetAutoGenFilterType() override;
    void WINAPI GenerateMipSubLevels() override;
    HRESULT WINAPI GetLevelDesc(UINT Level, D3DSURFACE_DESC* pDesc) override;
    HRESULT WINAPI GetCubeMapSurface(D3DCUBEMAP_FACES FaceType, UINT Level, IDirect3DSurface9** ppCubeMapSurface) override;
    HRESULT WINAPI LockRect(D3DCUBEMAP_FACES face, UINT level, D3DLOCKED_RECT * locked_rect, const RECT * rect, DWORD flags) override;
    HRESULT WINAPI UnlockRect(D3DCUBEMAP_FACES FaceType, UINT Level) override;
    HRESULT WINAPI AddDirtyRect(D3DCUBEMAP_FACES face, const RECT * dirty_rect) override;
};
struct VolumeTexture final : IDirect3DVolumeTexture9, Node {
    IDirect3DVolumeTexture9* native_;
    VolumeTexture(IDirect3DVolumeTexture9* native, Node* owner)
        : Node(Kind::VolumeTexture, native, owner), native_(native) { application = static_cast<IDirect3DVolumeTexture9*>(this); }
    HRESULT WINAPI QueryInterface(REFIID riid, void** ppvObject) override;
    ULONG WINAPI AddRef() override;
    ULONG WINAPI Release() override;
    HRESULT WINAPI GetDevice(IDirect3DDevice9** ppDevice) override;
    HRESULT WINAPI SetPrivateData(REFGUID guid, const void * data, DWORD data_size, DWORD flags) override;
    HRESULT WINAPI GetPrivateData(REFGUID refguid, void* pData, DWORD* pSizeOfData) override;
    HRESULT WINAPI FreePrivateData(REFGUID refguid) override;
    DWORD WINAPI SetPriority(DWORD PriorityNew) override;
    DWORD WINAPI GetPriority() override;
    void WINAPI PreLoad() override;
    D3DRESOURCETYPE WINAPI GetType() override;
    DWORD WINAPI SetLOD(DWORD LODNew) override;
    DWORD WINAPI GetLOD() override;
    DWORD WINAPI GetLevelCount() override;
    HRESULT WINAPI SetAutoGenFilterType(D3DTEXTUREFILTERTYPE FilterType) override;
    D3DTEXTUREFILTERTYPE WINAPI GetAutoGenFilterType() override;
    void WINAPI GenerateMipSubLevels() override;
    HRESULT WINAPI GetLevelDesc(UINT Level, D3DVOLUME_DESC * pDesc) override;
    HRESULT WINAPI GetVolumeLevel(UINT Level, IDirect3DVolume9** ppVolumeLevel) override;
    HRESULT WINAPI LockBox(UINT level, D3DLOCKED_BOX * locked_box, const D3DBOX * box, DWORD flags) override;
    HRESULT WINAPI UnlockBox(UINT Level) override;
    HRESULT WINAPI AddDirtyBox(const D3DBOX * dirty_box) override;
};
struct Surface final : IDirect3DSurface9, Node {
    IDirect3DSurface9* native_;
    Surface(IDirect3DSurface9* native, Node* owner)
        : Node(Kind::Surface, native, owner), native_(native) { application = static_cast<IDirect3DSurface9*>(this); }
    HRESULT WINAPI QueryInterface(REFIID riid, void** ppvObject) override;
    ULONG WINAPI AddRef() override;
    ULONG WINAPI Release() override;
    HRESULT WINAPI GetDevice(IDirect3DDevice9** ppDevice) override;
    HRESULT WINAPI SetPrivateData(REFGUID guid, const void * data, DWORD data_size, DWORD flags) override;
    HRESULT WINAPI GetPrivateData(REFGUID refguid, void* pData, DWORD* pSizeOfData) override;
    HRESULT WINAPI FreePrivateData(REFGUID refguid) override;
    DWORD WINAPI SetPriority(DWORD PriorityNew) override;
    DWORD WINAPI GetPriority() override;
    void WINAPI PreLoad() override;
    D3DRESOURCETYPE WINAPI GetType() override;
    HRESULT WINAPI GetContainer(REFIID riid, void** ppContainer) override;
    HRESULT WINAPI GetDesc(D3DSURFACE_DESC* pDesc) override;
    HRESULT WINAPI LockRect(D3DLOCKED_RECT * locked_rect, const RECT * rect, DWORD flags) override;
    HRESULT WINAPI UnlockRect() override;
    HRESULT WINAPI GetDC(HDC* phdc) override;
    HRESULT WINAPI ReleaseDC(HDC hdc) override;
};
struct Volume final : IDirect3DVolume9, Node {
    IDirect3DVolume9* native_;
    Volume(IDirect3DVolume9* native, Node* owner)
        : Node(Kind::Volume, native, owner), native_(native) { application = static_cast<IDirect3DVolume9*>(this); }
    HRESULT WINAPI QueryInterface(REFIID riid, void** ppvObject) override;
    ULONG WINAPI AddRef() override;
    ULONG WINAPI Release() override;
    HRESULT WINAPI GetDevice(IDirect3DDevice9** ppDevice) override;
    HRESULT WINAPI SetPrivateData(REFGUID guid, const void * data, DWORD data_size, DWORD flags) override;
    HRESULT WINAPI GetPrivateData(REFGUID refguid, void* pData, DWORD* pSizeOfData) override;
    HRESULT WINAPI FreePrivateData(REFGUID refguid) override;
    HRESULT WINAPI GetContainer(REFIID riid, void** ppContainer) override;
    HRESULT WINAPI GetDesc(D3DVOLUME_DESC* pDesc) override;
    HRESULT WINAPI LockBox(D3DLOCKED_BOX * locked_box, const D3DBOX * box, DWORD flags) override;
    HRESULT WINAPI UnlockBox() override;
};
struct VertexBuffer final : IDirect3DVertexBuffer9, Node {
    IDirect3DVertexBuffer9* native_;
    VertexBuffer(IDirect3DVertexBuffer9* native, Node* owner)
        : Node(Kind::VertexBuffer, native, owner), native_(native) { application = static_cast<IDirect3DVertexBuffer9*>(this); }
    HRESULT WINAPI QueryInterface(REFIID riid, void** ppvObject) override;
    ULONG WINAPI AddRef() override;
    ULONG WINAPI Release() override;
    HRESULT WINAPI GetDevice(IDirect3DDevice9** ppDevice) override;
    HRESULT WINAPI SetPrivateData(REFGUID guid, const void * data, DWORD data_size, DWORD flags) override;
    HRESULT WINAPI GetPrivateData(REFGUID refguid, void* pData, DWORD* pSizeOfData) override;
    HRESULT WINAPI FreePrivateData(REFGUID refguid) override;
    DWORD WINAPI SetPriority(DWORD PriorityNew) override;
    DWORD WINAPI GetPriority() override;
    void WINAPI PreLoad() override;
    D3DRESOURCETYPE WINAPI GetType() override;
    HRESULT WINAPI Lock(UINT OffsetToLock, UINT SizeToLock, void** ppbData, DWORD Flags) override;
    HRESULT WINAPI Unlock() override;
    HRESULT WINAPI GetDesc(D3DVERTEXBUFFER_DESC* pDesc) override;
};
struct IndexBuffer final : IDirect3DIndexBuffer9, Node {
    IDirect3DIndexBuffer9* native_;
    IndexBuffer(IDirect3DIndexBuffer9* native, Node* owner)
        : Node(Kind::IndexBuffer, native, owner), native_(native) { application = static_cast<IDirect3DIndexBuffer9*>(this); }
    HRESULT WINAPI QueryInterface(REFIID riid, void** ppvObject) override;
    ULONG WINAPI AddRef() override;
    ULONG WINAPI Release() override;
    HRESULT WINAPI GetDevice(IDirect3DDevice9** ppDevice) override;
    HRESULT WINAPI SetPrivateData(REFGUID guid, const void * data, DWORD data_size, DWORD flags) override;
    HRESULT WINAPI GetPrivateData(REFGUID refguid, void* pData, DWORD* pSizeOfData) override;
    HRESULT WINAPI FreePrivateData(REFGUID refguid) override;
    DWORD WINAPI SetPriority(DWORD PriorityNew) override;
    DWORD WINAPI GetPriority() override;
    void WINAPI PreLoad() override;
    D3DRESOURCETYPE WINAPI GetType() override;
    HRESULT WINAPI Lock(UINT OffsetToLock, UINT SizeToLock, void** ppbData, DWORD Flags) override;
    HRESULT WINAPI Unlock() override;
    HRESULT WINAPI GetDesc(D3DINDEXBUFFER_DESC* pDesc) override;
};
struct VertexDeclaration final : IDirect3DVertexDeclaration9, Node {
    IDirect3DVertexDeclaration9* native_;
    VertexDeclaration(IDirect3DVertexDeclaration9* native, Node* owner)
        : Node(Kind::VertexDeclaration, native, owner), native_(native) { application = static_cast<IDirect3DVertexDeclaration9*>(this); }
    HRESULT WINAPI QueryInterface(REFIID riid, void** ppvObject) override;
    ULONG WINAPI AddRef() override;
    ULONG WINAPI Release() override;
    HRESULT WINAPI GetDevice(IDirect3DDevice9** ppDevice) override;
    HRESULT WINAPI GetDeclaration(D3DVERTEXELEMENT9* arg0, UINT* pNumElements) override;
};
struct VertexShader final : IDirect3DVertexShader9, Node {
    IDirect3DVertexShader9* native_;
    VertexShader(IDirect3DVertexShader9* native, Node* owner)
        : Node(Kind::VertexShader, native, owner), native_(native) { application = static_cast<IDirect3DVertexShader9*>(this); }
    HRESULT WINAPI QueryInterface(REFIID riid, void** ppvObject) override;
    ULONG WINAPI AddRef() override;
    ULONG WINAPI Release() override;
    HRESULT WINAPI GetDevice(IDirect3DDevice9** ppDevice) override;
    HRESULT WINAPI GetFunction(void* arg0, UINT* pSizeOfData) override;
};
struct PixelShader final : IDirect3DPixelShader9, Node {
    IDirect3DPixelShader9* native_;
    PixelShader(IDirect3DPixelShader9* native, Node* owner)
        : Node(Kind::PixelShader, native, owner), native_(native) { application = static_cast<IDirect3DPixelShader9*>(this); }
    HRESULT WINAPI QueryInterface(REFIID riid, void** ppvObject) override;
    ULONG WINAPI AddRef() override;
    ULONG WINAPI Release() override;
    HRESULT WINAPI GetDevice(IDirect3DDevice9** ppDevice) override;
    HRESULT WINAPI GetFunction(void* arg0, UINT* pSizeOfData) override;
};
struct StateBlock final : IDirect3DStateBlock9, Node {
    IDirect3DStateBlock9* native_;
    StateBlock(IDirect3DStateBlock9* native, Node* owner)
        : Node(Kind::StateBlock, native, owner), native_(native) { application = static_cast<IDirect3DStateBlock9*>(this); }
    HRESULT WINAPI QueryInterface(REFIID riid, void** ppvObject) override;
    ULONG WINAPI AddRef() override;
    ULONG WINAPI Release() override;
    HRESULT WINAPI GetDevice(IDirect3DDevice9** ppDevice) override;
    HRESULT WINAPI Capture() override;
    HRESULT WINAPI Apply() override;
};
struct Query final : IDirect3DQuery9, Node {
    IDirect3DQuery9* native_;
    ExecutionQuery execution_query;
    Query(IDirect3DQuery9* native, Node* owner)
        : Node(Kind::Query, native, owner), native_(native) { application = static_cast<IDirect3DQuery9*>(this); }
    HRESULT WINAPI QueryInterface(REFIID riid, void** ppvObject) override;
    ULONG WINAPI AddRef() override;
    ULONG WINAPI Release() override;
    HRESULT WINAPI GetDevice(IDirect3DDevice9** ppDevice) override;
    D3DQUERYTYPE WINAPI GetType() override;
    DWORD WINAPI GetDataSize() override;
    HRESULT WINAPI Issue(DWORD dwIssueFlags) override;
    HRESULT WINAPI GetData(void* pData, DWORD dwSize, DWORD dwGetDataFlags) override;
};
struct SwapChain final : IDirect3DSwapChain9, Node {
    IDirect3DSwapChain9* native_;
    SwapChain(IDirect3DSwapChain9* native, Node* owner)
        : Node(Kind::SwapChain, native, owner), native_(native) { application = static_cast<IDirect3DSwapChain9*>(this); }
    HRESULT WINAPI QueryInterface(REFIID riid, void ** ppvObject) override;
    ULONG WINAPI AddRef() override;
    ULONG WINAPI Release() override;
    HRESULT WINAPI Present(const RECT * src_rect, const RECT * dst_rect, HWND dst_window_override, const RGNDATA * dirty_region, DWORD flags) override;
    HRESULT WINAPI GetFrontBufferData(IDirect3DSurface9 * pDestSurface) override;
    HRESULT WINAPI GetBackBuffer(UINT iBackBuffer, D3DBACKBUFFER_TYPE Type, IDirect3DSurface9 ** ppBackBuffer) override;
    HRESULT WINAPI GetRasterStatus(D3DRASTER_STATUS * pRasterStatus) override;
    HRESULT WINAPI GetDisplayMode(D3DDISPLAYMODE * pMode) override;
    HRESULT WINAPI GetDevice(IDirect3DDevice9 ** ppDevice) override;
    HRESULT WINAPI GetPresentParameters(D3DPRESENT_PARAMETERS * pPresentationParameters) override;
};
