"""tools/manage.py and the engine-effects option (docs/architecture/engine-effects-modern.md, phase 1): --engine-effects
native|off|plumes exported as X3M_ENGINE_EFFECTS only when given (an inherited value is dropped), refused under --vanilla,
kept in player mode only when given, the `engine bodies:` dry-run line; and the engine body table install step
(<game>/x3m/engine_bodies.json generated by tools/effects/engine_bodies.py, ownership by its `tool` field, removal by
uninstall only), once with the generator mocked and once for real on test_engine_bodies' synthetic stock tree.
The launch harness is test_launcher_defaults' (a temporary game directory, a fake proxy, nothing launched)."""
import contextlib
import hashlib
import importlib.util
import io
import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))


def load_manage():
    spec = importlib.util.spec_from_file_location('engine_effects_manage', ROOT / 'tools/manage.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def table(bodies=('effects\\engines\\fx_a',), missing=0):
    return {'schema': 1, 'tool': 'tools/effects/engine_bodies.py', 'generated_from': {'view': 'installed'},
            'counts': {'bodies': len(bodies), 'missing': missing}, 'bodies': {b: {'value': 1000} for b in bodies},
            'missing': []}


def fake_generator(content, code=0, stderr=''):
    """A subprocess.run stand-in that writes `content` to the generator's --out and returns `code`."""
    calls = []

    def run(argv, **kwargs):
        calls.append(argv)
        if content is not None:
            Path(argv[argv.index('--out') + 1]).write_text(content)
        return subprocess.CompletedProcess(argv, code, '', stderr)
    run.calls = calls
    return run


class EngineEffectsLaunchOption(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.module = load_manage()
        cls.directory = tempfile.TemporaryDirectory()
        game = Path(cls.directory.name) / 'game'
        game.mkdir()
        (game / 'X3AP.exe').touch()
        (game / 'd3d9.dll').write_bytes(b'proxy')
        (game / 'x3-modern-install.json').write_text(json.dumps({'sha256': hashlib.sha256(b'proxy').hexdigest()}))
        cls.game = game
        cls.wine = Path(cls.directory.name) / 'wine'
        cls.wine.touch()

    @classmethod
    def tearDownClass(cls):
        cls.directory.cleanup()

    def launch(self, *args, vanilla=False, inherited=None):
        argv = ['manage.py', 'launch', '--dry-run', *(['--vanilla'] if vanilla else []), '--game-dir', str(self.game), *args]
        environ = {k: v for k, v in os.environ.items() if not k.startswith('X3M_')}
        environ.update(inherited or {})
        output, error = io.StringIO(), io.StringIO()
        module = self.module
        with mock.patch.object(sys, 'argv', argv), mock.patch.object(module, 'WINE', self.wine), \
                mock.patch.object(module, 'VOICE_DECODER_REPO', None), mock.patch.dict(module.os.environ, environ, clear=True), \
                mock.patch.object(module.subprocess, 'call', side_effect=AssertionError('must never launch')), \
                contextlib.redirect_stdout(output), contextlib.redirect_stderr(error):
            try:
                module.main()
            except SystemExit as exit_error:
                return exit_error.code, None, error.getvalue()
        return 0, json.loads(output.getvalue()), error.getvalue()

    def test_default_sends_nothing_and_drops_an_inherited_value(self):
        for inherited in (None, {'X3M_ENGINE_EFFECTS': 'off'}):
            code, data, error = self.launch(inherited=inherited)
            self.assertEqual(code, 0, error)
            self.assertNotIn('X3M_ENGINE_EFFECTS', data['env'])
            # Unset is the DLL default plumes, so the table line is reported.
            self.assertTrue(data['engine_bodies'].startswith('engine bodies: missing ('), data['engine_bodies'])
            self.assertIn(data['engine_bodies'], error)

    def test_explicit_values_and_the_table_line(self):
        table_path = self.game / 'x3m/engine_bodies.json'
        for value in ('native', 'off', 'plumes'):
            code, data, error = self.launch('--engine-effects', value, inherited={'X3M_ENGINE_EFFECTS': 'off'})
            self.assertEqual(code, 0, error)
            self.assertEqual(data['env']['X3M_ENGINE_EFFECTS'], value)
            if value == 'native':
                self.assertIsNone(data['engine_bodies'])
            else:
                self.assertTrue(data['engine_bodies'].startswith('engine bodies: missing ('), data['engine_bodies'])
                self.assertIn(data['engine_bodies'], error)
        try:
            table_path.parent.mkdir()
            table_path.write_text(json.dumps(table(('a', 'b'), missing=3)))
            _, data, _ = self.launch('--engine-effects', 'off')
            self.assertEqual(data['engine_bodies'], 'engine bodies: ok (2 bodies, 3 listed but not loadable, schema 1, view installed)')
            table_path.write_text('{"tool": "something else", "bodies": {}}')
            _, data, _ = self.launch('--engine-effects', 'plumes')
            self.assertTrue(data['engine_bodies'].startswith('engine bodies: unreadable'), data['engine_bodies'])
        finally:
            table_path.unlink(missing_ok=True)
            table_path.parent.rmdir()
        code, _, error = self.launch('--engine-effects', 'on')
        self.assertEqual(code, 2)
        self.assertIn("invalid choice: 'on'", error)

    def test_vanilla_refuses_and_drops(self):
        for value in ('native', 'off', 'plumes'):
            code, _, error = self.launch('--engine-effects', value, vanilla=True)
            self.assertEqual(code, 2, value)
            self.assertIn('--engine-effects cannot be combined with --vanilla', error)
        code, data, error = self.launch(vanilla=True, inherited={'X3M_ENGINE_EFFECTS': 'off'})
        self.assertEqual(code, 0, error)
        self.assertNotIn('X3M_ENGINE_EFFECTS', data['env'])
        self.assertIsNone(data['engine_bodies'])

    def test_player_mode_sends_it_only_when_given(self):
        def x3m(data):
            return {k: v for k, v in data['env'].items() if k.startswith('X3M_')}
        _, data, _ = self.launch('--config', inherited={'X3M_ENGINE_EFFECTS': 'off'})
        self.assertEqual(x3m(data), {})
        _, data, _ = self.launch('--config', '--engine-effects', 'off')
        self.assertEqual(x3m(data), {'X3M_ENGINE_EFFECTS': 'off'})
        _, data, _ = self.launch('--config', '--engine-effects', 'native')
        self.assertEqual(x3m(data), {'X3M_ENGINE_EFFECTS': 'native'})


class EngineBodiesInstall(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.module = load_manage()

    def test_install_unchanged_retained_failed_and_remove(self):
        module = self.module
        with tempfile.TemporaryDirectory() as directory:
            game = Path(directory) / 'game'
            game.mkdir()
            target = game / 'x3m/engine_bodies.json'
            text = json.dumps(table(('a', 'b'), missing=1), indent=1)
            run = fake_generator(text)
            first = module.install_engine_bodies(game, run=run)
            self.assertEqual((first['status'], first['bodies'], first['missing']), ('installed', 2, 1))
            self.assertEqual(target.read_text(), text)
            self.assertEqual(first['sha256'], hashlib.sha256(text.encode()).hexdigest())
            argv = run.calls[0]
            self.assertEqual(argv[:2], [sys.executable, str(ROOT / 'tools/effects/engine_bodies.py')])
            self.assertEqual(argv[argv.index('--game-root') + 1], str(game))
            self.assertFalse(Path(argv[argv.index('--out') + 1]).is_relative_to(game))   # the generator refuses inside
            self.assertFalse(Path(argv[argv.index('--out') + 1]).parent.exists())        # its scratch directory is gone
            self.assertEqual(module.install_engine_bodies(game, run=fake_generator(text))['status'], 'unchanged')
            # A failed or malformed generation leaves the previous table in place.
            for run, reason in ((fake_generator(None, code=1, stderr='engine_bodies: types/Bodies not found\n'),
                                 'generator exit 1: engine_bodies: types/Bodies not found'),
                                (fake_generator('{"tool": "other"}'), 'generator exit 0')):
                failed = module.install_engine_bodies(game, run=run)
                self.assertEqual((failed['status'], failed['reason']), ('failed', reason))
                self.assertEqual(target.read_text(), text)
            newer = json.dumps(table(('a',)))
            self.assertEqual(module.install_engine_bodies(game, run=fake_generator(newer))['status'], 'installed')
            self.assertEqual(target.read_text(), newer)
            self.assertEqual(sorted(p.name for p in target.parent.iterdir()), ['engine_bodies.json'])   # no .tmp left
            # Removal: ours and the regenerate .previous go, x3m/ goes when empty; a foreign file stays and blocks install.
            target.with_name('engine_bodies.json.previous').write_text(text)
            self.assertEqual(module.remove_engine_bodies(game),
                             {'removed': ['x3m/engine_bodies.json', 'x3m/engine_bodies.json.previous'], 'retained': []})
            self.assertFalse(target.parent.exists())
            target.parent.mkdir()
            (target.parent / 'fog-families.bin').write_bytes(b'x')
            target.write_text('{"player": "file"}')
            retained = module.install_engine_bodies(game, run=fake_generator(text))
            self.assertEqual(retained['status'], 'retained')
            self.assertEqual(target.read_text(), '{"player": "file"}')
            self.assertEqual(module.remove_engine_bodies(game), {'removed': [], 'retained': ['x3m/engine_bodies.json']})
            target.write_text(text)
            self.assertEqual(module.remove_engine_bodies(game)['removed'], ['x3m/engine_bodies.json'])
            self.assertTrue((target.parent / 'fog-families.bin').is_file())   # x3m/ not empty: kept

    def test_real_generator_on_the_synthetic_stock_tree(self):
        import test_engine_bodies
        with tempfile.TemporaryDirectory() as directory:
            game = test_engine_bodies.game(Path(directory) / 'X3')
            result = self.module.install_engine_bodies(game)
            self.assertEqual(result['status'], 'installed', result['reason'])
            expected = test_engine_bodies.eb.generate(game)
            installed = json.loads((game / 'x3m/engine_bodies.json').read_text())
            self.assertEqual(installed, json.loads(test_engine_bodies.eb.dumps(expected)))
            self.assertEqual((result['bodies'], result['missing']), (expected['counts']['bodies'], expected['counts']['missing']))
            self.assertEqual(self.module.install_engine_bodies(game)['status'], 'unchanged')   # deterministic

    def test_action_wiring(self):
        source = (ROOT / 'tools/manage.py').read_text()
        install = source.index("if args.action == 'install':")
        uninstall = source.index("elif args.action == 'uninstall':")
        rollback = source.index("elif args.action == 'rollback':")
        # Generated after the proxy install succeeded, removed by uninstall only (rollback leaves it for any DLL).
        self.assertLess(source.index('media_package.install(game, source', install), source.index('install_engine_bodies(game)', install))
        self.assertLess(source.index('install_engine_bodies(game)', install), uninstall)
        self.assertLess(uninstall, source.index('remove_engine_bodies(game)', uninstall))
        self.assertLess(source.index('remove_engine_bodies(game)', uninstall), rollback)
        self.assertEqual(source.count('= remove_engine_bodies(game)'), 1)


if __name__ == '__main__':
    unittest.main()
