"""Host tests for tools/media_transcode.py.

No bottle and no Wine: every test runs against a temporary "game directory"
with a tiny real MPEG-1 clip generated by ffmpeg's ``testsrc`` (skipped when
ffmpeg is absent), plus fake files for the install/restore refusals.  The
install/restore tests never touch a real game directory; ``x3_running`` is
patched so the pgrep guard is exercised without a running game.
"""
import importlib.util
import json
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

_spec = importlib.util.spec_from_file_location(
    'media_transcode', ROOT / 'tools' / 'media_transcode.py')
mt = importlib.util.module_from_spec(_spec)
sys.modules['media_transcode'] = mt
_spec.loader.exec_module(mt)

HAVE_FFMPEG = Path(mt.FFMPEG).exists() and Path(mt.FFPROBE).exists()


def make_clip(path, seconds=1, rate=30, size='64x64'):
    path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [mt.FFMPEG, '-v', 'error', '-y', '-f', 'lavfi',
         '-i', f'testsrc=size={size}:rate={rate}:duration={seconds}',
         '-c:v', 'mpeg1video', '-f', 'mpeg1video', str(path)],
        check=True)
    return path


class ArgumentValidation(unittest.TestCase):
    def test_cue_id_range_and_type(self):
        self.assertEqual(mt.parse_cue_id('1'), 1)
        for bad in ('x', '-1', '100000'):
            with self.assertRaises(Exception):
                mt.parse_cue_id(bad)

    def test_container_choice_rejected_by_parser(self):
        parser = mt.build_parser()
        with self.assertRaises(SystemExit):
            parser.parse_args(['build', '--id', '1', '--container', 'mkv',
                               '--out', '/tmp/x'])

    def test_build_requires_out(self):
        parser = mt.build_parser()
        with self.assertRaises(SystemExit):
            parser.parse_args(['build', '--id', '1'])

    def test_cue_path_is_five_digits(self):
        self.assertEqual(mt.cue_path(Path('/g'), 1).name, '00001.dat')
        self.assertEqual(mt.cue_path(Path('/g'), 812).name, '00812.dat')

    def test_missing_source_reports_error(self):
        with tempfile.TemporaryDirectory() as tmp:
            rc = mt.main(['build', '--id', '7', '--game-dir', tmp,
                          '--out', str(Path(tmp) / 'out')])
            self.assertEqual(rc, 2)

    def test_build_refuses_to_write_into_game_dir(self):
        if not HAVE_FFMPEG:
            self.skipTest('ffmpeg not present')
        with tempfile.TemporaryDirectory() as tmp:
            game = Path(tmp) / 'X3'
            make_clip(game / 'mov' / '00001.dat')
            rc = mt.main(['build', '--id', '1', '--game-dir', str(game),
                          '--out', str(game / 'mov')])
            self.assertEqual(rc, 2)
            self.assertEqual(sorted(p.name for p in (game / 'mov').iterdir()),
                             ['00001.dat'])


@unittest.skipUnless(HAVE_FFMPEG, 'ffmpeg/ffprobe not present')
class ProbeAndSidecar(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.game = self.tmp / 'X3'
        self.src = make_clip(self.game / 'mov' / '00001.dat')
        self.out = self.tmp / 'out'

    def tearDown(self):
        self._tmp.cleanup()

    def test_probe_stream_reports_true_rate_and_count(self):
        info = mt.probe_stream(self.src)
        self.assertEqual(info['codec_name'], 'mpeg1video')
        self.assertEqual((info['width'], info['height']), (64, 64))
        # raw MPEG-1 ES: r_frame_rate is the field rate, the packet duration
        # in the stream time base is the frame rate
        self.assertEqual(info['frame_rate'], '30')
        self.assertEqual(info['frame_rate_source'], 'packet_duration')
        self.assertEqual(info['frame_count'], 30)
        self.assertAlmostEqual(info['duration_s'], 1.0, places=6)

    def _build(self, container):
        rc = mt.main(['build', '--id', '1', '--container', container,
                      '--game-dir', str(self.game), '--out', str(self.out)])
        self.assertEqual(rc, 0)
        dst = self.out / f'00001.{container}.dat'
        sidecar = Path(str(dst) + '.json')
        self.assertTrue(dst.is_file())
        return dst, json.loads(sidecar.read_text())

    def test_sidecar_schema_avi(self):
        dst, rec = self._build('avi')
        self.assertEqual(rec['tool'], 'media_transcode')
        self.assertEqual(rec['sidecar_version'], mt.SIDECAR_VERSION)
        self.assertEqual(rec['cue_id'], 1)
        self.assertEqual(rec['container'], 'avi')
        for side, path in (('source', self.src), ('result', dst)):
            block = rec[side]
            for key in ('path', 'sha256', 'size', 'codec_name', 'width',
                        'height', 'frame_rate', 'frame_count', 'duration_s',
                        'pix_fmt'):
                self.assertIn(key, block, f'{side}.{key}')
            self.assertEqual(block['sha256'], mt.sha256_file(path))
            self.assertEqual(block['size'], path.stat().st_size)
        self.assertEqual(rec['result']['codec_name'], 'h264')
        self.assertEqual(rec['result']['pix_fmt'], 'yuv420p')
        self.assertEqual(rec['result']['frame_count'],
                         rec['source']['frame_count'])
        self.assertEqual(rec['result']['frame_rate'],
                         rec['source']['frame_rate'])
        self.assertEqual((rec['result']['width'], rec['result']['height']),
                         (rec['source']['width'], rec['source']['height']))
        self.assertEqual(rec['checks']['frame_count_delta'], 0)
        self.assertLessEqual(abs(rec['checks']['duration_delta_s']),
                             rec['checks']['frame_seconds'])
        self.assertEqual(rec['encode']['gop'], 12)
        self.assertEqual(rec['encode']['b_frames'], 0)
        self.assertIn('-bf', rec['encode']['command'])
        self.assertGreater(rec['encode']['wall_time_s'], 0.0)

    def test_sidecar_schema_mp4(self):
        dst, rec = self._build('mp4')
        self.assertEqual(rec['container'], 'mp4')
        self.assertEqual(dst.name, '00001.mp4.dat')
        self.assertEqual(rec['result']['frame_count'],
                         rec['source']['frame_count'])

    def test_probe_subcommand_lists_the_cue(self):
        rc = mt.main(['probe', '--game-dir', str(self.game)])
        self.assertEqual(rc, 0)


class InstallRestore(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.game = self.tmp / 'X3'
        self.mov = self.game / 'mov'
        self.mov.mkdir(parents=True)
        self.target = self.mov / '00001.dat'
        self.target.write_bytes(b'ORIGINAL-MPEG1-BYTES' * 16)
        self.src_dir = self.tmp / 'out'
        self.src_dir.mkdir()
        self.new = self.src_dir / '00001.avi.dat'
        self.new.write_bytes(b'H264-IN-AVI' * 32)
        self._real_running = mt.x3_running
        mt.x3_running = lambda: None

    def tearDown(self):
        mt.x3_running = self._real_running
        self._tmp.cleanup()

    def args(self, *extra):
        return ['--game-dir', str(self.game), *extra]

    def test_refuses_while_game_runs(self):
        mt.x3_running = lambda: '1234 X3AP.exe'
        self.assertEqual(mt.main(['install', '--id', '1',
                                  '--from', str(self.src_dir)] + self.args()), 2)
        self.assertEqual(mt.main(['restore', '--id', '1'] + self.args()), 2)
        self.assertEqual(self.target.read_bytes(), b'ORIGINAL-MPEG1-BYTES' * 16)

    def test_install_then_restore_round_trip(self):
        original = self.target.read_bytes()
        rc = mt.main(['install', '--id', '1', '--from', str(self.src_dir)]
                     + self.args())
        self.assertEqual(rc, 0)
        orig = self.mov / '00001.dat.orig'
        self.assertEqual(orig.read_bytes(), original)
        self.assertEqual(self.target.read_bytes(), self.new.read_bytes())
        self.assertFalse((self.mov / '00001.dat.new').exists())

        rc = mt.main(['restore', '--id', '1'] + self.args())
        self.assertEqual(rc, 0)
        self.assertEqual(self.target.read_bytes(), original)

    def test_second_install_refused_while_transcode_is_in_place(self):
        self.assertEqual(
            mt.main(['install', '--id', '1', '--from', str(self.src_dir)]
                    + self.args()), 0)
        installed = self.target.read_bytes()
        self.assertEqual(
            mt.main(['install', '--id', '1', '--from', str(self.src_dir)]
                    + self.args()), 2)
        # neither the game file nor the saved original moved
        self.assertEqual(self.target.read_bytes(), installed)
        self.assertEqual((self.mov / '00001.dat.orig').read_bytes(),
                         b'ORIGINAL-MPEG1-BYTES' * 16)

    def test_install_refused_when_no_transcode_present(self):
        self.new.unlink()
        self.assertEqual(
            mt.main(['install', '--id', '1', '--from', str(self.src_dir)]
                    + self.args()), 2)
        self.assertFalse((self.mov / '00001.dat.orig').exists())

    def test_install_ambiguous_without_container(self):
        shutil.copy2(self.new, self.src_dir / '00001.mp4.dat')
        self.assertEqual(
            mt.main(['install', '--id', '1', '--from', str(self.src_dir)]
                    + self.args()), 2)
        self.assertEqual(
            mt.main(['install', '--id', '1', '--from', str(self.src_dir),
                     '--container', 'mp4'] + self.args()), 0)

    def test_install_refused_when_cue_absent(self):
        self.target.unlink()
        self.assertEqual(
            mt.main(['install', '--id', '1', '--from', str(self.src_dir)]
                    + self.args()), 2)

    def test_restore_without_saved_original_refused(self):
        self.assertEqual(mt.main(['restore', '--id', '1'] + self.args()), 2)

    def test_restore_is_idempotent(self):
        mt.main(['install', '--id', '1', '--from', str(self.src_dir)]
                + self.args())
        self.assertEqual(mt.main(['restore', '--id', '1'] + self.args()), 0)
        self.assertEqual(mt.main(['restore', '--id', '1'] + self.args()), 0)
        self.assertEqual(self.target.read_bytes(),
                         b'ORIGINAL-MPEG1-BYTES' * 16)


if __name__ == '__main__':
    unittest.main()
