"""Seven exact glass originals: source-use proof and real combined transformer.

Original/generated bytecode stays local. This is host evidence, not GPU parity.
"""
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest

ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'tools/analysis'))
import inspect_glass_materials as proof
import inspect_linear_materials as core
import inspect_motion_output_profiles as motion

PP=0x200000;SAT=0x100000

def reg(kind,n):return 0x80000000|((kind&7)<<28)|((kind&24)<<8)|n

def src(kind,n,sw=0xe4):return reg(kind,n)|(sw<<16)

def dst(kind,n,mask=7):return reg(kind,n)|(mask<<16)

def load(path):return motion.instructions(path.read_bytes())[:2]

def span(w,i):return tuple(w[i['dword']:i['dword']+i['length']+1])

class GlassMaterialTransformerTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.originals=Path(os.environ.get('X3M_SHADER_PROGRAM_DIRECTORY','/tmp/x3-shader-sweep/programs'))
        if not all((cls.originals/(r+'.bin')).exists() for r in ['vs_'+v for v in proof.VERTICES]+['ps_'+p for p in proof.PIXELS]):raise unittest.SkipTest('local glass originals unavailable')
        cls.report=proof.derive(cls.originals)
        cls.profiles={r['id']:r for r in cls.report['programs']}
        cls.temp=tempfile.TemporaryDirectory(prefix='x3-glass-structure-');cls.addClassCleanup(cls.temp.cleanup);cls.output=Path(cls.temp.name)
        compiler=shutil.which('clang++') or shutil.which('c++')
        command=[compiler,'-std=c++17','-O2','-Wall','-Wextra','-Werror',str(ROOT/'verification/probe/glass_material_structure.cpp'),str(ROOT/'src/renderer/linear_material.cpp'),str(ROOT/'src/renderer/material_motion.cpp'),'-o',str(cls.output/'driver')]
        done=subprocess.run(command,capture_output=True,text=True);assert done.returncode==0,done.stdout+done.stderr
        done=subprocess.run([str(cls.output/'driver'),str(cls.originals),str(cls.output)],capture_output=True,text=True);assert done.returncode==0,done.stdout+done.stderr
        cls.driver=json.loads(done.stdout)

    def each(self):
        for file in sorted(self.output.glob('*.bin')):
            id,depth,gain=file.stem.split('-')
            if gain=='motion':continue
            w,items=load(file)
            yield id,int(depth),int(gain),w,items

    def test_report_exact_archive_pair_join(self):
        self.assertEqual(json.loads(json.dumps(self.report)),json.loads((ROOT/'docs/reverse-engineering/glass-material-profiles.json').read_text()))
        self.assertEqual((self.driver['pairs'],self.driver['programs'],self.driver['variants']),(6,7,56))
        inventory=json.loads((ROOT/'verification/results/motion-output-profiles.json').read_text())
        expected={(p['vs'],p['ps']) for p in inventory['pairs'] if 'glass' in p['effects']['basenames'] or 'glass2s' in p['effects']['basenames'] or 'glass_0000' in p['effects']['basenames'] or 'glass_0001' in p['effects']['basenames']}
        self.assertEqual(set(proof.PAIRS),expected)

    def test_every_original_instruction_changes_only_reviewed_lanes(self):
        for id,depth,gain,w,items in self.each():
            p=self.profiles[id];vs=id.startswith('vs_');ow,original=load(self.originals/(id+'.bin'))
            transformed=[span(w,i) for i in items];cursor=0
            for i in original:
                at,op=i['dword'],i['opcode'];tokens=list(span(ow,i))
                if vs and op==31 and motion.register_of(tokens[2])==(6,6):
                    tokens[2]=dst(6,6)
                if not vs and op==31 and motion.register_of(tokens[2])==(1,5):tokens[2]=dst(1,5)
                if vs:
                    if at==p['point']:
                        tokens[3]=src(0,7)
                        if p['loop']:tokens[0]=(3<<24)|5;del tokens[4]
                    if at==p['emissive']:tokens[1]=dst(6,6);tokens[3 if p['loop'] else 4]=src(0,7)
                    if at==p['fresnel'][0]:tokens[1]=dst(6,1,1)
                else:
                    if at in p['rgb']:tokens[1]&=~PP
                    if at==p['clamp']:tokens[1]&=~SAT;tokens[2]=src(1,5)
                    for operand,c in p['lights']:
                        if at<operand<=at+i['length']:tokens[operand-at]=src(0,12 if c==1 else 13)
                    if at<p['fresnel'][0]<=at+i['length']:tokens[p['fresnel'][0]-at]=src(1,0,0)
                    if at==p['final_rgb']:tokens[1]=dst(0,11)
                try:cursor=transformed.index(tuple(tokens),cursor)+1
                except ValueError:self.fail((id,depth,gain,'changed original',at))

    def test_color_lane_and_precision_contract(self):
        for id,depth,gain,w,items in self.each():
            vs=id.startswith('vs_');kind=6 if vs else 1
            declarations={((i['words'][0]&31),(i['words'][0]>>16)&15):i['words'][1] for i in items if i['opcode']==31 and motion.register_of(i['words'][1])[0]==kind}
            self.assertEqual(declarations[(10,0)],dst(kind,1 if vs else 0,15)|(0 if vs else PP))
            self.assertEqual(declarations[(10,1)],dst(kind,6 if vs else 5,7))
            self.assertEqual(declarations[(5,4)],dst(kind,7 if vs else 6,15))
            if depth:self.assertEqual(declarations[(5,5)],dst(kind,8 if vs else 7,15 if vs else 3))
            color0=[];fresnel=[]
            for i in items:
                if i['opcode'] in motion.HEADER_OPCODES:continue
                d,sources=motion.split_operands(i,3)
                if vs and d and d['name']=='o1':color0.append((i['opcode'],d['mask']))
                if not vs:
                    for source in sources:
                        if source['name']=='v0':color0.append((i['opcode'],d['mask'],source['swizzle']))
                        if source['name']=='v5':fresnel.append(source['swizzle'])
            self.assertEqual(color0,[(5,'w'),(1,'w'),(14,'x')] if vs else ([(5,'w','xxxx'),(5,'w','wwww')]))
            if not vs:self.assertEqual(fresnel,['xyzw'])

    def test_temporal_insertions_and_samples_are_byte_exact(self):
        for id,depth,gain,w,items in self.each():
            ow,original=load(self.originals/(id+'.bin'));mw,mi=load(self.output/(id+f'-{depth}-motion.bin'))
            # Ordinary-motion additions are recognized by ordered subtraction
            # of immutable original spans, then required intact in combined.
            original_spans=[span(ow,i) for i in original];additions=[];cursor=0
            for i in mi:
                t=span(mw,i)
                if cursor<len(original_spans) and t==original_spans[cursor]:cursor+=1
                else:additions.append(t)
            self.assertEqual(cursor,len(original_spans))
            combined=[span(w,i) for i in items];cursor=0
            for t in additions:
                cursor=combined.index(t,cursor)+1
            self.assertEqual([span(w,i) for i in items if i['opcode']==66],[span(ow,i) for i in original if i['opcode']==66])
            self.assertEqual([span(w,i) for i in items if i['opcode'] in [38,39,40,42,43]],[span(ow,i) for i in original if i['opcode'] in [38,39,40,42,43]])

    def test_resource_limits(self):
        maxima={'vs':0,'ps':0}
        for id,depth,gain,w,items in self.each():
            stage=id[:2];code=(self.output/(id+f'-{depth}-{gain}.bin')).read_bytes();p=motion.profile(code,id,stage,'3_0')
            self.assertTrue(p['parsed'] and p['control_flow_balanced'])
            decoded=core.decode_sites(items)
            # Authored sanitizer/zero-mask opcodes are one documented SM3 slot.
            extra={at:r for at,r in decoded.items() if r['item']['opcode'] in [10,11,12]}
            slots=core.weighted_slots({at:r for at,r in decoded.items() if at not in extra},p,stage)+len(extra)
            self.assertLessEqual(slots,512);maxima[stage]=max(maxima[stage],slots)
            self.assertLess(p['highest_temporary'],32)
        self.assertGreater(maxima['ps'],43)

if __name__=='__main__':unittest.main()
