import hashlib,importlib.util,tempfile,unittest
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[2]; SPEC=importlib.util.spec_from_file_location('fog_sector_patches_preview',ROOT/'tools/analysis/fog_sector_patches_preview.py'); preview=importlib.util.module_from_spec(SPEC); SPEC.loader.exec_module(preview)
class FogSectorPatchesPreview(unittest.TestCase):
 def volume(self,rho=.5):
  v=np.empty((8,8,8,4),np.float32); v[...,3]=rho; v[...,:3]=rho*np.array([.2,.5,.8],np.float32); return v
 def test_rotation_is_fixed_proper(self):
  np.testing.assert_allclose(preview.R.T@preview.R,np.eye(3),rtol=0,atol=1e-15); self.assertAlmostEqual(float(np.linalg.det(preview.R)),1.,places=15)
 def test_hash_and_integer_lattice_values(self):
  vectors=[((0,0,0),0,0xf1a88b6a,.8879560828208923),((1,-1,2),0,0x974c75ef,.18202084302902222),
           ((-7,13,-29),1,0x521c20bf,-.3585166335105896),((123456,-654321,17),2,0x8b8dffd5,.09027093648910522)]
  # Constants were generated by an independent scalar uint32 implementation.
  for point,octave,_hash,value in vectors:
   self.assertAlmostEqual(float(preview.value_noise(np.array([point],np.float64),octave)[0]),value,places=7)
  self.assertEqual([int(preview.mix_array(np.array([x],np.uint64))[0]) for x in (0,1,0xffffffff)],
                   [0x00000000,0x688990c0,0x6768824a])
 def test_quintic_noise_is_continuous_at_cell_boundary(self):
  eps=1e-6; p=np.array([[1-eps,.2,.3],[1+eps,.2,.3]])
  self.assertLess(abs(float(np.diff(preview.value_noise(p,2))[0])),2e-5)
 def test_macro_formula_and_bounds(self):
  pts=np.array([[0.,0.,0.],[10000.,20000.,-30000.]])
  b,M=preview.macro(pts); manual=(4*preview.value_noise(pts/(8*preview.P),0)+2*preview.value_noise((pts@preview.R.T)/(4*preview.P),1)+preview.value_noise((pts@(preview.R@preview.R).T)/(2*preview.P),2))/7
  np.testing.assert_allclose(b,manual,rtol=0,atol=1e-7); self.assertTrue(np.all((M>=0)&(M<=1)))
 def test_zero_and_negative_depth_are_exact_identity(self):
  result=preview.integrate(self.volume(),np.zeros(3),np.array([[1.,0,0],[-1.,0,0]],np.float32),np.array([0.,-1.],np.float32),4e-6,128.)
  np.testing.assert_array_equal(result['S'],np.zeros((2,3),np.float32)); np.testing.assert_array_equal(result['T'],np.ones(2,np.float32))
 def test_fine_field_sampled_only_on_positive_macro_support(self):
  original=preview.fog.sample_level; calls=[0]
  def counted(volume,points): calls[0]+=len(points); return original(volume,points)
  preview.fog.sample_level=counted
  try: result=preview.integrate(self.volume(),np.zeros(3),np.array([[1.,0,0]],np.float32),np.array([4096.],np.float32),4e-6,128.,collect=True,components=False)
  finally: preview.fog.sample_level=original
  self.assertEqual(2*calls[0],int(result['cost']['fine_reads'].sum())); self.assertTrue(np.isfinite(result['S']).all())
 def test_near_component_clips_exactly_at_12000(self):
  original_macro,original_sample=preview.macro,preview.fog.sample_level
  preview.macro=lambda points:(np.ones(np.asarray(points).shape[:-1],np.float32),np.ones(np.asarray(points).shape[:-1],np.float32))
  def constant(volume,points):
   out=np.zeros(np.asarray(points).shape[:-1]+(4,),np.float32); out[...,3]=.5; out[...,:3]=.1; return out
  preview.fog.sample_level=constant
  try: result=preview.integrate(self.volume(),np.zeros(3),np.array([[1.,0,0]],np.float32),np.array([preview.fog.FAR],np.float32),4e-6,128.)
  finally: preview.macro,preview.fog.sample_level=original_macro,original_sample
  self.assertAlmostEqual(float(result['near']['tau'][0]),4e-6*.5*preview.fog.NEAR,places=6)
 def test_limit_is_clamped_to_40km(self):
  original_macro,original_sample=preview.macro,preview.fog.sample_level
  preview.macro=lambda points:(np.ones(np.asarray(points).shape[:-1],np.float32),np.ones(np.asarray(points).shape[:-1],np.float32))
  def constant(volume,points):
   out=np.zeros(np.asarray(points).shape[:-1]+(4,),np.float32); out[...,3]=.5; return out
  preview.fog.sample_level=constant
  try: result=preview.integrate(self.volume(),np.zeros(3),np.array([[1.,0,0]],np.float32),np.array([2*preview.fog.FAR],np.float32),4e-6,128.,components=False)
  finally: preview.macro,preview.fog.sample_level=original_macro,original_sample
  # Outer taper integrates to 175,000 render units of effective distance.
  self.assertAlmostEqual(float(result['tau'][0]),4e-6*.5*175000,places=5)
 def test_saved_comparison_poses_and_pixel_centres(self):
  poses=preview.poses(); self.assertEqual([p['name'] for p in poses],['A','B','C']); self.assertEqual([p['prior_name'] for p in poses],['inside-core','30km','38km'])
  rays=preview.connected.camera_rays(poses[0]['origin'],poses[0]['forward'],poses[0]['up'],4,2); self.assertEqual(rays.shape,(8,3)); np.testing.assert_allclose(np.linalg.norm(rays,axis=1),1,atol=1e-7)
 def test_angular_variation_uses_fixed_view_neighbors(self):
  values=np.zeros((preview.HEIGHT,preview.WIDTH)); values[:,preview.WIDTH//2:]=1
  row=preview.angular_variation(values)
  self.assertGreater(row['standard_deviation'],0); self.assertEqual(row['four_neighbor_absolute_difference']['max'],1.)
 def test_result_json_and_image_hash_validation(self):
  with tempfile.TemporaryDirectory() as tmp:
   out=Path(tmp); images={}
   for i in range(8):
    path=out/f'{i}.png'; path.write_bytes(f'image{i}'.encode()); images[path.name]=hashlib.sha256(path.read_bytes()).hexdigest()
   result={'schema':1,'families':{'bluewell':{'views':[{}, {}, {}]},'foggreenoutlands':{'views':[{}, {}, {}]}},'images':images}
   preview.validate_result(result,out)
   (out/'0.png').write_bytes(b'changed')
   with self.assertRaisesRegex(ValueError,'image hash mismatch'): preview.validate_result(result,out)
 def test_reported_laws_pass(self): self.assertTrue(all(preview.laws().values()),preview.laws())
if __name__=='__main__': unittest.main()
