// Generated by tools/config/generate.py from tools/config/schema.py: do not edit, run the generator.
// The settings the proxy reads (docs/architecture/config-file.md): the resolver in src/proxy/config.cpp
// binary-searches `entries` by environment name; config_default:: carries each default as a typed constant.
// No Windows header: included by the resolver and by the host parser test.
#pragma once

namespace x3m::config::schema {
enum class Type : unsigned char { Bool, Int, Float, IntList, FloatList, Enum, String, Path };
enum Flag : unsigned char { developer = 1, env_only = 2 };
struct Interval { double min, max; bool min_open; }; // min..max inclusive, (min, max] when min_open
struct ElementRange { unsigned short first; unsigned char count; }; // the intervals of one list position
struct Entry {
    const char* env;           // X3M_<KEY>, sorted
    const char* key;           // the INI key
    Type type;
    const char* default_value; // nullptr: nothing (the read site's own behaviour)
    const char* off_value;     // the X3M_CONFIG=bare base; nullptr: unset
    unsigned short range_first; unsigned char range_count;     // intervals[]: a value (every list element) in one of them
    unsigned short element_first; unsigned char element_count; // element_ranges[]: per list position, overrides the range
    unsigned char count_mask;  // bit n: a list of n elements is accepted (0: any count)
    const char* choices;       // "|"-separated words ("" none): the enum set, or words a number or list also accepts
    unsigned char flags;       // Flag
    short marker_of;           // index of the key a launcher default marker follows, -1
};
struct Alias { const char* key; unsigned short entry; };
constexpr unsigned interval_count = 100;
constexpr Interval intervals[interval_count] = {
    {0.0, 64.0, true},
    {0.0, 64.0, false},
    {0.0, 256.0, true},
    {0.0, 180.0, true},
    {1.0, 1000000.0, false},
    {0.0, 4294967295.0, false},
    {0.0, 4294967295.0, false},
    {0.0, 1.0, false},
    {0.0, 10.0, true},
    {0.0, 90.0, false},
    {-1.0, 1.0, false},
    {0.0, 30.0, false},
    {0.0, 1.0, false},
    {0.0, 10.0, true},
    {0.0, 10.0, true},
    {0.0, 64.0, false},
    {0.0, 16.0, false},
    {1.0, 8.0, false},
    {0.0, 0.0, false},
    {64.0, 8192.0, false},
    {2.0, 16.0, false},
    {0.0, 512.0, false},
    {2.0, 64.0, false},
    {70.0, 100.0, false},
    {1.0, 100000.0, false},
    {0.0, 999999.0, false},
    {1.0, 10000.0, false},
    {0.0, 4294967295.0, false},
    {0.0, 60.0, true},
    {0.0, 60.0, true},
    {0.0, 65504.0, true},
    {0.0, 1000.0, true},
    {-16.0, 16.0, false},
    {0.0, 8.0, false},
    {-16.0, 16.0, false},
    {-16.0, 16.0, false},
    {-16.0, 16.0, false},
    {0.0, 64.0, true},
    {0.0, 1.0, false},
    {0.0001, 64.0, false},
    {0.0, 1.0, false},
    {0.0, 1.0, false},
    {0.0, 4.0, false},
    {1.0, 8.0, false},
    {1.0, 8.0, false},
    {0.0, 16.0, false},
    {0.0, 1000000.0, true},
    {0.0, 1000000.0, true},
    {0.0, 8.0, false},
    {0.0, 4096.0, false},
    {0.0, 16.0, false},
    {0.0, 16.0, false},
    {0.0, 0.5, false},
    {1.0, 3600.0, false},
    {1.0, 100000.0, false},
    {2.0, 64.0, false},
    {0.0, 0.5, false},
    {100.0, 1000000.0, false},
    {1.0, 3600.0, false},
    {0.0, 0.0, false},
    {1.0, 8.0, false},
    {0.0, 1.0, false},
    {0.5, 8.0, false},
    {0.0, 0.0, false},
    {50.0, 150000.0, false},
    {0.5, 8.0, false},
    {1.0, 4096.0, false},
    {1.0, 4096.0, false},
    {2.0, 16.0, false},
    {0.0, 1000000.0, false},
    {-1e+300, 64.0, false},
    {1.0, 4096.0, false},
    {64.0, 4096.0, false},
    {1.0, 4.0, false},
    {1.0, 10000000.0, false},
    {0.0001, 100.0, false},
    {0.25, 4.0, false},
    {0.005, 0.25, false},
    {1.0, 64.0, false},
    {0.0, 8.0, false},
    {0.0, 1000.0, false},
    {0.0, 4294967295.0, false},
    {0.0, 0.99, false},
    {0.0, 4.0, false},
    {0.0, 1000000.0, true},
    {0.0, 1000000.0, true},
    {0.0, 64.0, false},
    {0.0, 64.0, true},
    {0.5, 0.98, false},
    {-8.0, 8.0, false},
    {0.0, 1.0, false},
    {1.0, 16.0, false},
    {0.0, 0.0, false},
    {0.125, 16.0, false},
    {0.0, 0.99, false},
    {0.0, 1.0, false},
    {0.0, 64.0, false},
    {0.0, 64.0, true},
    {0.0, 65000.0, false},
    {0.0, 0.1, false},
};
constexpr unsigned element_range_count = 18;
constexpr ElementRange element_ranges[element_range_count] = {
    {1, 1},
    {2, 1},
    {18, 2},
    {20, 1},
    {21, 1},
    {46, 1},
    {47, 1},
    {48, 1},
    {82, 1},
    {83, 1},
    {84, 1},
    {85, 1},
    {86, 1},
    {87, 1},
    {94, 1},
    {95, 1},
    {96, 1},
    {97, 1},
};
constexpr unsigned entry_count = 232;
constexpr const char schema_date[] = "2026-09-26";
constexpr Entry entries[entry_count] = {
    {"X3M_ADMISSION", "admission", Type::Bool, nullptr, nullptr, 0, 0, 0, 0, 0, "", 1, -1},
    {"X3M_BLOOM_SOURCE_CLAMP", "bloom_source_clamp", Type::Float, "1.0", nullptr, 0, 1, 0, 0, 0, "", 0, -1},
    {"X3M_BOLT_FOOTPRINT", "bolt_footprint", Type::FloatList, "3,12", nullptr, 1, 0, 0, 2, 6, "", 0, -1},
    {"X3M_CAMERA", "camera", Type::Enum, "chase", nullptr, 3, 0, 2, 0, 0, "chase|vanilla", 0, -1},
    {"X3M_CAMERA_CUT_DEG", "camera_cut_deg", Type::Float, "20.0", nullptr, 3, 1, 2, 0, 0, "", 1, -1},
    {"X3M_CAMERA_LOG", "camera_log", Type::Int, nullptr, nullptr, 4, 1, 2, 0, 0, "", 1, -1},
    {"X3M_CAPTURE_FRAMES", "capture_frames", Type::Int, "8", nullptr, 5, 1, 2, 0, 0, "", 0, -1},
    {"X3M_CAPTURE_START", "capture_start", Type::Int, "999999", nullptr, 6, 1, 2, 0, 0, "", 1, -1},
    {"X3M_CHASE_COMBAT_TIGHTNESS", "chase_combat_tightness", Type::Float, "0.0", nullptr, 7, 1, 2, 0, 0, "", 1, -1},
    {"X3M_CHASE_DISTANCE_SCALE", "chase_distance_scale", Type::Float, "1.05", nullptr, 8, 1, 2, 0, 0, "", 0, -1},
    {"X3M_CHASE_FOV_COMPENSATE", "chase_fov_compensate", Type::Bool, "1", nullptr, 9, 0, 2, 0, 0, "", 0, -1},
    {"X3M_CHASE_HUD_ANCHOR", "chase_hud_anchor", Type::Enum, "forward", nullptr, 9, 0, 2, 0, 0, "forward|centre", 0, -1},
    {"X3M_CHASE_LAG_CLAMP_DEG", "chase_lag_clamp_deg", Type::Float, nullptr, nullptr, 9, 1, 2, 0, 0, "", 1, -1},
    {"X3M_CHASE_OFFSET_Y", "chase_offset_y", Type::Float, "0.5", nullptr, 10, 1, 2, 0, 0, "", 0, -1},
    {"X3M_CHASE_PITCH_DOWN_DEG", "chase_pitch_down_deg", Type::Float, "0.5", nullptr, 11, 1, 2, 0, 0, "", 0, -1},
    {"X3M_CHASE_POS_LAG_CLAMP", "chase_pos_lag_clamp", Type::Float, nullptr, nullptr, 12, 1, 2, 0, 0, "", 1, -1},
    {"X3M_CHASE_POS_TAU", "chase_pos_tau", Type::Float, nullptr, nullptr, 13, 1, 2, 0, 0, "", 1, -1},
    {"X3M_CHASE_ROT_TAU", "chase_rot_tau", Type::Float, nullptr, nullptr, 14, 1, 2, 0, 0, "", 1, -1},
    {"X3M_CHASE_SCENE_FIX", "chase_scene_fix", Type::Bool, "0", nullptr, 15, 0, 2, 0, 0, "", 0, -1},
    {"X3M_CHASE_VIEW_RESTORE", "chase_view_restore", Type::Bool, "1", nullptr, 15, 0, 2, 0, 0, "", 0, -1},
    {"X3M_COLLIDE_BOX_CULL", "collide_box_cull", Type::Bool, "1", nullptr, 15, 0, 2, 0, 0, "", 0, -1},
    {"X3M_COLLIDE_MEMO", "collide_memo", Type::Bool, "1", nullptr, 15, 0, 2, 0, 0, "", 0, -1},
    {"X3M_COLLIDE_MEMO_VERIFY", "collide_memo_verify", Type::Bool, nullptr, nullptr, 15, 0, 2, 0, 0, "", 1, -1},
    {"X3M_COLLIDE_NARROW_CENSUS", "collide_narrow_census", Type::Bool, nullptr, nullptr, 15, 0, 2, 0, 0, "", 1, -1},
    {"X3M_COLLIDE_QUERY_PHASES", "collide_query_phases", Type::Bool, nullptr, nullptr, 15, 0, 2, 0, 0, "", 1, -1},
    {"X3M_COLLIDE_SAT_SSE2", "collide_sat_sse2", Type::Bool, "1", nullptr, 15, 0, 2, 0, 0, "", 0, -1},
    {"X3M_CONFIG", "config", Type::Path, nullptr, nullptr, 15, 0, 2, 0, 0, "", 3, -1},
    {"X3M_CRYPT_CACHE", "crypt_cache", Type::Bool, "1", nullptr, 15, 0, 2, 0, 0, "", 0, -1},
    {"X3M_CULL_CENSUS", "cull_census", Type::Bool, nullptr, nullptr, 15, 0, 2, 0, 0, "", 1, -1},
    {"X3M_CULL_SMALL_PARTS_PROJECTILES", "cull_small_parts_projectiles", Type::Enum, "on", nullptr, 15, 0, 2, 0, 0, "on|off", 0, -1},
    {"X3M_CULL_SMALL_PARTS_PX", "cull_small_parts_px", Type::Float, "4.0000", nullptr, 15, 1, 2, 0, 0, "", 0, -1},
    {"X3M_CURSOR_REASSERT", "cursor_reassert", Type::Bool, nullptr, nullptr, 16, 0, 2, 0, 0, "", 0, -1},
    {"X3M_DAT_HANDLES", "dat_handles", Type::Bool, "1", nullptr, 16, 0, 2, 0, 0, "", 0, -1},
    {"X3M_DEBUG", "debug", Type::Bool, nullptr, nullptr, 16, 0, 2, 0, 0, "", 0, -1},
    {"X3M_DEPTH_COPY", "depth_copy", Type::Bool, nullptr, nullptr, 16, 0, 2, 0, 0, "", 1, -1},
    {"X3M_DRAW_TRACE", "draw_trace", Type::Bool, nullptr, nullptr, 16, 0, 2, 0, 0, "", 1, -1},
    {"X3M_EMISSION_GAIN", "emission_gain", Type::Float, nullptr, nullptr, 16, 1, 2, 0, 0, "", 1, -1},
    {"X3M_EMISSION_SOURCE_GAIN", "emission_source_gain", Type::Float, "2.0", nullptr, 17, 1, 2, 0, 0, "", 0, -1},
    {"X3M_FADE_ROUTE", "fade_route", Type::String, nullptr, nullptr, 18, 0, 2, 0, 0, "", 1, -1},
    {"X3M_FADE_RT2_OWNER", "fade_rt2_owner", Type::Enum, "on", nullptr, 18, 0, 2, 0, 0, "on|off", 1, -1},
    {"X3M_FADE_RT2_OWNER_DEFAULT", "fade_rt2_owner_default", Type::Bool, "1", nullptr, 18, 0, 2, 0, 0, "", 3, 39},
    {"X3M_FADE_WITNESS", "fade_witness", Type::String, nullptr, nullptr, 18, 0, 2, 0, 0, "", 1, -1},
    {"X3M_FINITE_POSITIONS", "finite_positions", Type::Bool, nullptr, nullptr, 18, 0, 2, 0, 0, "", 1, -1},
    {"X3M_FIXTURE_EXCEPTION", "fixture_exception", Type::String, nullptr, nullptr, 18, 0, 2, 0, 0, "", 3, -1},
    {"X3M_FIXTURE_FADE_RECT", "fixture_fade_rect", Type::String, nullptr, nullptr, 18, 0, 2, 0, 0, "", 3, -1},
    {"X3M_FIXTURE_LOG_BENCH", "fixture_log_bench", Type::String, nullptr, nullptr, 18, 0, 2, 0, 0, "", 3, -1},
    {"X3M_FIXTURE_MOTION_DEPTH", "fixture_motion_depth", Type::String, nullptr, nullptr, 18, 0, 2, 0, 0, "", 3, -1},
    {"X3M_FIXTURE_QUAD_FVF", "fixture_quad_fvf", Type::String, nullptr, nullptr, 18, 0, 2, 0, 0, "", 3, -1},
    {"X3M_FIXTURE_SCREEN_CAPS_FAULT", "fixture_screen_caps_fault", Type::String, nullptr, nullptr, 18, 0, 2, 0, 0, "", 3, -1},
    {"X3M_FIXTURE_SCREEN_RECT", "fixture_screen_rect", Type::String, nullptr, nullptr, 18, 0, 2, 0, 0, "", 3, -1},
    {"X3M_FIXTURE_SHADOW_CASCADES", "fixture_shadow_cascades", Type::String, nullptr, nullptr, 18, 0, 2, 0, 0, "", 3, -1},
    {"X3M_FIXTURE_SLICE_NEAR", "fixture_slice_near", Type::String, nullptr, nullptr, 18, 0, 2, 0, 0, "", 3, -1},
    {"X3M_FIXTURE_STRETCH_FAULT", "fixture_stretch_fault", Type::String, nullptr, nullptr, 18, 0, 2, 0, 0, "", 3, -1},
    {"X3M_FIXTURE_SUN_LANE_FAULT", "fixture_sun_lane_fault", Type::String, nullptr, nullptr, 18, 0, 2, 0, 0, "", 3, -1},
    {"X3M_FIXTURE_TAA_FILTER_FAULT", "fixture_taa_filter_fault", Type::String, nullptr, nullptr, 18, 0, 2, 0, 0, "", 3, -1},
    {"X3M_FIXTURE_TAA_K", "fixture_taa_k", Type::String, nullptr, nullptr, 18, 0, 2, 0, 0, "", 3, -1},
    {"X3M_FIXTURE_TAA_SENTINEL", "fixture_taa_sentinel", Type::String, nullptr, nullptr, 18, 0, 2, 0, 0, "", 3, -1},
    {"X3M_FOG_DOCKED", "fog_docked", Type::Bool, "1", nullptr, 18, 0, 2, 0, 0, "", 0, -1},
    {"X3M_FOG_DUST_MOTES", "fog_dust_motes", Type::FloatList, "1300,3,128", nullptr, 18, 0, 2, 3, 8, "", 0, -1},
    {"X3M_FOG_FAMILIES", "fog_families", Type::Path, nullptr, nullptr, 22, 0, 5, 0, 0, "", 1, -1},
    {"X3M_FOG_HANDOVER_COLDFILL", "fog_handover_coldfill", Type::Bool, "1", nullptr, 22, 0, 5, 0, 0, "", 0, -1},
    {"X3M_FOG_HANDOVER_PREFILL", "fog_handover_prefill", Type::Bool, "1", nullptr, 22, 0, 5, 0, 0, "", 0, -1},
    {"X3M_FOG_HANDOVER_STEP", "fog_handover_step", Type::Bool, "1", nullptr, 22, 0, 5, 0, 0, "", 0, -1},
    {"X3M_FOG_MARCH_SCALE", "fog_march_scale", Type::Enum, "4", nullptr, 22, 0, 5, 0, 0, "2|4", 0, -1},
    {"X3M_FOG_MOTES_MAX_PX", "fog_motes_max_px", Type::Float, "8", nullptr, 22, 1, 5, 0, 0, "", 0, -1},
    {"X3M_FOV", "fov", Type::Float, "90", nullptr, 23, 1, 5, 0, 0, "game", 0, -1},
    {"X3M_FPS_OVERLAY", "fps_overlay", Type::Bool, nullptr, nullptr, 24, 0, 5, 0, 0, "", 1, -1},
    {"X3M_FRAME_END_STRIDE", "frame_end_stride", Type::Int, nullptr, nullptr, 24, 1, 5, 0, 0, "", 1, -1},
    {"X3M_FRAME_PHASES", "frame_phases", Type::Bool, nullptr, nullptr, 25, 0, 5, 0, 0, "", 1, -1},
    {"X3M_FRAME_TIMING", "frame_timing", Type::Bool, nullptr, nullptr, 25, 0, 5, 0, 0, "", 1, -1},
    {"X3M_FRAME_TIMING_STATE_STAMPS", "frame_timing_state_stamps", Type::Int, nullptr, nullptr, 25, 1, 5, 0, 0, "", 1, -1},
    {"X3M_GAME_PHASES", "game_phases", Type::Bool, nullptr, nullptr, 26, 0, 5, 0, 0, "", 1, -1},
    {"X3M_GAME_PHASE_THRESHOLD_MS", "game_phase_threshold_ms", Type::Int, nullptr, nullptr, 26, 1, 5, 0, 0, "", 1, -1},
    {"X3M_GPU_SYNC_TIMING", "gpu_sync_timing", Type::Bool, nullptr, nullptr, 27, 0, 5, 0, 0, "", 1, -1},
    {"X3M_GZ_BUFFER", "gz_buffer", Type::Bool, "1", nullptr, 27, 0, 5, 0, 0, "", 0, -1},
    {"X3M_GZ_BUFFER_KB", "gz_buffer_kb", Type::Int, "256", nullptr, 27, 1, 5, 0, 0, "", 1, -1},
    {"X3M_HDR", "hdr", Type::Bool, "1", nullptr, 28, 0, 5, 0, 0, "", 0, -1},
    {"X3M_HDR_ADAPT_DOWN", "hdr_adapt_down", Type::Float, nullptr, nullptr, 28, 1, 5, 0, 0, "", 0, -1},
    {"X3M_HDR_ADAPT_UP", "hdr_adapt_up", Type::Float, nullptr, nullptr, 29, 1, 5, 0, 0, "", 0, -1},
    {"X3M_HDR_BLOOM", "hdr_bloom", Type::Bool, "1", nullptr, 30, 0, 5, 0, 0, "", 0, -1},
    {"X3M_HDR_CLAMP", "hdr_clamp", Type::Float, "0.0", nullptr, 30, 1, 5, 0, 0, "", 1, -1},
    {"X3M_HDR_DECODE", "hdr_decode", Type::String, "gamma2.2", nullptr, 31, 0, 5, 0, 0, "", 1, -1},
    {"X3M_HDR_DITHER", "hdr_dither", Type::Bool, "1", nullptr, 31, 0, 5, 0, 0, "", 0, -1},
    {"X3M_HDR_DT_MS", "hdr_dt_ms", Type::Float, nullptr, nullptr, 31, 1, 5, 0, 0, "", 1, -1},
    {"X3M_HDR_EV", "hdr_ev", Type::Float, "0.0", nullptr, 32, 1, 5, 0, 0, "", 0, -1},
    {"X3M_HDR_EV_DEADBAND", "hdr_ev_deadband", Type::Float, "0.25", nullptr, 33, 1, 5, 0, 0, "", 1, -1},
    {"X3M_HDR_EV_MANUAL", "hdr_ev_manual", Type::Float, "", nullptr, 34, 1, 5, 0, 0, "", 0, -1},
    {"X3M_HDR_EV_MAX", "hdr_ev_max", Type::Float, "1.3", nullptr, 35, 1, 5, 0, 0, "", 0, -1},
    {"X3M_HDR_EV_MIN", "hdr_ev_min", Type::Float, "-3.0", nullptr, 36, 1, 5, 0, 0, "", 0, -1},
    {"X3M_HDR_EXPOSURE", "hdr_exposure", Type::Enum, "auto", nullptr, 37, 0, 5, 0, 0, "auto|manual|fixed", 0, -1},
    {"X3M_HDR_KEY", "hdr_key", Type::Float, nullptr, nullptr, 37, 1, 5, 0, 0, "", 0, -1},
    {"X3M_HDR_KEY_PULL", "hdr_key_pull", Type::Float, "0.25", nullptr, 38, 1, 5, 0, 0, "", 1, -1},
    {"X3M_HDR_LOOK", "hdr_look", Type::Enum, "none", nullptr, 39, 0, 5, 0, 0, "none|golden|punchy", 0, -1},
    {"X3M_HDR_METER_BG", "hdr_meter_bg", Type::Float, "0.001953125", nullptr, 39, 1, 5, 0, 0, "", 1, -1},
    {"X3M_HDR_METER_EDGE_WEIGHT", "hdr_meter_edge_weight", Type::Float, "0.35", nullptr, 40, 1, 5, 0, 0, "", 1, -1},
    {"X3M_HDR_METER_MIN_LIT", "hdr_meter_min_lit", Type::Float, nullptr, nullptr, 41, 1, 5, 0, 0, "", 1, -1},
    {"X3M_HDR_TONEMAP", "hdr_tonemap", Type::Enum, "agx", nullptr, 42, 0, 5, 0, 0, "agx|identity|1|0", 0, -1},
    {"X3M_HDR_WHITE_TARGET", "hdr_white_target", Type::Float, "0.9", nullptr, 42, 1, 5, 0, 0, "", 1, -1},
    {"X3M_HULL_EMISSION_GAIN", "hull_emission_gain", Type::Float, "2.0", nullptr, 43, 1, 5, 0, 0, "", 1, -1},
    {"X3M_HULL_EMISSIVE_WIDENING", "hull_emissive_widening", Type::String, "4,4", nullptr, 44, 0, 5, 0, 0, "", 1, -1},
    {"X3M_HULL_LIGHTMAP_GAIN", "hull_lightmap_gain", Type::Float, "4.0", nullptr, 44, 1, 5, 0, 0, "", 0, -1},
    {"X3M_LIGHTMAP_EMISSIVE_GAIN", "lightmap_emissive_gain", Type::Float, nullptr, nullptr, 45, 1, 5, 0, 0, "", 1, -1},
    {"X3M_LIGHT_MAP_FAR_FADE", "light_map_far_fade", Type::FloatList, "80,220,1", nullptr, 46, 0, 5, 3, 12, "", 0, -1},
    {"X3M_LIGHT_PHASES", "light_phases", Type::Bool, nullptr, nullptr, 49, 0, 8, 0, 0, "", 1, -1},
    {"X3M_LINEAR_DISTANCE_FADE", "linear_distance_fade", Type::Bool, nullptr, nullptr, 49, 0, 8, 0, 0, "", 1, -1},
    {"X3M_LINEAR_EMISSIONS", "linear_emissions", Type::Bool, nullptr, nullptr, 49, 0, 8, 0, 0, "", 1, -1},
    {"X3M_LINEAR_MATERIALS", "linear_materials", Type::Bool, nullptr, nullptr, 49, 0, 8, 0, 0, "", 1, -1},
    {"X3M_LOADING_PROBES", "loading_probes", Type::Bool, nullptr, nullptr, 49, 0, 8, 0, 0, "", 1, -1},
    {"X3M_LOCKED_PREFIX_LOG", "locked_prefix_log", Type::Bool, nullptr, nullptr, 49, 0, 8, 0, 0, "", 1, -1},
    {"X3M_LOD_OCCLUSION", "lod_occlusion", Type::Enum, "all", nullptr, 49, 0, 8, 0, 0, "off|record0|all", 0, -1},
    {"X3M_LOD_OCCLUSION_DEFAULT", "lod_occlusion_default", Type::Bool, "1", nullptr, 49, 0, 8, 0, 0, "", 3, 109},
    {"X3M_LOD_SWITCH_LOG", "lod_switch_log", Type::Int, nullptr, nullptr, 49, 1, 8, 0, 0, "", 1, -1},
    {"X3M_LOG_FILE", "log_file", Type::Path, nullptr, nullptr, 50, 0, 8, 0, 0, "", 0, -1},
    {"X3M_LOOP_PHASES", "loop_phases", Type::Bool, nullptr, nullptr, 50, 0, 8, 0, 0, "", 1, -1},
    {"X3M_MATERIAL_DIRECT_GAIN", "material_direct_gain", Type::Float, nullptr, nullptr, 50, 1, 8, 0, 0, "", 1, -1},
    {"X3M_MATERIAL_EMISSIVE_GAIN", "material_emissive_gain", Type::Float, nullptr, nullptr, 51, 1, 8, 0, 0, "", 1, -1},
    {"X3M_MATERIAL_FILL", "material_fill", Type::Float, nullptr, nullptr, 52, 1, 8, 0, 0, "", 1, -1},
    {"X3M_MEDIA_CUE_CACHE", "media_cue_cache", Type::Bool, "1", nullptr, 53, 0, 8, 0, 0, "", 1, -1},
    {"X3M_MEDIA_CUE_RETRY_S", "media_cue_retry_s", Type::Int, "30", nullptr, 53, 1, 8, 0, 0, "", 1, -1},
    {"X3M_MEDIA_CUE_TRACE", "media_cue_trace", Type::Bool, nullptr, nullptr, 54, 0, 8, 0, 0, "", 1, -1},
    {"X3M_MESH_ADJACENCY", "mesh_adjacency", Type::Enum, "fast", nullptr, 54, 0, 8, 0, 0, "fast|native|verify", 0, -1},
    {"X3M_MOTION_CAPTURE", "motion_capture", Type::Bool, nullptr, nullptr, 54, 0, 8, 0, 0, "", 1, -1},
    {"X3M_MOTION_CUT_MEDIAN_PX", "motion_cut_median_px", Type::Float, "1e30", nullptr, 54, 0, 8, 0, 0, "", 1, -1},
    {"X3M_MOTION_CUT_MISSING", "motion_cut_missing", Type::Float, "1", nullptr, 54, 0, 8, 0, 0, "", 1, -1},
    {"X3M_MOTION_FRAME_LOG", "motion_frame_log", Type::Int, nullptr, nullptr, 54, 1, 8, 0, 0, "", 1, -1},
    {"X3M_MOTION_JITTER", "motion_jitter", Type::Bool, "1", nullptr, 55, 0, 8, 0, 0, "", 0, -1},
    {"X3M_MOTION_JITTER_SAMPLES", "motion_jitter_samples", Type::Int, nullptr, nullptr, 55, 1, 8, 0, 0, "", 1, -1},
    {"X3M_MOTION_OUTPUT", "motion_output", Type::Bool, "1", nullptr, 56, 0, 8, 0, 0, "", 1, -1},
    {"X3M_MOTION_RT_MODE", "motion_rt_mode", Type::Enum, "lazy", nullptr, 56, 0, 8, 0, 0, "lazy|perdraw", 1, -1},
    {"X3M_MUSIC_KEEP", "music_keep", Type::Bool, "1", nullptr, 56, 0, 8, 0, 0, "", 0, -1},
    {"X3M_MUSIC_TRACE", "music_trace", Type::Bool, nullptr, nullptr, 56, 0, 8, 0, 0, "", 1, -1},
    {"X3M_OBJECT_BOUNDS_LOG", "object_bounds_log", Type::Bool, nullptr, nullptr, 56, 0, 8, 0, 0, "", 1, -1},
    {"X3M_OBJECT_LIFETIME", "object_lifetime", Type::Bool, "1", nullptr, 56, 0, 8, 0, 0, "", 1, -1},
    {"X3M_OBJECT_TRACE", "object_trace", Type::Bool, "1", nullptr, 56, 0, 8, 0, 0, "", 1, -1},
    {"X3M_ORIGINAL_FILL", "original_fill", Type::Float, "0.01", nullptr, 56, 1, 8, 0, 0, "", 0, -1},
    {"X3M_ORIGINAL_FILL_DEFAULT", "original_fill_default", Type::Bool, "1", nullptr, 57, 0, 8, 0, 0, "", 3, 134},
    {"X3M_OWNERSHIP", "ownership", Type::Bool, "1", nullptr, 57, 0, 8, 0, 0, "", 1, -1},
    {"X3M_PASS_PHASES", "pass_phases", Type::Bool, nullptr, nullptr, 57, 0, 8, 0, 0, "", 1, -1},
    {"X3M_PAUSE_KEY", "pause_key", Type::String, nullptr, nullptr, 57, 0, 8, 0, 0, "", 0, -1},
    {"X3M_PAUSE_KEY_ONLY", "pause_key_only", Type::Bool, "1", nullptr, 57, 0, 8, 0, 0, "", 0, -1},
    {"X3M_PERF", "perf", Type::Bool, nullptr, nullptr, 57, 0, 8, 0, 0, "", 0, -1},
    {"X3M_POINT_LIGHT_ROOT_ADMISSION", "point_light_root_admission", Type::Bool, nullptr, nullptr, 57, 0, 8, 0, 0, "", 0, -1},
    {"X3M_PROFILE", "profile", Type::Bool, nullptr, nullptr, 57, 0, 8, 0, 0, "", 1, -1},
    {"X3M_PROFILE_INTERVAL_US", "profile_interval_us", Type::Int, nullptr, nullptr, 57, 1, 8, 0, 0, "", 1, -1},
    {"X3M_PROFILE_REPORT_S", "profile_report_s", Type::Int, nullptr, nullptr, 58, 1, 8, 0, 0, "", 1, -1},
    {"X3M_RESIDUAL_PHASES", "residual_phases", Type::Bool, nullptr, nullptr, 59, 0, 8, 0, 0, "", 1, -1},
    {"X3M_RESOURCE_READ", "resource_read", Type::Enum, "fast", nullptr, 59, 0, 8, 0, 0, "fast|native|verify", 0, -1},
    {"X3M_SCENE_DEPTH_CAPTURE", "scene_depth_capture", Type::Bool, nullptr, nullptr, 59, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SCENE_HOOK", "scene_hook", Type::Enum, "1", nullptr, 59, 0, 8, 0, 0, "1|0", 1, -1},
    {"X3M_SCREEN_EMISSION", "screen_emission", Type::Bool, nullptr, nullptr, 59, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SCREEN_EMISSION_ADDITIVE", "screen_emission_additive", Type::Float, "2.0", nullptr, 59, 2, 8, 0, 0, "", 0, -1},
    {"X3M_SCREEN_EMISSION_ADDITIVE_ALPHA", "screen_emission_additive_alpha", Type::Float, "0.0", nullptr, 61, 1, 8, 0, 0, "", 1, -1},
    {"X3M_SCREEN_EMISSION_BOUND", "screen_emission_bound", Type::Bool, nullptr, nullptr, 62, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SCREEN_EMISSION_GAIN", "screen_emission_gain", Type::Float, nullptr, nullptr, 62, 1, 8, 0, 0, "", 1, -1},
    {"X3M_SCREEN_EMISSION_TIMING", "screen_emission_timing", Type::Bool, nullptr, nullptr, 63, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SECTOR_BACKGROUND", "sector_background", Type::Bool, nullptr, nullptr, 63, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_ALPHA_CASTERS", "shadow_alpha_casters", Type::Bool, "1", nullptr, 63, 0, 8, 0, 0, "", 0, -1},
    {"X3M_SHADOW_CASCADES", "shadow_cascades", Type::FloatList, "250.0,1500.0,7500.0,37500.0,150000.0", nullptr, 63, 2, 8, 0, 62, "", 0, -1},
    {"X3M_SHADOW_CASCADE_ADAPTIVE_C0", "shadow_cascade_adaptive_c0", Type::Float, "1.5", nullptr, 65, 1, 8, 0, 0, "", 0, -1},
    {"X3M_SHADOW_CASCADE_BACKFACE_FROM", "shadow_cascade_backface_from", Type::String, nullptr, nullptr, 66, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_CASCADE_BUDGET", "shadow_cascade_budget", Type::Int, nullptr, nullptr, 66, 1, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_CASCADE_CAPS", "shadow_cascade_caps", Type::IntList, nullptr, nullptr, 67, 1, 8, 0, 62, "", 1, -1},
    {"X3M_SHADOW_CASCADE_DROP_ORDER", "shadow_cascade_drop_order", Type::Enum, "importance", nullptr, 68, 0, 8, 0, 0, "importance|submission", 0, -1},
    {"X3M_SHADOW_CASCADE_LADDER_RATIO", "shadow_cascade_ladder_ratio", Type::Float, nullptr, nullptr, 68, 1, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_CASCADE_LARGE_MIN", "shadow_cascade_large_min", Type::Float, nullptr, nullptr, 69, 1, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_CASCADE_MIN_FOOTPRINT", "shadow_cascade_min_footprint", Type::Float, "8.0", nullptr, 70, 1, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_CASCADE_RECORDS", "shadow_cascade_records", Type::IntList, "1024,1024,2048,4096,4096", nullptr, 71, 1, 8, 0, 62, "", 0, -1},
    {"X3M_SHADOW_CASCADE_SIZES", "shadow_cascade_sizes", Type::IntList, "2048,4096,4096,4096,2048", nullptr, 72, 1, 8, 0, 62, "", 0, -1},
    {"X3M_SHADOW_CASCADE_STATIC_FROM", "shadow_cascade_static_from", Type::Int, nullptr, nullptr, 73, 1, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_CASTER_RETENTION", "shadow_caster_retention", Type::Bool, "1", nullptr, 74, 0, 8, 0, 0, "", 0, -1},
    {"X3M_SHADOW_CASTER_RETENTION_AGE", "shadow_caster_retention_age", Type::Int, nullptr, nullptr, 74, 1, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_CASTER_RETENTION_EPS", "shadow_caster_retention_eps", Type::Float, nullptr, nullptr, 75, 1, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_REPLAY_CANDIDATES", "shadow_replay_candidates", Type::Bool, "1", nullptr, 76, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_REPLAY_CAP", "shadow_replay_cap", Type::String, nullptr, nullptr, 76, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_REPLAY_DEPTH", "shadow_replay_depth", Type::Bool, "1", nullptr, 76, 0, 8, 0, 0, "", 0, -1},
    {"X3M_SHADOW_REPLAY_DEPTH_HALF", "shadow_replay_depth_half", Type::String, nullptr, nullptr, 76, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_REPLAY_EXTENT", "shadow_replay_extent", Type::String, nullptr, nullptr, 76, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_REPLAY_SIZE", "shadow_replay_size", Type::String, nullptr, nullptr, 76, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_RETENTION_CENSUS", "shadow_retention_census", Type::Bool, nullptr, nullptr, 76, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_RETENTION_TIMING", "shadow_retention_timing", Type::Bool, nullptr, nullptr, 76, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_ROWS", "shadow_rows", Type::Bool, nullptr, nullptr, 76, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_SUN_POLL", "shadow_sun_poll", Type::Bool, "1", nullptr, 76, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_SUN_TRACE", "shadow_sun_trace", Type::Bool, nullptr, nullptr, 76, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SHADOW_TIMING", "shadow_timing", Type::Bool, nullptr, nullptr, 76, 0, 8, 0, 0, "", 1, -1},
    {"X3M_STATE_SHADOW", "state_shadow", Type::String, nullptr, nullptr, 76, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SUBMIT_PHASES", "submit_phases", Type::Bool, nullptr, nullptr, 76, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SUN_FLARE_FIX", "sun_flare_fix", Type::Enum, "on", nullptr, 76, 0, 8, 0, 0, "on|off", 0, -1},
    {"X3M_SUN_OCCLUSION", "sun_occlusion", Type::Bool, "1", nullptr, 76, 0, 8, 0, 0, "", 0, -1},
    {"X3M_SUN_OCCLUSION_CORE_F", "sun_occlusion_core_f", Type::Bool, "1", nullptr, 76, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SUN_OCCLUSION_CURVE", "sun_occlusion_curve", Type::Float, nullptr, nullptr, 76, 1, 8, 0, 0, "", 1, -1},
    {"X3M_SUN_OCCLUSION_DEFAULT", "sun_occlusion_default", Type::Bool, "1", nullptr, 77, 0, 8, 0, 0, "", 3, 187},
    {"X3M_SUN_OCCLUSION_LOG", "sun_occlusion_log", Type::Bool, nullptr, nullptr, 77, 0, 8, 0, 0, "", 1, -1},
    {"X3M_SUN_OCCLUSION_RADIUS", "sun_occlusion_radius", Type::Float, nullptr, nullptr, 77, 1, 8, 0, 0, "", 1, -1},
    {"X3M_SUN_SHADOW_APPLY", "sun_shadow_apply", Type::Bool, "1", nullptr, 78, 0, 8, 0, 0, "", 0, -1},
    {"X3M_SUN_SHADOW_BIAS_CLAMP_TEXELS", "sun_shadow_bias_clamp_texels", Type::Float, "20.97152", nullptr, 78, 1, 8, 0, 0, "", 0, -1},
    {"X3M_SUN_SHADOW_BIAS_SLOPE_TEXELS", "sun_shadow_bias_slope_texels", Type::Float, "0.2", nullptr, 79, 1, 8, 0, 0, "", 0, -1},
    {"X3M_SUN_SHADOW_BIAS_UNITS", "sun_shadow_bias_units", Type::Float, "0.53571875", nullptr, 80, 1, 8, 0, 0, "", 0, -1},
    {"X3M_SUN_SHADOW_LANE", "sun_shadow_lane", Type::Bool, "1", nullptr, 81, 0, 8, 0, 0, "", 0, -1},
    {"X3M_TAA", "taa", Type::Bool, "1", nullptr, 81, 0, 8, 0, 0, "", 0, -1},
    {"X3M_TAA_ALPHA_HISTORY", "taa_alpha_history", Type::Bool, nullptr, nullptr, 81, 0, 8, 0, 0, "", 0, -1},
    {"X3M_TAA_BOX_RESOLUTION", "taa_box_resolution", Type::Enum, "half", nullptr, 81, 0, 8, 0, 0, "half|full", 1, -1},
    {"X3M_TAA_BOX_RESOLUTION_DEFAULT", "taa_box_resolution_default", Type::Bool, "1", nullptr, 81, 0, 8, 0, 0, "", 3, 200},
    {"X3M_TAA_DEBUG", "taa_debug", Type::Int, nullptr, nullptr, 81, 1, 8, 0, 0, "", 1, -1},
    {"X3M_TAA_FAR_CLIP", "taa_far_clip", Type::Enum, "7x7", nullptr, 82, 0, 8, 0, 0, "7x7|3x3", 1, -1},
    {"X3M_TAA_FAR_CLIP_DEFAULT", "taa_far_clip_default", Type::Bool, "1", nullptr, 82, 0, 8, 0, 0, "", 3, 203},
    {"X3M_TAA_FAR_GATE", "taa_far_gate", Type::Enum, "camera", nullptr, 82, 0, 8, 0, 0, "camera|screen", 1, -1},
    {"X3M_TAA_FAR_GATE_DEFAULT", "taa_far_gate_default", Type::Bool, "1", nullptr, 82, 0, 8, 0, 0, "", 3, 205},
    {"X3M_TAA_FAR_STABILISER", "taa_far_stabiliser", Type::FloatList, "0.985,0,60,68,0.03,0.25", nullptr, 82, 0, 8, 6, 86, "", 0, -1},
    {"X3M_TAA_HISTORY_WEIGHT", "taa_history_weight", Type::Float, nullptr, nullptr, 88, 1, 14, 0, 0, "", 0, -1},
    {"X3M_TAA_MIP_BIAS", "taa_mip_bias", Type::Float, "-0.5", nullptr, 89, 1, 14, 0, 0, "", 0, -1},
    {"X3M_TAA_MOTION_WEIGHT", "taa_motion_weight", Type::String, "0.7,2,8", nullptr, 90, 0, 14, 0, 0, "", 1, -1},
    {"X3M_TAA_SHARPEN", "taa_sharpen", Type::Float, "0.75", nullptr, 90, 1, 14, 0, 0, "", 0, -1},
    {"X3M_TAA_SKY_HISTORY", "taa_sky_history", Type::String, "strict", nullptr, 91, 0, 14, 0, 0, "", 1, -1},
    {"X3M_TAA_SKY_HISTORY_BAND_PX", "taa_sky_history_band_px", Type::Float, nullptr, nullptr, 91, 1, 14, 0, 0, "", 1, -1},
    {"X3M_TAA_SKY_HISTORY_EXIT_PX", "taa_sky_history_exit_px", Type::Float, "0.25", nullptr, 92, 2, 14, 0, 0, "", 1, -1},
    {"X3M_TAA_THIN_REGION", "taa_thin_region", Type::FloatList, "0.97,1", nullptr, 94, 0, 14, 4, 22, "", 0, -1},
    {"X3M_TAA_THIN_REGION_EMISSIVE", "taa_thin_region_emissive", Type::Float, "1", nullptr, 98, 1, 18, 0, 0, "", 0, -1},
    {"X3M_TAA_THIN_VOTE", "taa_thin_vote", Type::Enum, "on", nullptr, 99, 0, 18, 0, 0, "on|off", 1, -1},
    {"X3M_TAA_THIN_VOTE_DEFAULT", "taa_thin_vote_default", Type::Bool, "1", nullptr, 99, 0, 18, 0, 0, "", 3, 217},
    {"X3M_TAA_UNMATCHED_STATIC", "taa_unmatched_static", Type::String, "node", nullptr, 99, 0, 18, 0, 0, "", 1, -1},
    {"X3M_TELEMETRY", "telemetry", Type::Bool, nullptr, nullptr, 99, 0, 18, 0, 0, "", 1, -1},
    {"X3M_TELEMETRY_DRAW", "telemetry_draw", Type::Bool, nullptr, nullptr, 99, 0, 18, 0, 0, "", 1, -1},
    {"X3M_TERRAN_STATION_LOD", "terran_station_lod", Type::Enum, "size", nullptr, 99, 0, 18, 0, 0, "size|distance", 0, -1},
    {"X3M_VOICE_DMO_FALLBACK", "voice_dmo_fallback", Type::Bool, "1", nullptr, 99, 0, 18, 0, 0, "", 0, -1},
    {"X3M_VOLUMETRIC_FOG", "volumetric_fog", Type::Bool, "1", nullptr, 99, 0, 18, 0, 0, "", 0, -1},
    {"X3M_VOLUMETRIC_FOG_CARDS", "volumetric_fog_cards", Type::Enum, "replace", nullptr, 99, 0, 18, 0, 0, "replace|keep", 0, -1},
    {"X3M_VOLUMETRIC_FOG_RANGE", "volumetric_fog_range", Type::Enum, "stored", nullptr, 99, 0, 18, 0, 0, "stored|legacy", 0, -1},
    {"X3M_VOLUMETRIC_FOG_STRENGTH", "volumetric_fog_strength", Type::Float, "0.02", nullptr, 99, 1, 18, 0, 0, "", 0, -1},
    {"X3M_VOLUMETRIC_FOG_TIMING", "volumetric_fog_timing", Type::Bool, nullptr, nullptr, 100, 0, 18, 0, 0, "", 1, -1},
    {"X3M_WINDOW_MONITOR_RECT", "window_monitor_rect", Type::Bool, "1", nullptr, 100, 0, 18, 0, 0, "", 0, -1},
    {"X3M_WINDOW_MONITOR_RECT_DEFAULT", "window_monitor_rect_default", Type::Bool, "1", nullptr, 100, 0, 18, 0, 0, "", 3, 229},
    {"X3M_WINDOW_TRACE", "window_trace", Type::Bool, nullptr, nullptr, 100, 0, 18, 0, 0, "", 1, -1},
};
constexpr unsigned alias_count = 0;
constexpr Alias aliases[1] = {{nullptr, 0}}; // none yet
}

namespace x3m::config_default {
constexpr float bloom_source_clamp = 1.0f;
constexpr const char bolt_footprint[] = "3,12";
constexpr const char camera[] = "chase";
constexpr float camera_cut_deg = 20.0f;
constexpr long capture_frames = 8;
constexpr long capture_start = 999999;
constexpr float chase_combat_tightness = 0.0f;
constexpr float chase_distance_scale = 1.05f;
constexpr bool chase_fov_compensate = true;
constexpr const char chase_hud_anchor[] = "forward";
constexpr float chase_offset_y = 0.5f;
constexpr float chase_pitch_down_deg = 0.5f;
constexpr bool chase_scene_fix = false;
constexpr bool chase_view_restore = true;
constexpr bool collide_box_cull = true;
constexpr bool collide_memo = true;
constexpr bool collide_sat_sse2 = true;
constexpr bool crypt_cache = true;
constexpr const char cull_small_parts_projectiles[] = "on";
constexpr float cull_small_parts_px = 4.0000f;
constexpr bool dat_handles = true;
constexpr float emission_source_gain = 2.0f;
constexpr const char fade_rt2_owner[] = "on";
constexpr bool fog_docked = true;
constexpr const char fog_dust_motes[] = "1300,3,128";
constexpr bool fog_handover_coldfill = true;
constexpr bool fog_handover_prefill = true;
constexpr bool fog_handover_step = true;
constexpr const char fog_march_scale[] = "4";
constexpr float fog_motes_max_px = 8.0f;
constexpr float fov = 90.0f;
constexpr bool gz_buffer = true;
constexpr long gz_buffer_kb = 256;
constexpr bool hdr = true;
constexpr bool hdr_bloom = true;
constexpr float hdr_clamp = 0.0f;
constexpr const char hdr_decode[] = "gamma2.2";
constexpr bool hdr_dither = true;
constexpr float hdr_ev = 0.0f;
constexpr float hdr_ev_deadband = 0.25f;
constexpr const char hdr_ev_manual[] = "";
constexpr float hdr_ev_max = 1.3f;
constexpr float hdr_ev_min = -3.0f;
constexpr const char hdr_exposure[] = "auto";
constexpr float hdr_key_pull = 0.25f;
constexpr const char hdr_look[] = "none";
constexpr float hdr_meter_bg = 0.001953125f;
constexpr float hdr_meter_edge_weight = 0.35f;
constexpr const char hdr_tonemap[] = "agx";
constexpr float hdr_white_target = 0.9f;
constexpr float hull_emission_gain = 2.0f;
constexpr const char hull_emissive_widening[] = "4,4";
constexpr float hull_lightmap_gain = 4.0f;
constexpr const char light_map_far_fade[] = "80,220,1";
constexpr const char lod_occlusion[] = "all";
constexpr bool media_cue_cache = true;
constexpr long media_cue_retry_s = 30;
constexpr const char mesh_adjacency[] = "fast";
constexpr float motion_cut_median_px = 1e30f;
constexpr float motion_cut_missing = 1.0f;
constexpr bool motion_jitter = true;
constexpr bool motion_output = true;
constexpr const char motion_rt_mode[] = "lazy";
constexpr bool music_keep = true;
constexpr bool object_lifetime = true;
constexpr bool object_trace = true;
constexpr float original_fill = 0.01f;
constexpr bool ownership = true;
constexpr bool pause_key_only = true;
constexpr const char resource_read[] = "fast";
constexpr const char scene_hook[] = "1";
constexpr float screen_emission_additive = 2.0f;
constexpr float screen_emission_additive_alpha = 0.0f;
constexpr bool shadow_alpha_casters = true;
constexpr float shadow_cascade_adaptive_c0 = 1.5f;
constexpr const char shadow_cascade_drop_order[] = "importance";
constexpr float shadow_cascade_min_footprint = 8.0f;
constexpr const char shadow_cascade_records[] = "1024,1024,2048,4096,4096";
constexpr const char shadow_cascade_sizes[] = "2048,4096,4096,4096,2048";
constexpr const char shadow_cascades[] = "250.0,1500.0,7500.0,37500.0,150000.0";
constexpr bool shadow_caster_retention = true;
constexpr bool shadow_replay_candidates = true;
constexpr bool shadow_replay_depth = true;
constexpr bool shadow_sun_poll = true;
constexpr const char sun_flare_fix[] = "on";
constexpr bool sun_occlusion = true;
constexpr bool sun_occlusion_core_f = true;
constexpr bool sun_shadow_apply = true;
constexpr float sun_shadow_bias_clamp_texels = 20.97152f;
constexpr float sun_shadow_bias_slope_texels = 0.2f;
constexpr float sun_shadow_bias_units = 0.53571875f;
constexpr bool sun_shadow_lane = true;
constexpr bool taa = true;
constexpr const char taa_box_resolution[] = "half";
constexpr const char taa_far_clip[] = "7x7";
constexpr const char taa_far_gate[] = "camera";
constexpr const char taa_far_stabiliser[] = "0.985,0,60,68,0.03,0.25";
constexpr float taa_mip_bias = -0.5f;
constexpr const char taa_motion_weight[] = "0.7,2,8";
constexpr float taa_sharpen = 0.75f;
constexpr const char taa_sky_history[] = "strict";
constexpr float taa_sky_history_exit_px = 0.25f;
constexpr const char taa_thin_region[] = "0.97,1";
constexpr float taa_thin_region_emissive = 1.0f;
constexpr const char taa_thin_vote[] = "on";
constexpr const char taa_unmatched_static[] = "node";
constexpr const char terran_station_lod[] = "size";
constexpr bool voice_dmo_fallback = true;
constexpr bool volumetric_fog = true;
constexpr const char volumetric_fog_cards[] = "replace";
constexpr const char volumetric_fog_range[] = "stored";
constexpr float volumetric_fog_strength = 0.02f;
constexpr bool window_monitor_rect = true;
}
