#!/usr/bin/env python3
"""Build and audit the dust-scene leak fix fixture. Never runs Wine.

The engine's 37 window bytes 0x0041f4b7..0x0041f4db are copyrighted game code
and are not tracked: this script reads them from the installed X3AP.exe
(read-only), checks their SHA-256 and that they are the verified window of
src/proxy/dust_leak_fix_sites.h, and writes the untracked fragment
build/verification/dust-leak-fix/dust_window_inc.h (DLF_WINDOW_ASM, `.byte`
lines). src/proxy/dust_leak_fix.cpp is compiled unchanged with the proxy's
flags plus `-include dust_leak_fix_patch_fixture_shim.h -DX3M_DUST_LEAK_FIX_SHIM`,
which routes its engine_patch read_code/store_pointer/restore calls through the
fixture's pass-through fault seam; src/proxy/engine_patch.cpp (claim, the real
lock cmpxchg8b write) is compiled as is. The executable links at 0x00200000
without ASLR and places the section .x3mdlf at 0x0041f000 (the window at its
own address inside an image section, as in X3AP.exe) and .x3mdlr at
0x00487000 (a jump at the engine's release address 0x00487be0 to the fixture's
stand-in). The audit checks that the seam took, that engine_patch.o carries
`lock cmpxchg8b`, that each of the two sections is one executable read-only
page at its address, that .x3mdlf holds the window bytes at +0x4b7, and that
no other section overlaps either page.
"""
import hashlib
import json
import re
import subprocess
from pathlib import Path
from run_chase_aim_trace import FLAGS
import verify_dust_leak_fix_site as site
ROOT = Path(__file__).resolve().parents[2]
BUILD = ROOT / 'build/verification/dust-leak-fix'
EXE = BUILD / 'dust_leak_fix_patch_fixture.exe'
SHIM = 'verification/probe/dust_leak_fix_patch_fixture_shim.h'
IMAGE_BASE, PAGE, RELEASE_PAGE = 0x200000, 0x41f000, 0x487000
WINDOW_SHA256 = '538370ceb5ea701a536e907f758aeb39f81073d3b4fa91bc6818352ef3b15e7c'


def tool(name, *args):
    return subprocess.run(['i686-w64-mingw32-' + name, *args], capture_output=True, text=True, check=True).stdout


def window_bytes(exe=site.DEFAULT_EXE):
    data = site.common.image_bytes(exe)
    window = site.common.Image(data).read(site.WINDOW_VA, len(site.WINDOW))
    if window is None or window != site.WINDOW:
        raise RuntimeError('the installed executable does not carry the verified window')
    if hashlib.sha256(window).hexdigest() != WINDOW_SHA256:
        raise RuntimeError('the window bytes differ from the pinned SHA-256')
    return window


def render(window):
    lines = ['// Generated by build_dust_leak_fix_patch.py from the installed X3AP.exe (0x0041f4b7..0x0041f4db); untracked, do not edit.',
             '#pragma once', '#define DLF_WINDOW_ASM \\']
    for i in range(0, len(window), 16):
        lines.append('    "    .byte ' + ','.join(f'0x{b:02x}' for b in window[i:i + 16]) + '\\n" \\')
    lines.append('    ""')
    return '\n'.join(lines) + '\n'


def sections():
    headers = tool('objdump', '-h', str(EXE)).splitlines()
    loaded = []
    for i, line in enumerate(headers):
        m = re.match(r'\s*\d+\s+(\S+)\s+([0-9a-f]+)\s+([0-9a-f]+)\s', line)
        if m and i + 1 < len(headers):  # every section: debug sections take image VA space too
            loaded.append((m.group(1), int(m.group(3), 16), int(m.group(2), 16), headers[i + 1]))
    return loaded


def section_bytes(name):
    out = BUILD / (name.strip('.') + '.bin')
    subprocess.run(['i686-w64-mingw32-objcopy', '-O', 'binary', f'--only-section={name}', str(EXE), str(out)], capture_output=True, check=True)
    data = out.read_bytes()
    out.unlink()
    return data


def audit(objects, window):
    module = tool('nm', str(objects['module']))
    seam = [name for name in ('fixture_read_code', 'fixture_store_pointer', 'fixture_restore') if name in module]
    direct = [l.strip() for l in module.splitlines() if re.search(r' U __ZN3x3m12engine_patch(9read_code|13store_pointer|7restore)', l)]
    listing = tool('objdump', '-d', '--no-show-raw-insn', str(objects['patch']))
    cmpxchg8b = len(re.findall(r'lock cmpxchg8b', listing))
    symbols = tool('nm', str(EXE))
    page = re.search(r'^([0-9a-f]+) T _dlf_engine_page$', symbols, re.M)
    release_page = re.search(r'^([0-9a-f]+) T _dlf_release_page$', symbols, re.M)
    loaded = sections()
    own = {s[0]: s for s in loaded if s[0] in ('.x3mdlf', '.x3mdlr')}
    others = [s for s in loaded if s[0] not in own]
    overlap = [s[0] for s in others for start in (PAGE, RELEASE_PAGE) if s[1] < start + 0x1000 and s[1] + s[2] > start]
    code = section_bytes('.x3mdlf') if '.x3mdlf' in own else b''
    release = section_bytes('.x3mdlr') if '.x3mdlr' in own else b''
    record = {'module_calls_seam': seam, 'module_calls_engine_patch_directly': direct, 'engine_patch_lock_cmpxchg8b': cmpxchg8b,
              'engine_page_va': page.group(1) if page else None, 'release_page_va': release_page.group(1) if release_page else None,
              'sections': {name: {'va': f'{s[1]:08x}', 'size': s[2], 'code_readonly': 'CODE' in s[3] and 'READONLY' in s[3]} for name, s in own.items()},
              'window_at_engine_offset': code[site.WINDOW_VA - PAGE:site.WINDOW_VA - PAGE + len(window)] == window,
              'release_jump_at_release_va': release[site.RELEASE_VA - RELEASE_PAGE:site.RELEASE_VA - RELEASE_PAGE + 1] == b'\xe9',
              'window_sha256': WINDOW_SHA256,
              'highest_other_section_end': f'{max(s[1] + s[2] for s in others):08x}' if others else None, 'overlapping_sections': overlap}
    ok = (len(seam) == 3 and not direct and cmpxchg8b >= 1 and record['engine_page_va'] == f'{PAGE:08x}'
          and record['release_page_va'] == f'{RELEASE_PAGE:08x}' and len(own) == 2
          and all(s['size'] == 4096 and s['code_readonly'] for s in record['sections'].values())
          and record['sections']['.x3mdlf']['va'] == f'{PAGE:08x}' and record['sections']['.x3mdlr']['va'] == f'{RELEASE_PAGE:08x}'
          and record['window_at_engine_offset'] and record['release_jump_at_release_va'] and not overlap)
    if not ok:
        raise RuntimeError('fixture build audit failed: ' + json.dumps(record))
    return record


def build():
    BUILD.mkdir(parents=True, exist_ok=True)
    window = window_bytes()
    (BUILD / 'dust_window_inc.h').write_text(render(window))
    objects = {}
    for source, stem, extra in [('verification/probe/dust_leak_fix_patch_fixture.cpp', 'fixture', ['-I', str(BUILD)]),
                                ('src/proxy/dust_leak_fix.cpp', 'module', ['-include', str(ROOT / SHIM), '-DX3M_DUST_LEAK_FIX_SHIM']),
                                ('src/proxy/engine_patch.cpp', 'patch', [])]:
        out = BUILD / (stem + '.o')
        subprocess.run(['i686-w64-mingw32-g++', *FLAGS, *extra, '-c', str(ROOT / source), '-o', str(out)], check=True, cwd=ROOT)
        objects[stem] = out
    subprocess.run(['i686-w64-mingw32-g++', *map(str, objects.values()), '-static', '-static-libgcc', '-static-libstdc++',
                    '-Wl,--strip-debug', f'-Wl,--image-base,{IMAGE_BASE:#010x}', '-Wl,--disable-dynamicbase',
                    f'-Wl,--section-start=.x3mdlf={PAGE:#010x}', f'-Wl,--section-start=.x3mdlr={RELEASE_PAGE:#010x}',
                    '-o', str(EXE)], check=True, cwd=ROOT)
    return {'binary': str(EXE.relative_to(ROOT)), 'toolchain': tool('g++', '--version').splitlines()[0], 'audit': audit(objects, window)}


if __name__ == '__main__':
    print(json.dumps(build(), indent=1))
