#!/usr/bin/env python3
"""Build and audit the small-parts cull CPU fixture. Never runs Wine.

The tracked run131 census rows (verification/fixtures/run131-cull-census-rows.json)
are rendered into a generated include (`run131_rows_inc.h`, build directory
only); the production modules are compiled with their production flags
(cull_census.cpp without SSE/MMX, cull_small_parts.cpp with the ordinary
flags: its stub is emitted bytes, no handler runs inside the pass) and the
census module is audited as build_cull_census.py does.
"""
import json
import subprocess
from pathlib import Path
from run_chase_aim_trace import FLAGS
from build_cull_census import NO_SSE, audit_module
ROOT = Path(__file__).resolve().parents[2]
BUILD = ROOT / 'build/verification/cull-small-parts'
ROWS = ROOT / 'verification/fixtures/run131-cull-census-rows.json'


def render_rows(document):
    """The census rows as a C++ include: one RowData per row plus the frame geometry and the expected classes."""
    lines = ['// Generated by build_cull_small_parts.py from verification/fixtures/run131-cull-census-rows.json; do not edit.',
             '#pragma once', '#include <cstdint>',
             'struct RowData { std::int32_t s, measure, d, radius, thr_1dc, thr_1d8, limit; std::uint32_t flags_in; std::int32_t verdict, draws, lod; };',
             f'static const std::uint32_t kRowsM00Bits = 0x{document["projection_m00_bits"]};',
             f'static const unsigned kRowsWidth = {int(document["width"])}u, kRowsMeasureReference = {int(document["measure_reference"])}u, kRowsViewScale = {int(document["view_scale"])}u;',
             'struct RowsExpected { double px; std::int32_t threshold_s; std::uint32_t nodes, draws, bodies_nodes, bodies_draws; };',
             f'static const std::uint32_t kRowsBodyFlagsMask = 0x{document["body_flags_mask"]}u;',
             'static const RowsExpected kRowsExpected[] = {' + ', '.join(f'{{{float(px)}, {e["threshold_s"]}, {e["nodes"]}u, {e["draws"]}u, {e["bodies_nodes"]}u, {e["bodies_draws"]}u}}' for px, e in sorted(document['expected'].items(), key=lambda kv: float(kv[0]))) + '};',
             f'static const unsigned kRowsExpectedCount = {len(document["expected"])}u;',
             f'static const unsigned kRowCount = {len(document["rows"])}u;',
             'static const RowData kRows[] = {']
    for row in document['rows']:
        s, measure, d, radius, thr_1dc, thr_1d8, limit, flags_in, verdict, draws, lod = row
        lines.append(f'{{{s}, {measure}, {d}, {radius}, {thr_1dc}, {thr_1d8}, {limit}, 0x{flags_in:08x}u, {verdict}, {draws}, {lod}}},')
    lines.append('};')
    return '\n'.join(lines) + '\n'


def build():
    BUILD.mkdir(parents=True, exist_ok=True)
    document = json.loads(ROWS.read_text())
    (BUILD / 'run131_rows_inc.h').write_text(render_rows(document))
    objects = []
    for source, stem, extra in [('verification/probe/cull_small_parts_fixture.cpp', 'fixture', ['-I', str(BUILD)]),
                                ('src/proxy/cull_small_parts.cpp', 'small_parts', []),
                                ('src/proxy/cull_census.cpp', 'census', NO_SSE),
                                ('src/proxy/engine_patch.cpp', 'patch', [])]:
        out = BUILD / (stem + '.o')
        subprocess.run(['i686-w64-mingw32-g++', *FLAGS, *extra, '-c', str(ROOT / source), '-o', str(out)], check=True, cwd=ROOT)
        objects.append(out)
    audit = audit_module(BUILD / 'census.o')
    exe = BUILD / 'cull_small_parts_fixture.exe'
    subprocess.run(['i686-w64-mingw32-g++', *map(str, objects), '-static', '-static-libgcc', '-static-libstdc++', '-o', str(exe)], check=True, cwd=ROOT)
    return {'binary': str(exe), 'rows': len(document['rows']), 'census_module_audit': audit, 'runtime': 'not run'}


if __name__ == '__main__':
    print(json.dumps(build(), indent=2))
