#!/usr/bin/env python3
"""Build and audit the collide-descent-sse2 CPU fixture. Never runs Wine.

The reference is the engine's own code, run in place: the fixture image is linked at the game's base with a section
.engine over the engine's addresses (0x004d0000..0x0060ffff) and copies in the narrow-phase query 0x004e2780 with the descent 0x004e2530, the leaf, the
transform helpers, the separating-axis test 0x004e3280, the float `fabs` helper and reps. No relocation is applied, so
the production module is exercised with its real addresses, including initialize() and the real call site. The bytes
are copyrighted game code and are not tracked: this script reads them from the installed X3AP.exe, checks the hashes
pinned in verify_collide_descent_site.py / verify_collide_sites.py, and writes the untracked fragment
build/verification/collide-descent-sse2/engine_ranges_inc.h.
Audits: the production module's object holds no x87/MMX opcode and both asm routines are the documented sequences.
"""
import hashlib
import json
import re
import subprocess
from pathlib import Path
from run_chase_aim_trace import FLAGS
import verify_collide_descent_site as site
sites = site.sites
ROOT = Path(__file__).resolve().parents[2]
BUILD = ROOT / 'build/verification/collide-descent-sse2'
OBJDUMP = 'i686-w64-mingw32-objdump'
# The fixture image sits at the game's base and owns the section .engine at 0x004d0000..0x0060ffff (the engine's code and
# data addresses); stripped, so that no debug section is assigned addresses in between.
LINK = ('-s', '-Wl,--image-base,0x00400000', '-Wl,--disable-dynamicbase', '-Wl,--section-start=.engine=0x004d0000')
# (va, length): fabs helper; 0x004dfd80 + 0x004dfe60; 0x004e1ff0..0x004e2968 (helpers, leaf, descent, query); the SAT; reps.
RANGES = ((sites.FABS_HELPER_VA, len(sites.FABS_HELPER)), (0x4dfd80, 0x4dfeab - 0x4dfd80), (0x4e1ff0, site.CALLER[1] - 0x4e1ff0),
          (sites.SAT_CALLEE[0], sites.SAT_CALLEE[1] - sites.SAT_CALLEE[0]), (sites.REPS_VA, 4))
THUNK = ['push', 'push', 'push', 'push', 'push', 'push', 'push', 'call', 'add', 'pop', 'pop', 'ret']
LEAF = ['push', 'push', 'push', 'push', 'mov', 'mov', 'mov', 'call', 'pop', 'pop', 'pop', 'pop', 'ret']


def engine_fragment(exe=sites.DEFAULT_EXE):
    data = Path(exe).read_bytes()
    image = site.common.Image(data)
    sat = image.read(*RANGES[3])
    if (hashlib.sha256(data).hexdigest() != site.common.EXPECTED_SHA256 or sites.fnv1a(site.masked_body(image)) != site.DESCENT_FNV1A or site.helpers_fnv(image) != site.HELPERS_FNV1A
            or sites.fnv1a(site.masked_leaf(image)) != site.LEAF_FNV1A or hashlib.sha256(sat).hexdigest() != sites.SAT_CALLEE_SHA256):
        raise RuntimeError('engine bytes do not match the pinned hashes')
    blob, rows = b'', []
    for va, length in RANGES:
        rows.append(f'{{0x{va:08x}u, {len(blob)}u, {length}u}}')
        blob += image.read(va, length)
    lines = ['    ' + ','.join(f'0x{b:02x}' for b in blob[k:k + 32]) + ',' for k in range(0, len(blob), 32)]
    text = ('// Generated by verification/probe/build_collide_descent_sse2.py from the installed X3AP.exe. Untracked: engine bytes.\n'
            'struct FxEngineRange { std::uint32_t va, offset, length; };\n'
            f'static const FxEngineRange fx_engine_ranges[{len(rows)}] = {{' + ', '.join(rows) + '};\n'
            f'static const unsigned char fx_engine_bytes[{len(blob)}] = {{\n' + '\n'.join(lines) + '\n};\n')
    BUILD.mkdir(parents=True, exist_ok=True)
    (BUILD / 'engine_ranges_inc.h').write_text(text)
    return {'ranges': len(rows), 'bytes': len(blob), 'sha256': hashlib.sha256(blob).hexdigest()}


def audit_module(obj):
    listing = subprocess.run([OBJDUMP, '-d', '-Mintel', '--no-show-raw-insn', str(obj)], capture_output=True, text=True, check=True).stdout
    rows = [m.groups() for m in (re.match(r'^\s*[0-9a-f]+:\s+([a-z][a-z0-9]*)\s*(.*)$', line) for line in listing.splitlines()) if m]
    x87 = [m for m, o in rows if re.match(r'^f[a-z0-9]+$', m) or m == 'emms' or re.search(r'\b(st\(\d\)|mm[0-7])\b', o)]
    if x87:
        raise RuntimeError('x87/MMX in the production module: ' + ' '.join(x87[:6]))
    report = {'module_x87_mmx_instructions': 0}
    for symbol, expected in (('_x3m_collide_descent_thunk', THUNK), ('_x3m_collide_descent_leaf', LEAF)):
        block = re.search(rf'<{symbol}>:\n(.*?)(?:\n\n|\Z)', listing, re.S)
        names = [m.group(1) for m in re.finditer(r'^\s*[0-9a-f]+:\s+([a-z][a-z0-9]*)', block.group(1) if block else '', re.M)][:len(expected)]
        if names != expected:
            raise RuntimeError(f'{symbol}: unexpected instruction sequence {names}')
        report[symbol.strip('_') + '_instructions'] = len(names)
    return report


def build():
    engine = engine_fragment()
    objects = []
    for source, stem in [('verification/probe/collide_descent_sse2_fixture.cpp', 'fixture'), ('src/proxy/collide_descent_sse2.cpp', 'module'),
                         ('src/proxy/collide_sat_sse2.cpp', 'sat_module'), ('src/proxy/engine_patch.cpp', 'patch')]:
        out = BUILD / (stem + '.o')
        subprocess.run(['i686-w64-mingw32-g++', *FLAGS, '-I', str(BUILD), '-c', str(ROOT / source), '-o', str(out)], check=True, cwd=ROOT)
        objects.append(out)
    exe = BUILD / 'collide_descent_sse2_fixture.exe'
    subprocess.run(['i686-w64-mingw32-g++', *map(str, objects), '-static', '-static-libgcc', '-static-libstdc++', *LINK, '-o', str(exe)], check=True, cwd=ROOT)
    return {'binary': str(exe), 'engine': engine, 'audit': audit_module(BUILD / 'module.o'), 'runtime': 'not run'}


if __name__ == '__main__':
    print(json.dumps(build(), indent=2))
