#!/usr/bin/env python3
"""Build and audit the collide-sat-sse2 CPU fixture. Never runs Wine.

The fixture needs a byte replica of the engine's separating-axis test
0x004e3280..0x004e38ad. The bytes are copyrighted game code, so they are not
tracked: this script reads them from the installed X3AP.exe, pins them by
SHA-256 (verify_collide_sites.SAT_CALLEE_SHA256), and writes the untracked
fragment build/verification/collide-sat-sse2/sat_replica_inc.h in which only
the 24 rel32 operands of `call 0x0040e710` (the float `fabs` helper, replicated
too) and the nine abs32 operands of `fadd dword [0x00565600]` (reps = 1e-6f)
are symbolic. Audits: the production module's object holds no x87/MMX opcode,
and the thunk is exactly the documented instruction sequence.
"""
import hashlib
import json
import re
import struct
import subprocess
from pathlib import Path
from run_chase_aim_trace import FLAGS
import verify_collide_sites as sites
ROOT = Path(__file__).resolve().parents[2]
BUILD = ROOT / 'build/verification/collide-sat-sse2'
OBJDUMP = 'i686-w64-mingw32-objdump'
THUNK = (['push', 'push', 'push', 'stmxcsr', 'mov', 'and', 'cmp', 'jne', 'push', 'push', 'push', 'push', 'call', 'lea', 'pop', 'pop', 'ret']      # default MXCSR control bits: no ldmxcsr
         + ['ldmxcsr', 'push', 'push', 'push', 'push', 'call', 'lea', 'ldmxcsr', 'pop', 'pop', 'pop', 'ret'])                                    # any other value: bracketed


def replica_fragment(exe=sites.DEFAULT_EXE):
    image = sites.common.Image(Path(exe).read_bytes())
    lo, hi = sites.SAT_CALLEE
    body = image.read(lo, hi - lo)
    if body is None or hashlib.sha256(body).hexdigest() != sites.SAT_CALLEE_SHA256:
        raise RuntimeError('0x004e3280 body does not match the pinned hash')
    helper = image.read(sites.FABS_HELPER_VA, len(sites.FABS_HELPER))
    if helper != sites.FABS_HELPER:
        raise RuntimeError('fabs helper bytes differ')
    listing = subprocess.run([OBJDUMP, '-d', '-Mintel', '--insn-width=16', f'--start-address={lo:#x}', f'--stop-address={hi:#x}', str(exe)],
                             check=True, capture_output=True, text=True, timeout=60).stdout
    calls, loads = [], []
    for i in sites.common.parse_objdump(listing, lo, hi):   # relocations only at decoded instruction boundaries
        if i.mnemonic == 'call' and sites.common._is_direct_control(i) == sites.FABS_HELPER_VA and len(i.raw) == 5:
            calls.append(i.va - lo + 1)
        elif i.raw[:2] == b'\xd8\x05' and len(i.raw) == 6 and struct.unpack('<I', i.raw[2:])[0] == sites.REPS_VA:
            loads.append(i.va - lo + 2)
    if len(calls) != 24 or len(loads) != 9:
        raise RuntimeError(f'unexpected relocation census: {len(calls)} calls, {len(loads)} reps loads')
    fields = {at: 'call' for at in calls} | {at: 'reps' for at in loads}
    lines, run, at = [], [], 0

    def flush():
        if run:
            lines.append('    .byte ' + ','.join(f'0x{b:02x}' for b in run))
            run.clear()
    while at < len(body):
        if at in fields:
            flush()
            lines.append('    .long _fx_fabs - (. + 4)' if fields[at] == 'call' else '    .long _fx_reps')
            at += 4
        else:
            run.append(body[at])
            at += 1
            if len(run) == 32:
                flush()
    flush()
    table = lambda name, values: f'static const unsigned short {name}[{len(values)}] = {{' + ', '.join(map(str, values)) + '};'
    text = ('// Generated by verification/probe/build_collide_sat_sse2.py from the installed X3AP.exe. Untracked: engine bytes.\n'
            'asm(R"(\n    .intel_syntax noprefix\n    .text\n    .p2align 4\n    .globl _fx_fabs\n_fx_fabs:\n    .byte '
            + ','.join(f'0x{b:02x}' for b in helper) + '\n    .p2align 4\n    .globl _fx_sat_replica\n_fx_sat_replica:\n' + '\n'.join(lines)
            + '\n    .att_syntax\n)");\n' + table('fx_replica_call_fields', calls) + '\n' + table('fx_replica_reps_fields', loads) + '\n')
    BUILD.mkdir(parents=True, exist_ok=True)
    (BUILD / 'sat_replica_inc.h').write_text(text)
    return {'bytes': len(body), 'sha256': sites.SAT_CALLEE_SHA256, 'rel32_calls': len(calls), 'abs32_reps': len(loads)}


def audit_module(obj):
    listing = subprocess.run([OBJDUMP, '-d', '-Mintel', '--no-show-raw-insn', str(obj)], capture_output=True, text=True, check=True).stdout
    rows = [m.groups() for m in (re.match(r'^\s*[0-9a-f]+:\s+([a-z][a-z0-9]*)\s*(.*)$', line) for line in listing.splitlines()) if m]
    x87 = [m for m, o in rows if re.match(r'^f[a-z0-9]+$', m) or m == 'emms' or re.search(r'\b(st\(\d\)|mm[0-7])\b', o)]
    if x87:
        raise RuntimeError('x87/MMX in the production module: ' + ' '.join(x87[:6]))
    thunk = re.search(r'<_x3m_collide_sat_thunk>:\n(.*?)(?:\n\n|\Z)', listing, re.S)
    names = [m.group(1) for m in re.finditer(r'^\s*[0-9a-f]+:\s+([a-z][a-z0-9]*)', thunk.group(1) if thunk else '', re.M)]
    names = names[:len(THUNK)]
    if names != THUNK:
        raise RuntimeError(f'thunk: unexpected instruction sequence {names}')
    return {'module_x87_mmx_instructions': 0, 'thunk_sequence_exact': True, 'thunk_instructions': len(names)}


def build():
    replica = replica_fragment()
    objects = []
    for source, stem in [('verification/probe/collide_sat_sse2_fixture.cpp', 'fixture'), ('src/proxy/collide_sat_sse2.cpp', 'module'), ('src/proxy/engine_patch.cpp', 'patch')]:
        out = BUILD / (stem + '.o')
        subprocess.run(['i686-w64-mingw32-g++', *FLAGS, '-I', str(BUILD), '-c', str(ROOT / source), '-o', str(out)], check=True, cwd=ROOT)
        objects.append(out)
    exe = BUILD / 'collide_sat_sse2_fixture.exe'
    subprocess.run(['i686-w64-mingw32-g++', *map(str, objects), '-static', '-static-libgcc', '-static-libstdc++', '-o', str(exe)], check=True, cwd=ROOT)
    return {'binary': str(exe), 'replica': replica, 'audit': audit_module(BUILD / 'module.o'), 'runtime': 'not run'}


if __name__ == '__main__':
    print(json.dumps(build(), indent=2))
