#!/usr/bin/env python3
"""Build and audit the lens-flare collector fix fixture. Never runs Wine.

The engine's gate 0x0047e315..0x0047e401 is copyrighted game code and is not
tracked: this script reads it from the installed X3AP.exe (read-only), checks
its SHA-256 and that it carries the verified window of
src/proxy/sun_flare_fix_sites.h, and writes the untracked fragment
build/verification/sun-flare-fix/sun_gate_inc.h (SUN_GATE_ASM, `.byte` lines).
src/proxy/sun_flare_fix.cpp is compiled unchanged with the proxy's flags plus
`-include sun_flare_fix_fixture_shim.h -DX3M_SUN_FLARE_FIX_SHIM`, which routes
its engine_patch read_code/store_pointer/restore calls through the fixture's
pass-through fault seam; src/proxy/engine_patch.cpp (claim, the real lock
cmpxchg8b write) is compiled as is. The executable links at 0x00300000
without ASLR and places the section .x3msfc at 0x0047e000, so the gate runs at
its own addresses inside an image section, as in X3AP.exe. The audit checks
that the seam took, that engine_patch.o carries `lock cmpxchg8b`, that .x3msfc
is one executable read-only page at 0x0047e000 holding the gate bytes at
+0x315, and that no other section overlaps it.
"""
import hashlib
import json
import re
import subprocess
from pathlib import Path
from run_chase_aim_trace import FLAGS
import verify_sun_flare_site as site
ROOT = Path(__file__).resolve().parents[2]
BUILD = ROOT / 'build/verification/sun-flare-fix'
EXE = BUILD / 'sun_flare_fix_fixture.exe'
SHIM = 'verification/probe/sun_flare_fix_fixture_shim.h'
IMAGE_BASE, PAGE = 0x300000, 0x47e000
GATE = (site.GATE_VA, site.GATE_END_VA)
GATE_SHA256 = '132c55c6872e61d7b801bd5c3dc37885892540f44ede9536070b19357b6b8acd'


def tool(name, *args):
    return subprocess.run(['i686-w64-mingw32-' + name, *args], capture_output=True, text=True, check=True).stdout


def gate_bytes(exe=site.DEFAULT_EXE):
    data = site.common.image_bytes(exe)
    gate = site.common.Image(data).read(GATE[0], GATE[1] - GATE[0])
    if gate is None or hashlib.sha256(gate).hexdigest() != GATE_SHA256:
        raise RuntimeError('the installed gate bytes differ from the pinned SHA-256')
    if gate[site.WINDOW_VA - GATE[0]:][:len(site.WINDOW)] != site.WINDOW:
        raise RuntimeError('the gate does not carry the verified window')
    return gate


def render(gate):
    lines = ['// Generated by build_sun_flare_fix.py from the installed X3AP.exe (0x0047e315..0x0047e401); untracked, do not edit.',
             '#pragma once', '#define SUN_GATE_ASM \\']
    for i in range(0, len(gate), 16):
        lines.append('    "    .byte ' + ','.join(f'0x{b:02x}' for b in gate[i:i + 16]) + '\\n" \\')
    lines.append('    ""')
    return '\n'.join(lines) + '\n'


def audit(objects, gate):
    module = tool('nm', str(objects['module']))
    seam = [name for name in ('fixture_read_code', 'fixture_store_pointer', 'fixture_restore') if name in module]
    direct = [l.strip() for l in module.splitlines() if re.search(r' U __ZN3x3m12engine_patch(9read_code|13store_pointer|7restore)', l)]
    listing = tool('objdump', '-d', '--no-show-raw-insn', str(objects['patch']))
    cmpxchg8b = len(re.findall(r'lock cmpxchg8b', listing))
    symbols = tool('nm', str(EXE))
    page = re.search(r'^([0-9a-f]+) T _sun_engine_page$', symbols, re.M)
    headers = tool('objdump', '-h', str(EXE)).splitlines()
    loaded = []
    for i, line in enumerate(headers):
        m = re.match(r'\s*\d+\s+(\S+)\s+([0-9a-f]+)\s+([0-9a-f]+)\s', line)
        if m and i + 1 < len(headers):  # every section: debug sections take image VA space too
            loaded.append((m.group(1), int(m.group(3), 16), int(m.group(2), 16), headers[i + 1]))
    code = [s for s in loaded if s[0] == '.x3msfc']
    others = [s for s in loaded if s[0] != '.x3msfc']
    overlap = [s[0] for s in others if s[1] < PAGE + 0x1000 and s[1] + s[2] > PAGE]
    subprocess.run(['i686-w64-mingw32-objcopy', '-O', 'binary', '--only-section=.x3msfc', str(EXE), str(BUILD / 'x3msfc.bin')],
                         capture_output=True, check=True)
    section = (BUILD / 'x3msfc.bin').read_bytes()
    (BUILD / 'x3msfc.bin').unlink()
    record = {'module_calls_seam': seam, 'module_calls_engine_patch_directly': direct, 'engine_patch_lock_cmpxchg8b': cmpxchg8b,
              'engine_page_va': page.group(1) if page else None,
              'x3msfc': {'va': f'{code[0][1]:08x}', 'size': code[0][2], 'code_readonly': 'CODE' in code[0][3] and 'READONLY' in code[0][3]} if code else None,
              'gate_at_engine_offset': section[GATE[0] - PAGE:GATE[1] - PAGE] == gate, 'gate_sha256': GATE_SHA256,
              'highest_other_section_end': f'{max(s[1] + s[2] for s in others):08x}' if others else None, 'overlapping_sections': overlap}
    if (len(seam) != 3 or direct or cmpxchg8b < 1 or record['engine_page_va'] != f'{PAGE:08x}' or not code or code[0][2] != 4096
            or not record['x3msfc']['code_readonly'] or not record['gate_at_engine_offset'] or overlap):
        raise RuntimeError('fixture build audit failed: ' + json.dumps(record))
    return record


def build():
    BUILD.mkdir(parents=True, exist_ok=True)
    gate = gate_bytes()
    (BUILD / 'sun_gate_inc.h').write_text(render(gate))
    objects = {}
    for source, stem, extra in [('verification/probe/sun_flare_fix_fixture.cpp', 'fixture', ['-I', str(BUILD)]),
                                ('src/proxy/sun_flare_fix.cpp', 'module', ['-include', str(ROOT / SHIM), '-DX3M_SUN_FLARE_FIX_SHIM']),
                                ('src/proxy/engine_patch.cpp', 'patch', [])]:
        out = BUILD / (stem + '.o')
        subprocess.run(['i686-w64-mingw32-g++', *FLAGS, *extra, '-c', str(ROOT / source), '-o', str(out)], check=True, cwd=ROOT)
        objects[stem] = out
    subprocess.run(['i686-w64-mingw32-g++', *map(str, objects.values()), '-static', '-static-libgcc', '-static-libstdc++',
                    '-Wl,--strip-debug', f'-Wl,--image-base,{IMAGE_BASE:#010x}', '-Wl,--disable-dynamicbase',
                    f'-Wl,--section-start=.x3msfc={PAGE:#010x}', '-o', str(EXE)], check=True, cwd=ROOT)
    return {'binary': str(EXE.relative_to(ROOT)), 'toolchain': tool('g++', '--version').splitlines()[0], 'audit': audit(objects, gate)}


if __name__ == '__main__':
    print(json.dumps(build(), indent=1))
