#!/usr/bin/env python3
"""Build and audit the collide-memo CPU fixture. Never runs Wine.

The reference is the engine's own code, run in place: the fixture image is linked at the game's base with a zero-filled
section .engine over 0x00400000..0x0066ffff (the image itself sits below, at 0x00340000) and copies in the mesh-pair query 0x0047f1b0 with everything below it
(0x004e29f0, the query 0x004e2780, the descent, the real leaf and triangle tests, the SAT, the transform helpers, the
ftol helper and the float constants). No relocation is applied, so the production module is exercised with its real
addresses, including initialize(), the real call site and the real globals. The bytes are copyrighted game code and
are not tracked: this script reads them from the installed X3AP.exe, checks the hashes pinned in
verify_collide_memo_site.py, and writes the untracked fragment build/verification/collide-memo/engine_ranges_inc.h.
Audits: the production module's object holds no x87/MMX opcode, the three routines the engine reaches hold no floating-point arithmetic, and the thunk
is the documented instruction sequence.
"""
import hashlib
import json
import re
import subprocess
from pathlib import Path
from run_chase_aim_trace import FLAGS
import verify_collide_memo_site as site
sites = site.sites
ROOT = Path(__file__).resolve().parents[2]
BUILD = ROOT / 'build/verification/collide-memo'
OBJDUMP = 'i686-w64-mingw32-objdump'
# Stripped, so that no debug section is assigned addresses between the image's own sections and .engine.
LINK = ('-s', '-Wl,--image-base,0x00340000', '-Wl,--disable-dynamicbase', '-Wl,--section-start=.engine=0x00400000')
# (va, length): fabs helper; the caller; vector helpers; 0x004e1ff0..0x004e38ad (helpers, leaf, descent, query, 0x004e29f0, triangle test, SAT); ftol; constants.
RANGES = ((sites.FABS_HELPER_VA, len(sites.FABS_HELPER)), (site.CALLER[0], site.CALLER[1] - site.CALLER[0]), (0x4dfd80, 0x4dfee3 - 0x4dfd80), (0x4e1ff0, 0x4e38ae - 0x4e1ff0),
          (site.FTOL_VA, 0x52b67b - site.FTOL_VA), (0x5654e0, 4), (0x565600, 12))
THUNK = ['push', 'push', 'lea', 'push', 'push', 'push', 'call', 'add', 'cmp', 'je', 'cmp', 'pop', 'pop', 'je', 'pop', 'call', 'push', 'push', 'push', 'call', 'pop', 'pop', 'pop',
         'jmp', 'add', 'xor', 'ret', 'jmp']
# Arithmetic, conversion, compare and control: plain XMM moves (struct copies) are not floating-point operations and read no MXCSR.
FLOAT_RE = re.compile(r'^(f[a-z0-9]+|emms|(add|sub|mul|div|sqrt|max|min|cmp|and|andn|or|xor|shuf|unpck[lh])[sp][sd]|cvt\w+|u?comis[sd]|stmxcsr|ldmxcsr)$')


def engine_fragment(exe=sites.DEFAULT_EXE):
    data = Path(exe).read_bytes()
    image = site.common.Image(data)
    if hashlib.sha256(data).hexdigest() != site.common.EXPECTED_SHA256 or site.body_hashes(image) != site.HASHES:
        raise RuntimeError('engine bytes do not match the pinned hashes')
    blob, rows = b'', []
    for va, length in RANGES:
        rows.append(f'{{0x{va:08x}u, {len(blob)}u, {length}u}}')
        blob += image.read(va, length)
    lines = ['    ' + ','.join(f'0x{b:02x}' for b in blob[k:k + 32]) + ',' for k in range(0, len(blob), 32)]
    text = ('// Generated by verification/probe/build_collide_memo.py from the installed X3AP.exe. Untracked: engine bytes.\n'
            'struct FxEngineRange { std::uint32_t va, offset, length; };\n'
            f'static const FxEngineRange fx_engine_ranges[{len(rows)}] = {{' + ', '.join(rows) + '};\n'
            f'static const unsigned char fx_engine_bytes[{len(blob)}] = {{\n' + '\n'.join(lines) + '\n};\n')
    BUILD.mkdir(parents=True, exist_ok=True)
    (BUILD / 'engine_ranges_inc.h').write_text(text)
    return {'ranges': len(rows), 'bytes': len(blob), 'sha256': hashlib.sha256(blob).hexdigest()}


def audit_module(obj):
    listing = subprocess.run([OBJDUMP, '-d', '-Mintel', '--no-show-raw-insn', str(obj)], capture_output=True, text=True, check=True).stdout
    rows = [m.groups() for m in (re.match(r'^\s*[0-9a-f]+:\s+([a-z][a-z0-9]*)\s*(.*)$', line) for line in listing.splitlines()) if m]
    x87 = [m for m, o in rows if re.match(r'^f[a-z0-9]+$', m) or m == 'emms' or re.search(r'\b(st\(\d\)|mm[0-7])\b', o)]
    if x87:
        raise RuntimeError('x87/MMX in the production module: ' + ' '.join(x87[:6]))
    report = {'module_x87_mmx_instructions': 0}
    # The three routines the engine reaches: no floating-point instruction of any kind (the key is compared as words).
    for symbol in ('_x3m_collide_memo_thunk', '_x3m_collide_memo_lookup', '_x3m_collide_memo_store'):
        block = re.search(rf'<{symbol}>:\n(.*?)(?:\n\n|\Z)', listing, re.S)
        names = [m.group(1) for m in re.finditer(r'^\s*[0-9a-f]+:\s+([a-z][a-z0-9]*)', block.group(1) if block else '', re.M)]
        floating = [n for n in names if FLOAT_RE.match(n)]
        if not names or floating:
            raise RuntimeError(f'{symbol}: floating-point instructions {floating[:6]}')
        if symbol == '_x3m_collide_memo_thunk' and names[:len(THUNK)] != THUNK:
            raise RuntimeError(f'thunk: unexpected instruction sequence {names}')
        report[symbol.strip('_') + '_instructions'] = len(names) if symbol != '_x3m_collide_memo_thunk' else len(THUNK)
    return report


def build():
    engine = engine_fragment()
    objects = []
    for source, stem in [('verification/probe/collide_memo_fixture.cpp', 'fixture'), ('src/proxy/collide_memo.cpp', 'module'), ('src/proxy/collide_sat_sse2.cpp', 'sat_module'),
                         ('src/proxy/engine_patch.cpp', 'patch')]:
        out = BUILD / (stem + '.o')
        subprocess.run(['i686-w64-mingw32-g++', *FLAGS, '-I', str(BUILD), '-c', str(ROOT / source), '-o', str(out)], check=True, cwd=ROOT)
        objects.append(out)
    exe = BUILD / 'collide_memo_fixture.exe'
    subprocess.run(['i686-w64-mingw32-g++', *map(str, objects), '-static', '-static-libgcc', '-static-libstdc++', *LINK, '-o', str(exe)], check=True, cwd=ROOT)
    return {'binary': str(exe), 'engine': engine, 'audit': audit_module(BUILD / 'module.o'), 'runtime': 'not run'}


if __name__ == '__main__':
    print(json.dumps(build(), indent=2))
