#!/usr/bin/env python3
"""Prepare (never launch) X3: Albion Prelude for MetalSharp's Sharp Library.

Writes, per route, under ~/.metalsharp/x3m/<route>/:
  x3m-launch.exe   32-bit wrapper (tools/metalsharp/x3m_launch.c) registered as the game exe
  x3m-launch.env   the launcher's dry-run environment (X3M_* and GST_* variables)
  x3m-launch.cfg   dir=/exe=/args= for the wrapper
  x3m-launch.cmd   the same as a batch file for a manual `wine cmd /c` start (not used by MetalSharp)
and registers two entries in ~/.metalsharp/sharp-library/library.json (backup
library.json.pre-x3m written once). Nothing is written into the CrossOver bottle.

  python3 tools/metalsharp/prepare_metalsharp.py            prepare
  python3 tools/metalsharp/prepare_metalsharp.py --check    verify only (no writes)
  python3 tools/metalsharp/prepare_metalsharp.py --remove   remove the two entries and the x3m directory
"""
import json, os, shutil, subprocess, sys, time

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
HOME = os.path.expanduser("~")
MS = os.path.join(HOME, ".metalsharp")
X3M = os.path.join(MS, "x3m")
LIB = os.path.join(MS, "sharp-library", "library.json")
GAME_DIR = os.path.join(HOME, "Library/Application Support/CrossOver/Bottles/X3/drive_c/X3")
GAME_EXE = "X3AP.exe"
GAME_ARGS = "-noabout -skipintro -runinbg"
ROUTES = [("dxmt32", "dxmt_32", "X3AP x3m proxy [DXMT(32)]", "sharp_1790400000001"),
          ("d3d9", "d3d9", "X3AP x3m proxy [D3D9]", "sharp_1790400000002")]
CC = "/opt/homebrew/bin/i686-w64-mingw32-gcc"
DRY_RUN = [sys.executable, os.path.join(REPO, "tools/manage.py"), "launch", "--dry-run", "--bottle", "X3", "--direct", "--debug", "--perf"]
CMD_SPECIAL = set('&|<>^%!"')


def win_path(unix_path):
    return "Z:" + unix_path.replace("/", "\\")


def dry_run_env():
    out = subprocess.run(DRY_RUN, cwd=REPO, capture_output=True, text=True, check=True).stdout
    data = json.loads(out[out.index("{"):])
    assert data["command"][-4:] == [os.path.join(GAME_DIR, GAME_EXE), "-noabout", "-skipintro", "-runinbg"], data["command"]
    assert data["overrides"] == "d3d9=n,b", data["overrides"]
    return data["env"]


def write_route(route_dir, env):
    os.makedirs(route_dir, exist_ok=True)
    keys = sorted(env)
    with open(os.path.join(route_dir, "x3m-launch.env"), "w") as f:
        f.write("# generated by tools/metalsharp/prepare_metalsharp.py from `manage.py launch --dry-run --bottle X3 --direct --telemetry --camera-log 1`\n")
        for k in keys:
            assert "\n" not in env[k] and "=" not in k
            f.write(f"{k}={env[k]}\n")
    with open(os.path.join(route_dir, "x3m-launch.cfg"), "w") as f:
        f.write(f"dir={win_path(GAME_DIR)}\nexe={GAME_EXE}\nargs={GAME_ARGS}\n")
    unsafe = [k for k in keys if CMD_SPECIAL & set(env[k])]
    with open(os.path.join(route_dir, "x3m-launch.cmd"), "w", newline="\r\n") as f:
        f.write("@echo off\r\nrem generated by tools/metalsharp/prepare_metalsharp.py; manual alternative to x3m-launch.exe\r\n")
        for k in keys:
            f.write(f'set "{k}={env[k]}"\r\n')
        f.write('if defined WINEDLLOVERRIDES (set "WINEDLLOVERRIDES=%WINEDLLOVERRIDES%;d3d9=n,b") else (set "WINEDLLOVERRIDES=d3d9=n,b")\r\n')
        f.write(f'cd /d "{win_path(GAME_DIR)}"\r\n')
        f.write(f'start "" /wait "{GAME_EXE}" {GAME_ARGS}\r\n')
    return unsafe


def build_exe(route_dir):
    src = os.path.join(REPO, "tools/metalsharp/x3m_launch.c")
    exe = os.path.join(route_dir, "x3m-launch.exe")
    subprocess.run([CC, "-O2", "-Wall", "-Wno-format-truncation", "-mwindows", "-o", exe, src], check=True)
    return exe


def register(entries):
    lib = json.load(open(LIB))
    backup = LIB + ".pre-x3m"
    if not os.path.exists(backup):
        shutil.copy2(LIB, backup)
    ids = {e["id"] for e in entries}
    lib = [e for e in lib if e["id"] not in ids] + entries
    tmp = LIB + ".tmp"
    with open(tmp, "w") as f:
        json.dump(lib, f, separators=(",", ":"))
    os.replace(tmp, LIB)
    return len(lib)


def entry(route_id, engine, name, sharp_id):
    exe = os.path.join(X3M, route_id, "x3m-launch.exe")
    return {"id": sharp_id, "name": name, "exe_path": exe, "install_dir": exe, "cover": None,
            "cover_position_x": 50, "cover_position_y": 50, "engine": engine, "launch_args": [],
            "user_launch_args": [], "bottle_id": None, "installed_at": int(time.time()), "size_bytes": 0}


def check():
    ok = True
    lib = json.load(open(LIB))
    for route_id, engine, name, sharp_id in ROUTES:
        d = os.path.join(X3M, route_id)
        for fn in ("x3m-launch.exe", "x3m-launch.env", "x3m-launch.cfg", "x3m-launch.cmd"):
            p = os.path.join(d, fn)
            if not os.path.exists(p):
                print("MISSING", p); ok = False
        exe = os.path.join(d, "x3m-launch.exe")
        if os.path.exists(exe):
            head = open(exe, "rb").read(0x200)
            pe = int.from_bytes(head[0x3c:0x40], "little")
            machine = int.from_bytes(head[pe + 4:pe + 6], "little")
            print(f"{route_id}: exe machine 0x{machine:x} ({'i386' if machine == 0x14c else 'NOT i386'}) size {os.path.getsize(exe)}")
            ok &= machine == 0x14c
        envp = os.path.join(d, "x3m-launch.env")
        if os.path.exists(envp):
            lines = [l for l in open(envp) if l.strip() and not l.startswith("#")]
            print(f"{route_id}: env {len(lines)} vars, {sum(l.startswith('X3M_') for l in lines)} X3M_*")
        e = [x for x in lib if x["id"] == sharp_id]
        print(f"{route_id}: library entry {'present' if e else 'MISSING'}: engine={e[0]['engine'] if e else None} exe_path={e[0]['exe_path'] if e else None}")
        ok &= bool(e) and e[0]["engine"] == engine and e[0]["exe_path"] == exe
    dll = os.path.join(GAME_DIR, "d3d9.dll")
    sha = subprocess.run(["shasum", "-a", "256", dll], capture_output=True, text=True).stdout.split()[0]
    print("game d3d9.dll sha256", sha)
    print("OK" if ok else "FAIL")
    return ok


def main():
    if "--check" in sys.argv:
        sys.exit(0 if check() else 1)
    if "--remove" in sys.argv:
        ids = {r[3] for r in ROUTES}
        lib = [e for e in json.load(open(LIB)) if e["id"] not in ids]
        json.dump(lib, open(LIB, "w"), separators=(",", ":"))
        shutil.rmtree(X3M, ignore_errors=True)
        print("removed entries and", X3M)
        return
    env = dry_run_env()
    print(f"dry-run env: {len(env)} variables")
    entries = []
    for route_id, engine, name, sharp_id in ROUTES:
        d = os.path.join(X3M, route_id)
        unsafe = write_route(d, env)
        if unsafe:
            print(f"{route_id}: cmd values with cmd-special characters (quoted with set \"K=V\"): {unsafe}")
        build_exe(d)
        entries.append(entry(route_id, engine, name, sharp_id))
        print(f"{route_id}: wrote {d}")
    n = register(entries)
    print(f"library.json now has {n} entries; backup at {LIB}.pre-x3m")
    check()


if __name__ == "__main__":
    main()
