#!/usr/bin/env python3
"""Author the packed screen policy's two ps_3_0 programs as generated fragments.

The programs are the qualified prototype's helpers (`screen_ps(0)` plane
initialization and `screen_ps(2)` enhanced C assembly in
verification/probe/linear_emission_sm1_packed_fixture.cpp, ps_2_0) ported to
ps_3_0 so that they pair with the proxy's vs_3_0 quad program: only the version
token and the input declaration/register (t0 -> v0 with a TEXCOORD0 usage)
differ; every arithmetic, sampler and constant token is the prototype's.
Outputs src/renderer/linear_screen_plane_init_inc.h and
src/renderer/linear_screen_composite_inc.h. --check compares without writing.
No compiler, D3D device or Wine is involved.
"""
import argparse
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TARGETS = {'plane_init': (0, ROOT / 'src/renderer/linear_screen_plane_init_inc.h'),
           'composite': (2, ROOT / 'src/renderer/linear_screen_composite_inc.h')}


def reg(t, i):
    return 0x80000000 | ((t & 7) << 28) | ((t & 24) << 8) | i


def dst(t, i, mask=15, pp=False):
    return reg(t, i) | (mask << 16) | (0x200000 if pp else 0)


def src(t, i, sw=0xe4):
    return reg(t, i) | (sw << 16)


def ins(w, op, args):
    w.append(op | (len(args) << 24))
    w.extend(args)


def f32(x):
    return struct.unpack('<f', struct.pack('<f', x))[0]


def literal(w, regno, a, b, c, d):
    ins(w, 81, [dst(2, regno), *struct.unpack('<4I', struct.pack('<4f', a, b, c, d))])


def screen_ps(kind, ps3):
    """kind 0: plane/M.alpha initialization; 2: enhanced C assembly.

    ps3=False reproduces the prototype's ps_2_0 words exactly (host test oracle).
    """
    w = [0xffff0300 if ps3 else 0xffff0200]
    samples = 1 if kind == 0 else 5
    if ps3:
        ins(w, 31, [0x80000005, dst(1, 0, 3)])  # dcl_texcoord0 v0.xy
        coord = src(1, 0)
    else:
        ins(w, 31, [0x80000000, dst(3, 0, 3)])  # dcl t0.xy
        coord = src(3, 0)
    for i in range(samples):
        ins(w, 31, [0x90000000, dst(10, i)])
    literal(w, 0, 0, f32(f32(1) / f32(2.2)) if kind else 2.2, 1e-22 if kind else 1e-10, 1)
    for i in range(samples):
        ins(w, 66, [dst(0, i), coord, src(10, i)])
    if kind == 0:
        ins(w, 1, [dst(8, 0), src(0, 0)])
        for c in range(3):
            ins(w, 1, [dst(0, 1, 1), src(0, 0, c * 0x55)])
            ins(w, 11, [dst(0, 1, 2), src(0, 1, 0), src(2, 0, 0xaa)])
            ins(w, 32, [dst(0, 1, 2), src(0, 1, 0x55), src(2, 0, 0x55)])
            ins(w, 1, [dst(0, 1, 12), src(2, 0, 0)])
            ins(w, 1, [dst(8, c + 1), src(0, 1)])
    else:
        output = 5
        for c in range(3):
            ins(w, 11, [dst(0, 6, 1), src(0, c, 0x55), src(2, 0, 0)])
            ins(w, 11, [dst(0, 6, 2), src(0, 6, 0), src(2, 0, 0xaa)])
            ins(w, 32, [dst(0, 6, 2), src(0, 6, 0x55), src(2, 0, 0x55)])
            ins(w, 88, [dst(0, 6, 2), src(0, 6, 0) | 0x1000000, src(2, 0, 0), src(0, 6, 0x55)])
            ins(w, 35, [dst(0, 6, 4), src(0, c, 0xaa)])
            ins(w, 88, [dst(0, output, 1 << c), src(0, 6, 0xaa) | 0x1000000, src(0, 4, c * 0x55), src(0, 6, 0x55)])
        ins(w, 1, [dst(0, output, 8), src(0, 3, 0xff)])
        ins(w, 1, [dst(8, 0), src(0, output)])
    w.append(0xffff)
    return w


def render(name, kind):
    words = screen_ps(kind, True)
    lines = ['// Generated by tools/shaders/generate_screen_emission_programs.py. Do not edit.',
             f'// ps_3_0 port of the packed prototype helper screen_ps({kind}) ({name}); {len(words)} DWORDs.']
    for i in range(0, len(words), 6):
        lines.append('    ' + ', '.join(f'0x{x:08x}u' for x in words[i:i + 6]) + ',')
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = 0
    for name, (kind, path) in TARGETS.items():
        text = render(name, kind)
        if args.check:
            if not path.is_file() or path.read_text() != text:
                print(f'stale: {path}')
                stale += 1
        else:
            path.write_text(text)
            print(f'{path}: {len(screen_ps(kind, True))} DWORDs')
    return 1 if stale else 0


if __name__ == '__main__':
    sys.exit(main())
