#!/usr/bin/env python3
"""Generate the mechanical normal-D3D9 forwarding ABI from a MinGW SDK header.

Ownership rules remain handwritten in src/ownership/d3d9_ownership.cpp. Generation
recognizes all interface inputs/outputs; no COM output is a plain passthrough.
The output is checked in, so building production does not require this script.
"""
import argparse
from pathlib import Path
import re
import subprocess

KINDS = {
    "IDirect3D9": "Factory", "IDirect3DDevice9": "Device",
    "IDirect3DTexture9": "Texture", "IDirect3DCubeTexture9": "CubeTexture",
    "IDirect3DVolumeTexture9": "VolumeTexture", "IDirect3DSurface9": "Surface",
    "IDirect3DVolume9": "Volume", "IDirect3DVertexBuffer9": "VertexBuffer",
    "IDirect3DIndexBuffer9": "IndexBuffer", "IDirect3DVertexDeclaration9": "VertexDeclaration",
    "IDirect3DVertexShader9": "VertexShader", "IDirect3DPixelShader9": "PixelShader",
    "IDirect3DStateBlock9": "StateBlock", "IDirect3DQuery9": "Query",
    "IDirect3DSwapChain9": "SwapChain",
}


def parameters(raw):
    raw = re.sub(r"^THIS_?\s*", "", raw.strip())
    if not raw:
        return []
    result = []
    for index, value in enumerate(raw.split(",")):
        value = re.sub(r"\bstruct\s+", "", " ".join(value.split()))
        match = re.search(r"([A-Za-z_]\w*)$", value)
        # A single typedef name, or a parameter ending '*', is unnamed.
        if match and match.start() > 0:
            name = match.group(1)
            typ = value[:match.start()].strip()
        else:
            name, typ = f"arg{index}", value
        result.append((typ, name))
    return result


def parse(header):
    result = {}
    for interface in KINDS:
        block = re.search(r"DECLARE_INTERFACE_IID_\(" + interface + r",[^\n]+\)\s*\{(.*?)\n\};", header, re.S)
        if not block:
            raise ValueError(f"Missing SDK interface {interface}")
        methods = []
        for match in re.finditer(r"STDMETHOD(?:_\(([^,]+),\s*(\w+)\)|\((\w+)\))\s*\((.*?)\)\s*PURE;", block.group(1), re.S):
            methods.append((match.group(1) or "HRESULT", match.group(2) or match.group(3), parameters(match.group(4))))
        if not methods or methods[0][1] != "QueryInterface":
            raise ValueError(f"Malformed method list for {interface}")
        result[interface] = methods
    return result


def generate(parsed, directory):
    preamble = "// Generated by tools/ownership/generate_d3d9_forwarders.py from MinGW d3d9.h.\n// Edit the generator or handwritten ownership rules, not this file.\n"
    classes, bodies = [preamble], [preamble]
    bodies.append('// Ordinary-return ABI shells only; handwritten helpers retain exceptions.\n'
                  '#if !defined(__GNUC__) || defined(__clang__)\n'
                  '#error "Generated ownership ABI shells require verified GCC scoped exception policy."\n'
                  '#endif\n#pragma GCC push_options\n#pragma GCC optimize("no-exceptions")\n')
    count = 0
    for interface, methods in parsed.items():
        kind = KINDS[interface]
        classes.append(f"struct {kind} final : {interface}, Node {{\n    {interface}* native_;\n")
        if kind in {"Factory", "Device"}:
            classes.append("    Options options;\n")
        if kind == "Device":
            classes.append("    std::vector<IUnknown*> renderer_resources;\n    bool retiring = false, resetting = false, lost = false;\n")
            classes.append("    CopyDepth copy_depth;\n    ObservedExecutionState execution;\n    std::atomic<bool> recording_state_block{false};\n    HRESULT buffer_tracking_status = S_OK;\n    std::uint64_t buffer_lock_generation = 1;\n    std::shared_ptr<FiniteOwner> finite_owner;\n    HRESULT finite_status = S_FALSE;\n")
        if kind == "Query":
            classes.append("    ExecutionQuery execution_query;\n")
        classes.append(f"    {kind}({interface}* native, Node* owner)\n        : Node(Kind::{kind}, native, owner), native_(native) {{ application = static_cast<{interface}*>(this); }}\n")
        for ret, name, params in methods:
            count += 1
            signature = ", ".join(f"{typ} {arg}" for typ, arg in params)
            args = [arg for _, arg in params]
            classes.append(f"    {ret} WINAPI {name}({signature}) override;\n")
            bodies.append(f"{ret} WINAPI {kind}::{name}({signature}) {{\n")
            bodies.append("    ApplicationAdmissionAbi admission(process_admission_monitor());\n")
            if name == "SetPrivateData":
                bodies.append(f"    if ({args[-1]} & D3DSPD_IUNKNOWN) admission_veto(process_admission_monitor(), AdmissionVeto::PrivateUnknown);\n")
            if kind == "Factory" and name == "RegisterSoftwareDevice":
                bodies.append(f"    if ({args[0]}) admission_veto(process_admission_monitor(), AdmissionVeto::UnobservedRoute);\n")
            for typ, arg in params:
                if re.fullmatch(r"HANDLE\s*\*", typ):
                    bodies.append(f"    if ({arg}) admission_veto(process_admission_monitor(), AdmissionVeto::ExternalResource);\n")
            if name == "QueryInterface":
                body = f"return query(this, {', '.join(args)});"
            elif name == "AddRef":
                body = "return add_ref(this);"
            elif name == "Release":
                body = "return release(this, admission);"
            elif name == "GetDevice":
                body = f"return get_device(this, {args[0]});"
            elif name == "GetDirect3D":
                body = f"return get_factory(this, {args[0]});"
            elif name == "GetContainer":
                body = f"return get_container(this, {', '.join(args)});"
            elif kind == "Factory" and name == "CreateDevice":
                body = f"return create_device(this, {', '.join(args)});"
            elif kind == "Device" and name == "Reset":
                body = f"return reset_device(this, {args[0]});"
            elif kind == "Device" and name == "Clear":
                body = f"return clear_device(this, {', '.join(args)});"
            elif kind == "Device" and name in {"CreateVertexBuffer", "CreateIndexBuffer"}:
                helper = "create_vertex_buffer" if name == "CreateVertexBuffer" else "create_index_buffer"
                body = f"return {helper}(this, {', '.join(args)});"
            elif kind in {"VertexBuffer", "IndexBuffer"} and name == "GetDesc":
                body = f"return buffer_desc(this, {args[0]});"
            elif kind in {"VertexBuffer", "IndexBuffer"} and name == "Lock":
                body = f"return buffer_lock(this, {', '.join(args)});"
            elif kind in {"VertexBuffer", "IndexBuffer"} and name == "Unlock":
                body = "return buffer_unlock(this);"
            elif kind == "Texture" and name == "LockRect":
                body = f"return texture_lock(this, {', '.join(args)});"
            elif kind == "Texture" and name == "UnlockRect":
                body = f"return texture_unlock(this, {args[0]});"
            elif kind == "Texture" and name == "GetSurfaceLevel":
                body = f"return texture_surface_level(this, {', '.join(args)});"
            elif kind == "Surface" and name == "LockRect":
                body = f"return surface_lock(this, __builtin_return_address(0), {', '.join(args)});"
            elif kind == "Surface" and name == "UnlockRect":
                body = "return surface_unlock(this, __builtin_return_address(0));"
            elif kind in {"VertexBuffer", "IndexBuffer"} and name in {"SetPrivateData", "FreePrivateData"}:
                body = f"return buffer_private_result(this, {args[0]}, native_->{name}({', '.join(args)}));"
            elif kind == "Device" and name == "ProcessVertices":
                body = f"return process_vertices(this, {', '.join(args)});"
            elif kind == "Device" and name in {"BeginScene", "EndScene"}:
                body = f"return scene_transition(this, {'true' if name == 'BeginScene' else 'false'});"
            elif kind == "Device" and name == "CreateQuery":
                body = f"return create_query(this, {', '.join(args)});"
            elif kind == "Query" and name == "Issue":
                body = f"return issue_query(this, {args[0]});"
            elif kind == "Device" and name == "BeginStateBlock":
                body = "return begin_state_block(this);"
            elif kind == "Device" and name == "EndStateBlock":
                body = f"return end_state_block(this, {args[0]});"
            else:
                outputs = [(typ, arg) for typ, arg in params if re.fullmatch(r"IDirect3D\w+\s*\*\s*\*", typ)]
                inputs = {arg for typ, arg in params if re.fullmatch(r"IDirect3D\w+\s*\*", typ)}
                if len(outputs) > 1:
                    raise ValueError(f"Multiple interface outputs: {interface}::{name}")
                actual = [f"unwrap(device_of(this), {arg})" if arg in inputs else arg for arg in args]
                if outputs:
                    typ, arg = outputs[0]
                    interface_out = typ.replace("*", "").strip()
                    actual[args.index(arg)] = f"{arg} ? &owned : nullptr"
                    body = (f"{interface_out}* owned = untouched_output<{interface_out}>();\n"
                            f"    const HRESULT hr = native_->{name}({', '.join(actual)});\n"
                            f"    return output(device_of(this), hr, owned, {arg});")
                elif ret == "HRESULT" and kind != "Factory":
                    body = f"return observe_result(device_of(this), native_->{name}({', '.join(actual)}));"
                else:
                    body = f"return native_->{name}({', '.join(actual)});"
            bodies.append("    " + body + "\n}\n")
        classes.append("};\n")
    bodies.append("#pragma GCC pop_options\n")
    directory.mkdir(parents=True, exist_ok=True)
    (directory / "d3d9_classes_inc.h").write_text("".join(classes))
    (directory / "d3d9_forwarders_inc.h").write_text("".join(bodies))
    print(f"Generated {len(parsed)} interfaces, {count} ABI methods in {directory}")


def discover_header(compiler):
    include = Path(subprocess.check_output([compiler, "-print-file-name=include"], text=True).strip()).resolve()
    for parent in include.parents:
        candidate = parent / "i686-w64-mingw32/include/d3d9.h"
        if candidate.exists():
            return candidate
    raise FileNotFoundError("Pass --header with the SDK's d3d9.h path")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--header", type=Path)
    parser.add_argument("--compiler", default="i686-w64-mingw32-g++")
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[2] / "src/ownership")
    args = parser.parse_args()
    header = args.header or discover_header(args.compiler)
    generate(parse(header.read_text()), args.output)


if __name__ == "__main__":
    main()
