// Generated by tools/build/fog_family_chroma.py from the pinned packets; do not edit.
// {profile id, mean chroma r, g, b}: sum(rgb) / sum(density) over the 128^3 volume.
{1u, {0.05158844f, 0.26947787f, 1.0f}}, // bluewell, atlas 4529497a5e1feda3
{2u, {0.20072728f, 1.0f, 0.120704934f}}, // foggreenoutlands, atlas d0342a05fe0e0421
{3u, {0.52384865f, 0.78991854f, 1.0f}}, // fogbluedistance, atlas f3e7deb8683a2768
{4u, {0.44454795f, 1.0f, 0.7954476f}}, // fogcyancorner, atlas 2535977d29170e4f
{5u, {1.0f, 0.14210647f, 0.14979388f}}, // fogdeepred, atlas 29c3b8ac38ee8ccb
{6u, {0.33964935f, 1.0f, 0.031233514f}}, // foggreeneye, atlas 4004b37835958771
{7u, {1.0f, 0.43631834f, 0.2759431f}}, // fogparanid, atlas 489ad7b5d0ac188a
{8u, {1.0f, 0.35385215f, 0.55125433f}}, // fogred, atlas aa4d4724f3428224
{9u, {0.022869607f, 0.9747667f, 0.9483355f}}, // uranus, atlas b81b7093c05493eb
{10u, {0.022869607f, 0.9747667f, 0.9483355f}}, // uranus3, atlas b81b7093c05493eb
{11u, {1.0f, 0.30731556f, 0.19092785f}}, // whitenexus, atlas e3e0dcbe152dc86b
{12u, {0.012956201f, 1.0f, 0.18493533f}}, // fogblue, atlas c8f68b7392593b3e
{13u, {0.0942173f, 0.0f, 1.0f}}, // fogkhaak, atlas 326c0a8edae60e02
{14u, {0.0942173f, 0.0f, 1.0f}}, // khaakhive, atlas 326c0a8edae60e02
