// Generated by tools/analysis/inspect_motion_output_profiles.py; derived metadata only.
// Reviewed full shader sweep SHA256:
//   794be7b6ceccfc2db45f29369982a4f61a568114f08cef303a75fd3ce9bbc737
// Reference pair, see docs/reverse-engineering/motion-output-candidate.md:
//   vs_53a0a641107ed76c + ps_8759c7838bbc86c2
// Rows are transformable captured material pairs, ordered by descending
// captured Scene draws then by vertex and pixel fingerprint.
// Classes emitted:
//   A_reference_registers = MotionOutputClass::ReferenceRegisters
//   B_relocated_registers = MotionOutputClass::RelocatedRegisters
//   C_relocated_registers_with_static_branches = MotionOutputClass::RelocatedRegistersWithBranches
// RelocatedRegistersWithBranches rows: the pixel program holds only
// if b#/else/endif blocks (boolean constant conditions, nesting depth <= 1,
// balanced, depth 0 at the append point); the transformer revalidates this.
// Field order:
//   vertex_fingerprint, vertex_dword_count, vertex_version
//   pixel_fingerprint, pixel_dword_count, pixel_version
//   transformation_class, matrix_register, position_temporary
//   position_dp4_dwords[4], position_lane_masks[4], vertex_declaration_insert_dword
//   vertex_arithmetic_insert_dword, pixel_definition_insert_dword, pixel_declaration_insert_dword
//   pixel_append_dword, vertex_output_register, texcoord_index
//   pixel_input_register, pixel_temporary_base, pixel_output_register
//   vertex_constant_base, pixel_constant_base, light_loop_bound_required
//   light_loop_max_count
// DWORD offsets are zero-based from the version token and include comments.
// Offsets and registers are inputs to a transformation that must still
// revalidate the program it is given; they are not an eligibility decision.
// light_loop_bound_required means the vertex program reads constants
// relatively: refuse the variant unless integer i0.x is checked in
// [0, light_loop_max_count] at draw time.
{0x494fe349b8bc12ecull, 526, 0xfffe0300u,
 0xfffdabd910793abaull, 1648, 0xffff0300u,
 MotionOutputClass::RelocatedRegistersWithBranches, 24, 1, {450, 454, 458, 462}, {1, 2, 4, 8},
 335, 466, 1280, 1313, 1647,
 6, 4, 6, 6, 1, 252, 216, true, 8},
{0x53a0a641107ed76cull, 526, 0xfffe0300u,
 0x8759c7838bbc86c2ull, 1260, 0xffff0300u,
 MotionOutputClass::ReferenceRegisters, 24, 1, {450, 454, 458, 462}, {1, 2, 4, 8},
 335, 466, 1047, 1074, 1259,
 6, 4, 5, 5, 1, 252, 216, true, 8},
{0x37c34a7478544c14ull, 768, 0xfffe0300u,
 0x5f82ecacd39529cdull, 1765, 0xffff0300u,
 MotionOutputClass::RelocatedRegistersWithBranches, 24, 2, {633, 637, 641, 645}, {1, 2, 4, 8},
 500, 649, 1325, 1370, 1764,
 9, 7, 8, 6, 1, 252, 216, true, 8},
{0x4944d81dfe531b37ull, 556, 0xfffe0300u,
 0xca6bfa4a6cca7e2aull, 1328, 0xffff0300u,
 MotionOutputClass::RelocatedRegisters, 24, 2, {477, 481, 485, 489}, {1, 2, 4, 8},
 344, 493, 1062, 1095, 1327,
 7, 5, 6, 7, 1, 252, 216, true, 8},
{0xb0602757fce6e870ull, 520, 0xfffe0300u,
 0x517540ae6d5e5410ull, 397, 0xffff0300u,
 MotionOutputClass::ReferenceRegisters, 24, 1, {441, 445, 449, 453}, {1, 2, 4, 8},
 335, 457, 233, 257, 396,
 6, 4, 5, 5, 1, 252, 216, true, 8},
{0x4944d81dfe531b37ull, 556, 0xfffe0300u,
 0x5e0a10fe752b6140ull, 1354, 0xffff0300u,
 MotionOutputClass::RelocatedRegisters, 24, 2, {477, 481, 485, 489}, {1, 2, 4, 8},
 344, 493, 1062, 1098, 1353,
 7, 5, 6, 7, 1, 252, 216, true, 8},
{0x37c34a7478544c14ull, 768, 0xfffe0300u,
 0xf1b0e820c7b488c3ull, 1791, 0xffff0300u,
 MotionOutputClass::RelocatedRegistersWithBranches, 24, 2, {633, 637, 641, 645}, {1, 2, 4, 8},
 500, 649, 1325, 1373, 1790,
 9, 7, 8, 6, 1, 252, 216, true, 8},
{0x53a0a641107ed76cull, 526, 0xfffe0300u,
 0x63f96eba9eea7880ull, 1292, 0xffff0300u,
 MotionOutputClass::ReferenceRegisters, 24, 1, {450, 454, 458, 462}, {1, 2, 4, 8},
 335, 466, 1053, 1083, 1291,
 6, 4, 5, 5, 1, 252, 216, true, 8},
{0x167eb2d5629ab9d3ull, 566, 0xfffe0300u,
 0xd44db87778a43b61ull, 448, 0xffff0300u,
 MotionOutputClass::RelocatedRegisters, 24, 2, {471, 475, 479, 483}, {1, 2, 4, 8},
 347, 487, 241, 274, 447,
 8, 6, 7, 5, 1, 252, 216, true, 8},
{0x494fe349b8bc12ecull, 526, 0xfffe0300u,
 0xe6794b6ec37ff71aull, 1674, 0xffff0300u,
 MotionOutputClass::RelocatedRegistersWithBranches, 24, 1, {450, 454, 458, 462}, {1, 2, 4, 8},
 335, 466, 1280, 1316, 1673,
 6, 4, 6, 6, 1, 252, 216, true, 8},
{0x53a0a641107ed76cull, 526, 0xfffe0300u,
 0x3b94320087e81945ull, 1264, 0xffff0300u,
 MotionOutputClass::ReferenceRegisters, 24, 1, {450, 454, 458, 462}, {1, 2, 4, 8},
 335, 466, 1047, 1074, 1263,
 6, 4, 5, 5, 1, 252, 216, true, 8},
{0x53a0a641107ed76cull, 526, 0xfffe0300u,
 0x462342e3e5781384ull, 1250, 0xffff0300u,
 MotionOutputClass::ReferenceRegisters, 24, 1, {450, 454, 458, 462}, {1, 2, 4, 8},
 335, 466, 1053, 1080, 1249,
 6, 4, 5, 5, 1, 252, 216, true, 8},
{0x4944d81dfe531b37ull, 556, 0xfffe0300u,
 0x64bac8bb307eb896ull, 1392, 0xffff0300u,
 MotionOutputClass::RelocatedRegisters, 24, 2, {477, 481, 485, 489}, {1, 2, 4, 8},
 344, 493, 1112, 1148, 1391,
 7, 5, 6, 7, 1, 252, 216, true, 8},
{0x494fe349b8bc12ecull, 526, 0xfffe0300u,
 0x7c83ed50c9894e44ull, 1298, 0xffff0300u,
 MotionOutputClass::ReferenceRegisters, 24, 1, {450, 454, 458, 462}, {1, 2, 4, 8},
 335, 466, 1097, 1124, 1297,
 6, 4, 5, 5, 1, 252, 216, true, 8},
{0x4944d81dfe531b37ull, 556, 0xfffe0300u,
 0x0c1f3f0f440e4a0cull, 1366, 0xffff0300u,
 MotionOutputClass::RelocatedRegisters, 24, 2, {477, 481, 485, 489}, {1, 2, 4, 8},
 344, 493, 1112, 1145, 1365,
 7, 5, 6, 7, 1, 252, 216, true, 8},
{0xc30104cb0efb6675ull, 550, 0xfffe0300u,
 0xa66fb1981ba755b2ull, 309, 0xffff0300u,
 MotionOutputClass::RelocatedRegisters, 24, 1, {453, 457, 461, 465}, {1, 2, 4, 8},
 338, 469, 122, 149, 308,
 7, 4, 6, 5, 1, 252, 216, true, 8},
