#!/usr/bin/env python3
"""Generate exact production shader metadata from pinned, reviewed inventories.

Raw archive programs are revalidated locally and never copied to generated
artifacts. Updating either pinned digest requires a new inventory review; this
is not an automatic discovery-to-production promotion tool.
"""
import argparse
import hashlib
import json
from pathlib import Path

from index_shaders import fnv1a64
from inspect_archive_positions import classify

ROOT = Path(__file__).resolve().parents[2]
ARCHIVE_SHA256 = '1617691f1c4e21737cf1bb604b4e3155510d11947acc78b2e40877b10bde431c'
SWEEP_SHA256 = '794be7b6ceccfc2db45f29369982a4f61a568114f08cef303a75fd3ce9bbc737'
CATEGORIES = {'homogeneous_row_dots': 'HomogeneousRowDots', 'direct_clip_xyzw': 'DirectClipXYZW',
              'direct_clip_xyz_w_one': 'DirectClipXYZWOne',
              'view_xy_billboard_projection': 'ViewXYBillboardProjection'}
REVIEWED_VERSIONS = (0xfffe0101, 0xfffe0200, 0xfffe0201, 0xfffe0300)
CONSTRUCTOR = 'MadXYZIdentityWFromX'


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_pinned(path, expected):
    data = path.read_bytes()
    if hashlib.sha256(data).hexdigest() != expected:
        raise ValueError('Inventory differs from independently reviewed digest: ' + str(path))
    return json.loads(data)


def replay_metadata(proof):
    """Retain distinctions lost by the ordinary finite-input algebraic contract.

    The caller first reproduces this complete proof from the pinned raw program.
    Offsets select original issue order, not a guessed order of matrix rows.
    Constructor semantics are already fixed by prove()'s exact operand checks.
    These facts enable separate replay qualification; they do not grant it.
    """
    if (proof['qualified_position_math'] is not True or
            proof['contract'] != 'FloatXYZForceWOneSubmittedRowDots' or
            proof['input_w_used'] is not False):
        raise ValueError('Unproved homogeneous position contract')
    offsets = proof['position_dot_dwords_xyzw']
    if (len(offsets) != 4 or any(type(n) is not int or n <= 0 for n in offsets) or
            len(set(offsets)) != 4):
        raise ValueError('Invalid position instruction offsets')
    order = ''.join('XYZW'[lane] for lane in sorted(range(4), key=lambda lane: offsets[lane]))
    return dict(shader_version=int(proof['version'], 0), position_write_order=order,
                homogeneous_constructor=CONSTRUCTOR)


def emit_tables(vertices, pixels):
    """Pure deterministic metadata rendering, also used by original-data tests."""
    seen = set()
    for items, limit in ((vertices, 769), (pixels, 1883)):
        for item in items:
            key = int(item['fnv1a64'], 16)
            if not 0 <= key <= 0xffffffffffffffff or len(item['fnv1a64']) != 16:
                raise ValueError('Invalid full-program fingerprint')
            if key in seen:
                raise ValueError('Ambiguous/repeated full-program fingerprint')
            if type(item['word_count']) is not int or not 0 < item['word_count'] <= limit:
                raise ValueError('Program length exceeds reviewed stage bound')
            seen.add(key)
    prefix = ('// Generated by tools/analysis/generate_shader_profiles.py; derived metadata only.\n'
              f'// Reviewed archive position SHA256: {ARCHIVE_SHA256}\n'
              f'// Reviewed full shader sweep SHA256: {SWEEP_SHA256}\n')
    rigid, exceptions, coverage = [], [], []
    for item in sorted(vertices, key=lambda p: int(p['fnv1a64'], 16)):
        category = item['position_path']
        if category not in CATEGORIES:
            raise ValueError('Unreviewed position category')
        head = f"{{0x{item['fnv1a64']}ull, {item['word_count']}"
        if category == 'homogeneous_row_dots':
            if item['matrix_register'] not in (0, 6, 24):
                raise ValueError('Unreviewed matrix layout')
            named = 'true' if item['named_world_view_projection'] else 'false'
            version = item['shader_version']
            order = item['position_write_order']
            constructor = item['homogeneous_constructor']
            if type(version) is not int or version not in REVIEWED_VERSIONS:
                raise ValueError('Unreviewed vertex shader model')
            if order not in ('XYZW', 'WXYZ') or (order == 'WXYZ' and version != 0xfffe0200):
                raise ValueError('Unreviewed position issue order/model combination')
            if constructor != CONSTRUCTOR:
                raise ValueError('Unreviewed homogeneous constructor')
            rigid.append(f"{head}, {item['matrix_register']}, {named}, 0x{version:08x}u, "
                         f"PositionWriteOrder::{order}, HomogeneousConstructor::{constructor}}},")
        else:
            exceptions.append(f'{head}, VertexPositionPath::{CATEGORIES[category]}}},')
    for item in sorted(pixels, key=lambda p: int(p['fnv1a64'], 16)):
        if item['coverage']['qualified'] is True:
            coverage.append(f"{{0x{item['fnv1a64']}ull, {item['word_count']}}},")
    return {'rigid_position_profiles_inc.h': prefix + '\n'.join(rigid) + '\n',
            'position_path_profiles_inc.h': prefix + '\n'.join(exceptions) + '\n',
            'pixel_coverage_profiles_inc.h': prefix + '\n'.join(coverage) + '\n'}


def generate(archive_path, sweep_path, raw_directory):
    from inspect_pixel_coverage import inspect as inspect_coverage
    archive = read_pinned(archive_path, ARCHIVE_SHA256)
    sweep = read_pinned(sweep_path, SWEEP_SHA256)
    if len(archive['programs']) != 256 or len(sweep['programs']) != 751:
        raise ValueError('Reviewed inventory count changed')
    by_id = {p['id']: p for p in sweep['programs']}
    vertices, pixels = [], []
    for item in archive['programs']:
        p = by_id[item['id']]
        code = (raw_directory / (item['id'] + '.bin')).read_bytes()
        if hashlib.sha256(code).hexdigest() != p['sha256'] or fnv1a64(code) != p['fnv1a64']:
            raise ValueError('Local vertex program differs from reviewed bytes')
        fresh = classify(code)
        if fresh != {key: item[key] for key in ('category', 'proof')}:
            raise ValueError('Vertex proof no longer reproduces')
        proof = item['proof']
        result = {'id': item['id'], 'fnv1a64': p['fnv1a64'], 'sha256': p['sha256'],
                  'word_count': len(code) // 4, 'position_path': item['category']}
        if item['category'] == 'homogeneous_row_dots':
            result.update(matrix_register=proof['matrix_first_register'],
                named_world_view_projection='g_mWorldViewProjection' in proof['matrix_names_only'])
            result.update(replay_metadata(proof))
        vertices.append(result)
    for p in sweep['programs']:
        if p['stage'] != 'ps':
            continue
        code = (raw_directory / (p['id'] + '.bin')).read_bytes()
        if hashlib.sha256(code).hexdigest() != p['sha256'] or fnv1a64(code) != p['fnv1a64']:
            raise ValueError('Local pixel program differs from reviewed bytes')
        pixels.append({'id': p['id'], 'fnv1a64': p['fnv1a64'], 'sha256': p['sha256'],
                       'word_count': len(code) // 4, 'coverage': inspect_coverage(code, p['features'])})
    tables = emit_tables(vertices, pixels)
    result = {'schema': 2, 'scope': 'Generated exact shader metadata; runtime input/history/coverage and replay qualification remain separate',
              'reviewed_archive_sha256': ARCHIVE_SHA256, 'reviewed_sweep_sha256': SWEEP_SHA256,
              'vertex_program_count': len(vertices), 'rigid_profile_count': sum(p['position_path'] == 'homogeneous_row_dots' for p in vertices),
              'pixel_program_count': len(pixels), 'pixel_coverage_profile_count': sum(p['coverage']['qualified'] for p in pixels),
              'maximum_vertex_words': max(p['word_count'] for p in vertices),
              'maximum_pixel_words': max(p['word_count'] for p in pixels),
              'tool_source_sha256': {name: digest(Path(__file__).with_name(name)) for name in
                  ('generate_shader_profiles.py', 'inspect_pixel_coverage.py', 'inspect_archive_positions.py',
                   'inspect_rigid_positions.py', 'index_shaders.py', 'shader_constants.py')},
              'generated_include_sha256': {name: hashlib.sha256(text.encode()).hexdigest() for name, text in tables.items()},
              'vertices': vertices, 'pixels': pixels}
    return tables, result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--raw-directory', type=Path, default=Path('/tmp/x3-shader-sweep/programs'))
    parser.add_argument('--output-directory', type=Path, default=ROOT / 'src/renderer')
    parser.add_argument('--report', type=Path, default=ROOT / 'verification/results/shader-profile-registry.json')
    parser.add_argument('--check', action='store_true', help='Reject stale generated files; do not write anything')
    args = parser.parse_args()
    tables, result = generate(ROOT / 'verification/results/archive-position-paths.json',
                             ROOT / 'verification/results/shader-sweep-inventory.json', args.raw_directory)
    outputs = {args.output_directory / name: text for name, text in tables.items()}
    outputs[args.report] = json.dumps(result, indent=2) + '\n'
    for path, text in outputs.items():
        if args.check:
            if path.read_text() != text:
                raise ValueError('Stale generated artifact: ' + str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    print(json.dumps({key: result[key] for key in ('vertex_program_count', 'rigid_profile_count',
                                                   'pixel_program_count', 'pixel_coverage_profile_count')}))


if __name__ == '__main__':
    main()
